<?php

namespace Database\Seeders;

use App\Models\Option;
use Illuminate\Database\Seeder;

class OptionsSeeder extends Seeder
{
    public function run()
    {
        $options = [
        // ─── toothNumbers ── (32)
        ['category' => 'toothNumbers', 'label' => 'Tooth 11 - Upper Right Central Incisor', 'value' => '11', 'sort_order' => 0],
        ['category' => 'toothNumbers', 'label' => 'Tooth 12 - Upper Right Lateral Incisor', 'value' => '12', 'sort_order' => 1],
        ['category' => 'toothNumbers', 'label' => 'Tooth 13 - Upper Right Canine', 'value' => '13', 'sort_order' => 2],
        ['category' => 'toothNumbers', 'label' => 'Tooth 14 - Upper Right 1st Premolar', 'value' => '14', 'sort_order' => 3],
        ['category' => 'toothNumbers', 'label' => 'Tooth 15 - Upper Right 2nd Premolar', 'value' => '15', 'sort_order' => 4],
        ['category' => 'toothNumbers', 'label' => 'Tooth 16 - Upper Right 1st Molar', 'value' => '16', 'sort_order' => 5],
        ['category' => 'toothNumbers', 'label' => 'Tooth 17 - Upper Right 2nd Molar', 'value' => '17', 'sort_order' => 6],
        ['category' => 'toothNumbers', 'label' => 'Tooth 18 - Upper Right 3rd Molar', 'value' => '18', 'sort_order' => 7],
        ['category' => 'toothNumbers', 'label' => 'Tooth 21 - Upper Left Central Incisor', 'value' => '21', 'sort_order' => 8],
        ['category' => 'toothNumbers', 'label' => 'Tooth 22 - Upper Left Lateral Incisor', 'value' => '22', 'sort_order' => 9],
        ['category' => 'toothNumbers', 'label' => 'Tooth 23 - Upper Left Canine', 'value' => '23', 'sort_order' => 10],
        ['category' => 'toothNumbers', 'label' => 'Tooth 24 - Upper Left 1st Premolar', 'value' => '24', 'sort_order' => 11],
        ['category' => 'toothNumbers', 'label' => 'Tooth 25 - Upper Left 2nd Premolar', 'value' => '25', 'sort_order' => 12],
        ['category' => 'toothNumbers', 'label' => 'Tooth 26 - Upper Left 1st Molar', 'value' => '26', 'sort_order' => 13],
        ['category' => 'toothNumbers', 'label' => 'Tooth 27 - Upper Left 2nd Molar', 'value' => '27', 'sort_order' => 14],
        ['category' => 'toothNumbers', 'label' => 'Tooth 28 - Upper Left 3rd Molar', 'value' => '28', 'sort_order' => 15],
        ['category' => 'toothNumbers', 'label' => 'Tooth 31 - Lower Left Central Incisor', 'value' => '31', 'sort_order' => 16],
        ['category' => 'toothNumbers', 'label' => 'Tooth 32 - Lower Left Lateral Incisor', 'value' => '32', 'sort_order' => 17],
        ['category' => 'toothNumbers', 'label' => 'Tooth 33 - Lower Left Canine', 'value' => '33', 'sort_order' => 18],
        ['category' => 'toothNumbers', 'label' => 'Tooth 34 - Lower Left 1st Premolar', 'value' => '34', 'sort_order' => 19],
        ['category' => 'toothNumbers', 'label' => 'Tooth 35 - Lower Left 2nd Premolar', 'value' => '35', 'sort_order' => 20],
        ['category' => 'toothNumbers', 'label' => 'Tooth 36 - Lower Left 1st Molar', 'value' => '36', 'sort_order' => 21],
        ['category' => 'toothNumbers', 'label' => 'Tooth 37 - Lower Left 2nd Molar', 'value' => '37', 'sort_order' => 22],
        ['category' => 'toothNumbers', 'label' => 'Tooth 38 - Lower Left 3rd Molar', 'value' => '38', 'sort_order' => 23],
        ['category' => 'toothNumbers', 'label' => 'Tooth 41 - Lower Right Central Incisor', 'value' => '41', 'sort_order' => 24],
        ['category' => 'toothNumbers', 'label' => 'Tooth 42 - Lower Right Lateral Incisor', 'value' => '42', 'sort_order' => 25],
        ['category' => 'toothNumbers', 'label' => 'Tooth 43 - Lower Right Canine', 'value' => '43', 'sort_order' => 26],
        ['category' => 'toothNumbers', 'label' => 'Tooth 44 - Lower Right 1st Premolar', 'value' => '44', 'sort_order' => 27],
        ['category' => 'toothNumbers', 'label' => 'Tooth 45 - Lower Right 2nd Premolar', 'value' => '45', 'sort_order' => 28],
        ['category' => 'toothNumbers', 'label' => 'Tooth 46 - Lower Right 1st Molar', 'value' => '46', 'sort_order' => 29],
        ['category' => 'toothNumbers', 'label' => 'Tooth 47 - Lower Right 2nd Molar', 'value' => '47', 'sort_order' => 30],
        ['category' => 'toothNumbers', 'label' => 'Tooth 48 - Lower Right 3rd Molar', 'value' => '48', 'sort_order' => 31],
        // ─── toothSurfaces ── (10)
        ['category' => 'toothSurfaces', 'label' => 'Occlusal (O)', 'value' => 'O', 'sort_order' => 0],
        ['category' => 'toothSurfaces', 'label' => 'Mesial (M)', 'value' => 'M', 'sort_order' => 1],
        ['category' => 'toothSurfaces', 'label' => 'Distal (D)', 'value' => 'D', 'sort_order' => 2],
        ['category' => 'toothSurfaces', 'label' => 'Buccal (B)', 'value' => 'B', 'sort_order' => 3],
        ['category' => 'toothSurfaces', 'label' => 'Lingual (L)', 'value' => 'L', 'sort_order' => 4],
        ['category' => 'toothSurfaces', 'label' => 'Incisal (I)', 'value' => 'I', 'sort_order' => 5],
        ['category' => 'toothSurfaces', 'label' => 'MOD (Mesial-Occlusal-Distal)', 'value' => 'MOD', 'sort_order' => 6],
        ['category' => 'toothSurfaces', 'label' => 'MO (Mesial-Occlusal)', 'value' => 'MO', 'sort_order' => 7],
        ['category' => 'toothSurfaces', 'label' => 'OD (Occlusal-Distal)', 'value' => 'OD', 'sort_order' => 8],
        ['category' => 'toothSurfaces', 'label' => 'BL (Buccal-Lingual)', 'value' => 'BL', 'sort_order' => 9],
        // ─── treatmentTypes ── (16)
        ['category' => 'treatmentTypes', 'label' => 'Restoration / Filling', 'value' => 'Restoration', 'sort_order' => 0],
        ['category' => 'treatmentTypes', 'label' => 'Extraction', 'value' => 'Extraction', 'sort_order' => 1],
        ['category' => 'treatmentTypes', 'label' => 'Root Canal Treatment', 'value' => 'RCT', 'sort_order' => 2],
        ['category' => 'treatmentTypes', 'label' => 'Scaling & Polishing', 'value' => 'Scaling', 'sort_order' => 3],
        ['category' => 'treatmentTypes', 'label' => 'Crown', 'value' => 'Crown', 'sort_order' => 4],
        ['category' => 'treatmentTypes', 'label' => 'Bridge', 'value' => 'Bridge', 'sort_order' => 5],
        ['category' => 'treatmentTypes', 'label' => 'Denture', 'value' => 'Denture', 'sort_order' => 6],
        ['category' => 'treatmentTypes', 'label' => 'Dental Implant', 'value' => 'Implant', 'sort_order' => 7],
        ['category' => 'treatmentTypes', 'label' => 'Orthodontic Treatment', 'value' => 'Orthodontic', 'sort_order' => 8],
        ['category' => 'treatmentTypes', 'label' => 'Periodontal Treatment', 'value' => 'Periodontal', 'sort_order' => 9],
        ['category' => 'treatmentTypes', 'label' => 'Fluoride Application', 'value' => 'Fluoride', 'sort_order' => 10],
        ['category' => 'treatmentTypes', 'label' => 'Fissure Sealant', 'value' => 'Sealant', 'sort_order' => 11],
        ['category' => 'treatmentTypes', 'label' => 'Bleaching / Whitening', 'value' => 'Bleaching', 'sort_order' => 12],
        ['category' => 'treatmentTypes', 'label' => 'Veneer', 'value' => 'Veneer', 'sort_order' => 13],
        ['category' => 'treatmentTypes', 'label' => 'Gum Surgery', 'value' => 'GumSurgery', 'sort_order' => 14],
        ['category' => 'treatmentTypes', 'label' => 'Biopsy', 'value' => 'Biopsy', 'sort_order' => 15],
        // ─── oralExaminationFindings ── (17)
        ['category' => 'oralExaminationFindings', 'label' => 'Normal oral mucosa', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'oralExaminationFindings', 'label' => 'Gingivitis', 'value' => 'Gingivitis', 'sort_order' => 1],
        ['category' => 'oralExaminationFindings', 'label' => 'Periodontitis', 'value' => 'Periodontitis', 'sort_order' => 2],
        ['category' => 'oralExaminationFindings', 'label' => 'Dental caries', 'value' => 'Caries', 'sort_order' => 3],
        ['category' => 'oralExaminationFindings', 'label' => 'Pulpitis', 'value' => 'Pulpitis', 'sort_order' => 4],
        ['category' => 'oralExaminationFindings', 'label' => 'Periapical abscess', 'value' => 'Abscess', 'sort_order' => 5],
        ['category' => 'oralExaminationFindings', 'label' => 'Oral ulcer', 'value' => 'Ulcer', 'sort_order' => 6],
        ['category' => 'oralExaminationFindings', 'label' => 'Leukoplakia', 'value' => 'Leukoplakia', 'sort_order' => 7],
        ['category' => 'oralExaminationFindings', 'label' => 'Erythroplakia', 'value' => 'Erythroplakia', 'sort_order' => 8],
        ['category' => 'oralExaminationFindings', 'label' => 'Oral candidiasis', 'value' => 'Candidiasis', 'sort_order' => 9],
        ['category' => 'oralExaminationFindings', 'label' => 'Oral lichen planus', 'value' => 'LichenPlanus', 'sort_order' => 10],
        ['category' => 'oralExaminationFindings', 'label' => 'TMJ disorder', 'value' => 'TMJ', 'sort_order' => 11],
        ['category' => 'oralExaminationFindings', 'label' => 'Malocclusion', 'value' => 'Malocclusion', 'sort_order' => 12],
        ['category' => 'oralExaminationFindings', 'label' => 'Impacted tooth', 'value' => 'Impacted', 'sort_order' => 13],
        ['category' => 'oralExaminationFindings', 'label' => 'Missing tooth', 'value' => 'Missing', 'sort_order' => 14],
        ['category' => 'oralExaminationFindings', 'label' => 'Fractured tooth', 'value' => 'Fractured', 'sort_order' => 15],
        ['category' => 'oralExaminationFindings', 'label' => 'Worn dentition / Attrition', 'value' => 'Attrition', 'sort_order' => 16],
        // ─── periodontalCharting ── (10)
        ['category' => 'periodontalCharting', 'label' => 'Probing Depth 1-3mm (Healthy)', 'value' => '1-3', 'sort_order' => 0],
        ['category' => 'periodontalCharting', 'label' => 'Probing Depth 4-5mm (Mild)', 'value' => '4-5', 'sort_order' => 1],
        ['category' => 'periodontalCharting', 'label' => 'Probing Depth 6-7mm (Moderate)', 'value' => '6-7', 'sort_order' => 2],
        ['category' => 'periodontalCharting', 'label' => 'Probing Depth 8mm+ (Severe)', 'value' => '8+', 'sort_order' => 3],
        ['category' => 'periodontalCharting', 'label' => 'Bleeding on Probing (BOP)', 'value' => 'BOP', 'sort_order' => 4],
        ['category' => 'periodontalCharting', 'label' => 'Gingival Recession', 'value' => 'Recession', 'sort_order' => 5],
        ['category' => 'periodontalCharting', 'label' => 'Furcation Involvement', 'value' => 'Furcation', 'sort_order' => 6],
        ['category' => 'periodontalCharting', 'label' => 'Mobility Grade I', 'value' => 'Mobility1', 'sort_order' => 7],
        ['category' => 'periodontalCharting', 'label' => 'Mobility Grade II', 'value' => 'Mobility2', 'sort_order' => 8],
        ['category' => 'periodontalCharting', 'label' => 'Mobility Grade III', 'value' => 'Mobility3', 'sort_order' => 9],
        // ─── treatmentPhases ── (3)
        ['category' => 'treatmentPhases', 'label' => 'Phase 1 - Initial / Urgent Care', 'value' => 'Phase 1', 'sort_order' => 0],
        ['category' => 'treatmentPhases', 'label' => 'Phase 2 - Restorative / Rehabilitative', 'value' => 'Phase 2', 'sort_order' => 1],
        ['category' => 'treatmentPhases', 'label' => 'Phase 3 - Cosmetic / Final Restoration', 'value' => 'Phase 3', 'sort_order' => 2],
        // ─── anaesthesiaTypes ── (5)
        ['category' => 'anaesthesiaTypes', 'label' => 'Local Anaesthesia', 'value' => 'Local', 'sort_order' => 0],
        ['category' => 'anaesthesiaTypes', 'label' => 'Regional Block', 'value' => 'Regional', 'sort_order' => 1],
        ['category' => 'anaesthesiaTypes', 'label' => 'General Anaesthesia', 'value' => 'General', 'sort_order' => 2],
        ['category' => 'anaesthesiaTypes', 'label' => 'Sedation (IV)', 'value' => 'SedationIV', 'sort_order' => 3],
        ['category' => 'anaesthesiaTypes', 'label' => 'Inhalation Sedation', 'value' => 'Inhalation', 'sort_order' => 4],
        // ─── radiographTypes ── (6)
        ['category' => 'radiographTypes', 'label' => 'Intraoral Periapical (IOPA)', 'value' => 'IOPA', 'sort_order' => 0],
        ['category' => 'radiographTypes', 'label' => 'Bitewing', 'value' => 'Bitewing', 'sort_order' => 1],
        ['category' => 'radiographTypes', 'label' => 'Occlusal', 'value' => 'Occlusal', 'sort_order' => 2],
        ['category' => 'radiographTypes', 'label' => 'Panoramic (OPG)', 'value' => 'OPG', 'sort_order' => 3],
        ['category' => 'radiographTypes', 'label' => 'Cephalometric', 'value' => 'Cephalometric', 'sort_order' => 4],
        ['category' => 'radiographTypes', 'label' => 'CBCT', 'value' => 'CBCT', 'sort_order' => 5],
        // ─── labOrderTypes ── (13)
        ['category' => 'labOrderTypes', 'label' => 'Crown (PFM)', 'value' => 'CrownPFM', 'sort_order' => 0],
        ['category' => 'labOrderTypes', 'label' => 'Crown (Full Cast)', 'value' => 'CrownFullCast', 'sort_order' => 1],
        ['category' => 'labOrderTypes', 'label' => 'Crown (Zirconia)', 'value' => 'CrownZirconia', 'sort_order' => 2],
        ['category' => 'labOrderTypes', 'label' => 'Crown (E-max)', 'value' => 'CrownEmax', 'sort_order' => 3],
        ['category' => 'labOrderTypes', 'label' => 'Bridge', 'value' => 'Bridge', 'sort_order' => 4],
        ['category' => 'labOrderTypes', 'label' => 'Partial Denture (Acrylic)', 'value' => 'PartialAcrylic', 'sort_order' => 5],
        ['category' => 'labOrderTypes', 'label' => 'Partial Denture (Cast Partial)', 'value' => 'PartialCast', 'sort_order' => 6],
        ['category' => 'labOrderTypes', 'label' => 'Complete Denture', 'value' => 'CompleteDenture', 'sort_order' => 7],
        ['category' => 'labOrderTypes', 'label' => 'Veneer', 'value' => 'Veneer', 'sort_order' => 8],
        ['category' => 'labOrderTypes', 'label' => 'Inlay / Onlay', 'value' => 'InlayOnlay', 'sort_order' => 9],
        ['category' => 'labOrderTypes', 'label' => 'Orthodontic Appliance', 'value' => 'OrthoAppliance', 'sort_order' => 10],
        ['category' => 'labOrderTypes', 'label' => 'Night Guard', 'value' => 'NightGuard', 'sort_order' => 11],
        ['category' => 'labOrderTypes', 'label' => 'Surgical Guide', 'value' => 'SurgicalGuide', 'sort_order' => 12],
        // ─── labMaterials ── (12)
        ['category' => 'labMaterials', 'label' => 'PFM (Porcelain Fused to Metal)', 'value' => 'PFM', 'sort_order' => 0],
        ['category' => 'labMaterials', 'label' => 'Zirconia', 'value' => 'Zirconia', 'sort_order' => 1],
        ['category' => 'labMaterials', 'label' => 'E-max (Lithium Disilicate)', 'value' => 'E-max', 'sort_order' => 2],
        ['category' => 'labMaterials', 'label' => 'Composite Resin', 'value' => 'Composite', 'sort_order' => 3],
        ['category' => 'labMaterials', 'label' => 'Acrylic Resin', 'value' => 'Acrylic', 'sort_order' => 4],
        ['category' => 'labMaterials', 'label' => 'Metal Alloy (Cobalt Chrome)', 'value' => 'CobaltChrome', 'sort_order' => 5],
        ['category' => 'labMaterials', 'label' => 'Metal Alloy (Nickel Chrome)', 'value' => 'NickelChrome', 'sort_order' => 6],
        ['category' => 'labMaterials', 'label' => 'Titanium', 'value' => 'Titanium', 'sort_order' => 7],
        ['category' => 'labMaterials', 'label' => 'Wax', 'value' => 'Wax', 'sort_order' => 8],
        ['category' => 'labMaterials', 'label' => 'Gypsum / Stone', 'value' => 'Gypsum', 'sort_order' => 9],
        ['category' => 'labMaterials', 'label' => 'Silicone Impression', 'value' => 'Silicone', 'sort_order' => 10],
        ['category' => 'labMaterials', 'label' => 'Other', 'value' => 'Other', 'sort_order' => 11],
        // ─── labShadeGuide ── (16)
        ['category' => 'labShadeGuide', 'label' => 'A1', 'value' => 'A1', 'sort_order' => 0],
        ['category' => 'labShadeGuide', 'label' => 'A2', 'value' => 'A2', 'sort_order' => 1],
        ['category' => 'labShadeGuide', 'label' => 'A3', 'value' => 'A3', 'sort_order' => 2],
        ['category' => 'labShadeGuide', 'label' => 'A3.5', 'value' => 'A3.5', 'sort_order' => 3],
        ['category' => 'labShadeGuide', 'label' => 'A4', 'value' => 'A4', 'sort_order' => 4],
        ['category' => 'labShadeGuide', 'label' => 'B1', 'value' => 'B1', 'sort_order' => 5],
        ['category' => 'labShadeGuide', 'label' => 'B2', 'value' => 'B2', 'sort_order' => 6],
        ['category' => 'labShadeGuide', 'label' => 'B3', 'value' => 'B3', 'sort_order' => 7],
        ['category' => 'labShadeGuide', 'label' => 'B4', 'value' => 'B4', 'sort_order' => 8],
        ['category' => 'labShadeGuide', 'label' => 'C1', 'value' => 'C1', 'sort_order' => 9],
        ['category' => 'labShadeGuide', 'label' => 'C2', 'value' => 'C2', 'sort_order' => 10],
        ['category' => 'labShadeGuide', 'label' => 'C3', 'value' => 'C3', 'sort_order' => 11],
        ['category' => 'labShadeGuide', 'label' => 'C4', 'value' => 'C4', 'sort_order' => 12],
        ['category' => 'labShadeGuide', 'label' => 'D2', 'value' => 'D2', 'sort_order' => 13],
        ['category' => 'labShadeGuide', 'label' => 'D3', 'value' => 'D3', 'sort_order' => 14],
        ['category' => 'labShadeGuide', 'label' => 'D4', 'value' => 'D4', 'sort_order' => 15],
        // ─── labOrderStatuses ── (4)
        ['category' => 'labOrderStatuses', 'label' => 'Ordered', 'value' => 'Ordered', 'sort_order' => 0],
        ['category' => 'labOrderStatuses', 'label' => 'In Progress', 'value' => 'In Progress', 'sort_order' => 1],
        ['category' => 'labOrderStatuses', 'label' => 'Ready', 'value' => 'Ready', 'sort_order' => 2],
        ['category' => 'labOrderStatuses', 'label' => 'Delivered', 'value' => 'Delivered', 'sort_order' => 3],
        // ─── lips ── (8)
        ['category' => 'lips', 'label' => 'Normal', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'lips', 'label' => 'Dry / Chapped', 'value' => 'Dry', 'sort_order' => 1],
        ['category' => 'lips', 'label' => 'Ulceration', 'value' => 'Ulceration', 'sort_order' => 2],
        ['category' => 'lips', 'label' => 'Angular Cheilitis', 'value' => 'AngularCheilitis', 'sort_order' => 3],
        ['category' => 'lips', 'label' => 'Herpes Labialis', 'value' => 'Herpes', 'sort_order' => 4],
        ['category' => 'lips', 'label' => 'Cleft Lip', 'value' => 'CleftLip', 'sort_order' => 5],
        ['category' => 'lips', 'label' => 'Swelling', 'value' => 'Swelling', 'sort_order' => 6],
        ['category' => 'lips', 'label' => 'Pigmentation', 'value' => 'Pigmentation', 'sort_order' => 7],
        // ─── buccalMucosa ── (8)
        ['category' => 'buccalMucosa', 'label' => 'Normal', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'buccalMucosa', 'label' => 'Hyperkeratosis', 'value' => 'Hyperkeratosis', 'sort_order' => 1],
        ['category' => 'buccalMucosa', 'label' => 'Leukoplakia', 'value' => 'Leukoplakia', 'sort_order' => 2],
        ['category' => 'buccalMucosa', 'label' => 'Erythroplakia', 'value' => 'Erythroplakia', 'sort_order' => 3],
        ['category' => 'buccalMucosa', 'label' => 'Lichen Planus', 'value' => 'LichenPlanus', 'sort_order' => 4],
        ['category' => 'buccalMucosa', 'label' => 'Ulceration', 'value' => 'Ulceration', 'sort_order' => 5],
        ['category' => 'buccalMucosa', 'label' => 'Fibroma', 'value' => 'Fibroma', 'sort_order' => 6],
        ['category' => 'buccalMucosa', 'label' => 'Linea Alba', 'value' => 'LineaAlba', 'sort_order' => 7],
        // ─── tongue ── (8)
        ['category' => 'tongue', 'label' => 'Normal', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'tongue', 'label' => 'Coated / Furred', 'value' => 'Coated', 'sort_order' => 1],
        ['category' => 'tongue', 'label' => 'Geographic Tongue', 'value' => 'Geographic', 'sort_order' => 2],
        ['category' => 'tongue', 'label' => 'Fissured Tongue', 'value' => 'Fissured', 'sort_order' => 3],
        ['category' => 'tongue', 'label' => 'Atrophic / Smooth', 'value' => 'Atrophic', 'sort_order' => 4],
        ['category' => 'tongue', 'label' => 'Ulceration', 'value' => 'Ulceration', 'sort_order' => 5],
        ['category' => 'tongue', 'label' => 'Leukoplakia', 'value' => 'Leukoplakia', 'sort_order' => 6],
        ['category' => 'tongue', 'label' => 'Macroglossia', 'value' => 'Macroglossia', 'sort_order' => 7],
        // ─── floorOfMouth ── (5)
        ['category' => 'floorOfMouth', 'label' => 'Normal', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'floorOfMouth', 'label' => 'Swelling', 'value' => 'Swelling', 'sort_order' => 1],
        ['category' => 'floorOfMouth', 'label' => 'Ranula', 'value' => 'Ranula', 'sort_order' => 2],
        ['category' => 'floorOfMouth', 'label' => 'Leukoplakia', 'value' => 'Leukoplakia', 'sort_order' => 3],
        ['category' => 'floorOfMouth', 'label' => 'Calculus', 'value' => 'Calculus', 'sort_order' => 4],
        // ─── palate ── (6)
        ['category' => 'palate', 'label' => 'Normal', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'palate', 'label' => 'High Arched', 'value' => 'HighArched', 'sort_order' => 1],
        ['category' => 'palate', 'label' => 'Cleft Palate', 'value' => 'CleftPalate', 'sort_order' => 2],
        ['category' => 'palate', 'label' => 'Erythema', 'value' => 'Erythema', 'sort_order' => 3],
        ['category' => 'palate', 'label' => 'Petechiae', 'value' => 'Petechiae', 'sort_order' => 4],
        ['category' => 'palate', 'label' => 'Toras Palatinus', 'value' => 'TorasPalatinus', 'sort_order' => 5],
        // ─── oropharynx ── (5)
        ['category' => 'oropharynx', 'label' => 'Normal', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'oropharynx', 'label' => 'Erythema', 'value' => 'Erythema', 'sort_order' => 1],
        ['category' => 'oropharynx', 'label' => 'Tonsillar Enlargement', 'value' => 'TonsillarEnlargement', 'sort_order' => 2],
        ['category' => 'oropharynx', 'label' => 'Exudate', 'value' => 'Exudate', 'sort_order' => 3],
        ['category' => 'oropharynx', 'label' => 'Ulceration', 'value' => 'Ulceration', 'sort_order' => 4],
        // ─── gingiva ── (8)
        ['category' => 'gingiva', 'label' => 'Normal / Healthy', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'gingiva', 'label' => 'Gingivitis', 'value' => 'Gingivitis', 'sort_order' => 1],
        ['category' => 'gingiva', 'label' => 'Periodontitis', 'value' => 'Periodontitis', 'sort_order' => 2],
        ['category' => 'gingiva', 'label' => 'Hyperplasia', 'value' => 'Hyperplasia', 'sort_order' => 3],
        ['category' => 'gingiva', 'label' => 'Recession', 'value' => 'Recession', 'sort_order' => 4],
        ['category' => 'gingiva', 'label' => 'Swelling', 'value' => 'Swelling', 'sort_order' => 5],
        ['category' => 'gingiva', 'label' => 'Bleeding on Probing', 'value' => 'BOP', 'sort_order' => 6],
        ['category' => 'gingiva', 'label' => 'Fistula / Sinus Tract', 'value' => 'Fistula', 'sort_order' => 7],
        // ─── salivaryGlands ── (5)
        ['category' => 'salivaryGlands', 'label' => 'Normal', 'value' => 'Normal', 'sort_order' => 0],
        ['category' => 'salivaryGlands', 'label' => 'Enlarged', 'value' => 'Enlarged', 'sort_order' => 1],
        ['category' => 'salivaryGlands', 'label' => 'Tender', 'value' => 'Tender', 'sort_order' => 2],
        ['category' => 'salivaryGlands', 'label' => 'Reduced Saliva Flow', 'value' => 'ReducedFlow', 'sort_order' => 3],
        ['category' => 'salivaryGlands', 'label' => 'Sialolith (Calculus)', 'value' => 'Sialolith', 'sort_order' => 4],
        // ─── toothStatus ── (6)
        ['category' => 'toothStatus', 'label' => 'Present', 'value' => 'Present', 'sort_order' => 0],
        ['category' => 'toothStatus', 'label' => 'Missing', 'value' => 'Missing', 'sort_order' => 1],
        ['category' => 'toothStatus', 'label' => 'Impacted', 'value' => 'Impacted', 'sort_order' => 2],
        ['category' => 'toothStatus', 'label' => 'Fractured', 'value' => 'Fractured', 'sort_order' => 3],
        ['category' => 'toothStatus', 'label' => 'Root Stump', 'value' => 'RootStump', 'sort_order' => 4],
        ['category' => 'toothStatus', 'label' => 'Partially Erupted', 'value' => 'PartiallyErupted', 'sort_order' => 5],
        // ─── cariesStatus ── (6)
        ['category' => 'cariesStatus', 'label' => 'Sound (Healthy)', 'value' => 'Sound', 'sort_order' => 0],
        ['category' => 'cariesStatus', 'label' => 'Decayed / Carious', 'value' => 'Decayed', 'sort_order' => 1],
        ['category' => 'cariesStatus', 'label' => 'Filled (Restored)', 'value' => 'Filled', 'sort_order' => 2],
        ['category' => 'cariesStatus', 'label' => 'Filled with Decay', 'value' => 'FilledDecay', 'sort_order' => 3],
        ['category' => 'cariesStatus', 'label' => 'Missing due to Caries', 'value' => 'MissingCaries', 'sort_order' => 4],
        ['category' => 'cariesStatus', 'label' => 'Fissure Sealant', 'value' => 'Sealant', 'sort_order' => 5],
        // ─── mobility ── (4)
        ['category' => 'mobility', 'label' => 'None (Grade 0)', 'value' => '0', 'sort_order' => 0],
        ['category' => 'mobility', 'label' => 'Grade I (1mm)', 'value' => '1', 'sort_order' => 1],
        ['category' => 'mobility', 'label' => 'Grade II (2mm)', 'value' => '2', 'sort_order' => 2],
        ['category' => 'mobility', 'label' => 'Grade III (3mm+)', 'value' => '3', 'sort_order' => 3],
        // ─── furcationInvolvement ── (4)
        ['category' => 'furcationInvolvement', 'label' => 'None', 'value' => 'None', 'sort_order' => 0],
        ['category' => 'furcationInvolvement', 'label' => 'Grade I (Early)', 'value' => 'I', 'sort_order' => 1],
        ['category' => 'furcationInvolvement', 'label' => 'Grade II (Definite)', 'value' => 'II', 'sort_order' => 2],
        ['category' => 'furcationInvolvement', 'label' => 'Grade III (Through & Through)', 'value' => 'III', 'sort_order' => 3],
        // ─── surgeryTypes ── (12)
        ['category' => 'surgeryTypes', 'label' => 'Tooth Extraction', 'value' => 'Extraction', 'sort_order' => 0],
        ['category' => 'surgeryTypes', 'label' => 'Surgical Extraction', 'value' => 'SurgicalExtraction', 'sort_order' => 1],
        ['category' => 'surgeryTypes', 'label' => 'Root Canal Treatment', 'value' => 'RCT', 'sort_order' => 2],
        ['category' => 'surgeryTypes', 'label' => 'Apicectomy', 'value' => 'Apicectomy', 'sort_order' => 3],
        ['category' => 'surgeryTypes', 'label' => 'Dental Implant Placement', 'value' => 'ImplantPlacement', 'sort_order' => 4],
        ['category' => 'surgeryTypes', 'label' => 'Bone Grafting', 'value' => 'BoneGrafting', 'sort_order' => 5],
        ['category' => 'surgeryTypes', 'label' => 'Sinus Lift', 'value' => 'SinusLift', 'sort_order' => 6],
        ['category' => 'surgeryTypes', 'label' => 'Gingivectomy', 'value' => 'Gingivectomy', 'sort_order' => 7],
        ['category' => 'surgeryTypes', 'label' => 'Flap Surgery', 'value' => 'FlapSurgery', 'sort_order' => 8],
        ['category' => 'surgeryTypes', 'label' => 'Cyst Enucleation', 'value' => 'CystEnucleation', 'sort_order' => 9],
        ['category' => 'surgeryTypes', 'label' => 'Biopsy', 'value' => 'Biopsy', 'sort_order' => 10],
        ['category' => 'surgeryTypes', 'label' => 'Orthognathic Surgery', 'value' => 'Orthognathic', 'sort_order' => 11],
        // ─── anaesthesiaTypesSurgery ── (5)
        ['category' => 'anaesthesiaTypesSurgery', 'label' => 'Local Anaesthesia', 'value' => 'Local', 'sort_order' => 0],
        ['category' => 'anaesthesiaTypesSurgery', 'label' => 'Regional Block (Inferior Alveolar)', 'value' => 'IANBlock', 'sort_order' => 1],
        ['category' => 'anaesthesiaTypesSurgery', 'label' => 'Greater Palatine Block', 'value' => 'PalatineBlock', 'sort_order' => 2],
        ['category' => 'anaesthesiaTypesSurgery', 'label' => 'General Anaesthesia', 'value' => 'General', 'sort_order' => 3],
        ['category' => 'anaesthesiaTypesSurgery', 'label' => 'IV Sedation', 'value' => 'IVSedation', 'sort_order' => 4],
        // ─── toothOptions ── (5)
        ['category' => 'toothOptions', 'label' => 'Upper Right (18-11)', 'value' => 'UpperRight', 'sort_order' => 0],
        ['category' => 'toothOptions', 'label' => 'Upper Left (21-28)', 'value' => 'UpperLeft', 'sort_order' => 1],
        ['category' => 'toothOptions', 'label' => 'Lower Left (31-38)', 'value' => 'LowerLeft', 'sort_order' => 2],
        ['category' => 'toothOptions', 'label' => 'Lower Right (41-48)', 'value' => 'LowerRight', 'sort_order' => 3],
        ['category' => 'toothOptions', 'label' => 'All Quadrants', 'value' => 'All', 'sort_order' => 4],
        // ─── tobaccoUse ── (5)
        ['category' => 'tobaccoUse', 'label' => 'None', 'value' => 'None', 'sort_order' => 0],
        ['category' => 'tobaccoUse', 'label' => 'Current Smoker', 'value' => 'Current', 'sort_order' => 1],
        ['category' => 'tobaccoUse', 'label' => 'Former Smoker', 'value' => 'Former', 'sort_order' => 2],
        ['category' => 'tobaccoUse', 'label' => 'Smokeless Tobacco', 'value' => 'Smokeless', 'sort_order' => 3],
        ['category' => 'tobaccoUse', 'label' => 'Passive Smoker', 'value' => 'Passive', 'sort_order' => 4],
        // ─── alcoholUse ── (4)
        ['category' => 'alcoholUse', 'label' => 'None', 'value' => 'None', 'sort_order' => 0],
        ['category' => 'alcoholUse', 'label' => 'Social', 'value' => 'Social', 'sort_order' => 1],
        ['category' => 'alcoholUse', 'label' => 'Moderate', 'value' => 'Moderate', 'sort_order' => 2],
        ['category' => 'alcoholUse', 'label' => 'Heavy', 'value' => 'Heavy', 'sort_order' => 3],
        // ─── oralHygieneStatus ── (4)
        ['category' => 'oralHygieneStatus', 'label' => 'Good', 'value' => 'Good', 'sort_order' => 0],
        ['category' => 'oralHygieneStatus', 'label' => 'Fair', 'value' => 'Fair', 'sort_order' => 1],
        ['category' => 'oralHygieneStatus', 'label' => 'Poor', 'value' => 'Poor', 'sort_order' => 2],
        ['category' => 'oralHygieneStatus', 'label' => 'Very Poor', 'value' => 'VeryPoor', 'sort_order' => 3],
        // ─── patientToReturn ── (2)
        ['category' => 'patientToReturn', 'label' => 'No', 'value' => 'No', 'sort_order' => 0],
        ['category' => 'patientToReturn', 'label' => 'Yes', 'value' => 'Yes', 'sort_order' => 1],
        // ─── labOrderTypesDialog ── (15)
        ['category' => 'labOrderTypesDialog', 'label' => 'Crown', 'value' => 'Crown', 'sort_order' => 0],
        ['category' => 'labOrderTypesDialog', 'label' => 'Bridge', 'value' => 'Bridge', 'sort_order' => 1],
        ['category' => 'labOrderTypesDialog', 'label' => 'Denture', 'value' => 'Denture', 'sort_order' => 2],
        ['category' => 'labOrderTypesDialog', 'label' => 'Partial Denture', 'value' => 'Partial Denture', 'sort_order' => 3],
        ['category' => 'labOrderTypesDialog', 'label' => 'Full Denture', 'value' => 'Full Denture', 'sort_order' => 4],
        ['category' => 'labOrderTypesDialog', 'label' => 'Dental Implant', 'value' => 'Implant', 'sort_order' => 5],
        ['category' => 'labOrderTypesDialog', 'label' => 'Veneer', 'value' => 'Veneer', 'sort_order' => 6],
        ['category' => 'labOrderTypesDialog', 'label' => 'Inlay/Onlay', 'value' => 'Inlay/Onlay', 'sort_order' => 7],
        ['category' => 'labOrderTypesDialog', 'label' => 'Night Guard', 'value' => 'Night Guard', 'sort_order' => 8],
        ['category' => 'labOrderTypesDialog', 'label' => 'Mouth Guard', 'value' => 'Mouth Guard', 'sort_order' => 9],
        ['category' => 'labOrderTypesDialog', 'label' => 'Space Maintainer', 'value' => 'Space Maintainer', 'sort_order' => 10],
        ['category' => 'labOrderTypesDialog', 'label' => 'Orthodontic Appliance', 'value' => 'Orthodontic', 'sort_order' => 11],
        ['category' => 'labOrderTypesDialog', 'label' => 'Model/Cast (Study)', 'value' => 'Model', 'sort_order' => 12],
        ['category' => 'labOrderTypesDialog', 'label' => 'Wax-up', 'value' => 'WaxUp', 'sort_order' => 13],
        ['category' => 'labOrderTypesDialog', 'label' => 'Other', 'value' => 'Other', 'sort_order' => 14],
        // ─── nhifClaimStatuses ── (5)
        ['category' => 'nhifClaimStatuses', 'label' => 'Draft', 'value' => 'draft', 'sort_order' => 0],
        ['category' => 'nhifClaimStatuses', 'label' => 'Submitted', 'value' => 'submitted', 'sort_order' => 1],
        ['category' => 'nhifClaimStatuses', 'label' => 'Approved', 'value' => 'approved', 'sort_order' => 2],
        ['category' => 'nhifClaimStatuses', 'label' => 'Rejected', 'value' => 'rejected', 'sort_order' => 3],
        ['category' => 'nhifClaimStatuses', 'label' => 'Paid', 'value' => 'paid', 'sort_order' => 4],
        // ─── hmisCancerTypes ── (10)
        ['category' => 'hmisCancerTypes', 'label' => 'Oral Cavity Cancer', 'value' => 'OralCavity', 'sort_order' => 0],
        ['category' => 'hmisCancerTypes', 'label' => 'Lip Cancer', 'value' => 'Lip', 'sort_order' => 1],
        ['category' => 'hmisCancerTypes', 'label' => 'Tongue Cancer', 'value' => 'Tongue', 'sort_order' => 2],
        ['category' => 'hmisCancerTypes', 'label' => 'Salivary Gland Cancer', 'value' => 'SalivaryGland', 'sort_order' => 3],
        ['category' => 'hmisCancerTypes', 'label' => 'Oropharyngeal Cancer', 'value' => 'Oropharynx', 'sort_order' => 4],
        ['category' => 'hmisCancerTypes', 'label' => 'Nasopharyngeal Cancer', 'value' => 'Nasopharynx', 'sort_order' => 5],
        ['category' => 'hmisCancerTypes', 'label' => 'Laryngeal Cancer', 'value' => 'Larynx', 'sort_order' => 6],
        ['category' => 'hmisCancerTypes', 'label' => 'Thyroid Cancer', 'value' => 'Thyroid', 'sort_order' => 7],
        ['category' => 'hmisCancerTypes', 'label' => 'Skin Cancer (Head & Neck)', 'value' => 'SkinHeadNeck', 'sort_order' => 8],
        ['category' => 'hmisCancerTypes', 'label' => 'Other (Specify)', 'value' => 'Other', 'sort_order' => 9],
        // ─── appointmentStatus ── (7)
        ['category' => 'appointmentStatus', 'label' => 'All', 'value' => '', 'sort_order' => 0],
        ['category' => 'appointmentStatus', 'label' => 'Scheduled', 'value' => 'Scheduled', 'sort_order' => 1],
        ['category' => 'appointmentStatus', 'label' => 'Confirmed', 'value' => 'Confirmed', 'sort_order' => 2],
        ['category' => 'appointmentStatus', 'label' => 'In Progress', 'value' => 'In Progress', 'sort_order' => 3],
        ['category' => 'appointmentStatus', 'label' => 'Completed', 'value' => 'Completed', 'sort_order' => 4],
        ['category' => 'appointmentStatus', 'label' => 'Cancelled', 'value' => 'Cancelled', 'sort_order' => 5],
        ['category' => 'appointmentStatus', 'label' => 'No Show', 'value' => 'No Show', 'sort_order' => 6],
        // ─── appointmentType ── (6)
        ['category' => 'appointmentType', 'label' => 'Check-up', 'value' => 'Check-up', 'sort_order' => 0],
        ['category' => 'appointmentType', 'label' => 'Treatment', 'value' => 'Treatment', 'sort_order' => 1],
        ['category' => 'appointmentType', 'label' => 'Follow-up', 'value' => 'Follow-up', 'sort_order' => 2],
        ['category' => 'appointmentType', 'label' => 'Emergency', 'value' => 'Emergency', 'sort_order' => 3],
        ['category' => 'appointmentType', 'label' => 'Braces Works', 'value' => 'Braces Works', 'sort_order' => 4],
        ['category' => 'appointmentType', 'label' => 'Ceramics Works', 'value' => 'Ceramics Works', 'sort_order' => 5],
        // ─── dentalExamStatus ── (2)
        ['category' => 'dentalExamStatus', 'label' => 'Pending', 'value' => 'Pending', 'sort_order' => 0],
        ['category' => 'dentalExamStatus', 'label' => 'Consulted', 'value' => 'Consulted', 'sort_order' => 1],
        // ─── labOrderStatusFilter ── (5)
        ['category' => 'labOrderStatusFilter', 'label' => 'All', 'value' => '', 'sort_order' => 0],
        ['category' => 'labOrderStatusFilter', 'label' => 'Ordered', 'value' => 'Ordered', 'sort_order' => 1],
        ['category' => 'labOrderStatusFilter', 'label' => 'In Progress', 'value' => 'In Progress', 'sort_order' => 2],
        ['category' => 'labOrderStatusFilter', 'label' => 'Ready', 'value' => 'Ready', 'sort_order' => 3],
        ['category' => 'labOrderStatusFilter', 'label' => 'Delivered', 'value' => 'Delivered', 'sort_order' => 4],
        // ─── labReportStatus ── (4)
        ['category' => 'labReportStatus', 'label' => 'Ordered', 'value' => 'Ordered', 'sort_order' => 0],
        ['category' => 'labReportStatus', 'label' => 'In Progress', 'value' => 'In Progress', 'sort_order' => 1],
        ['category' => 'labReportStatus', 'label' => 'Ready', 'value' => 'Ready', 'sort_order' => 2],
        ['category' => 'labReportStatus', 'label' => 'Delivered', 'value' => 'Delivered', 'sort_order' => 3],
        // ─── stockMovementType ── (3)
        ['category' => 'stockMovementType', 'label' => 'Stock In', 'value' => 'in', 'sort_order' => 0],
        ['category' => 'stockMovementType', 'label' => 'Stock Out', 'value' => 'out', 'sort_order' => 1],
        ['category' => 'stockMovementType', 'label' => 'Adjustment', 'value' => 'adjustment', 'sort_order' => 2],
        // ─── stockLevel ── (3)
        ['category' => 'stockLevel', 'label' => 'In Stock', 'value' => 'In Stock', 'sort_order' => 0],
        ['category' => 'stockLevel', 'label' => 'Low Stock', 'value' => 'Low Stock', 'sort_order' => 1],
        ['category' => 'stockLevel', 'label' => 'Out of Stock', 'value' => 'Out of Stock', 'sort_order' => 2],
        // ─── itemCategory ── (8)
        ['category' => 'itemCategory', 'label' => 'Medicine', 'value' => 'Medicine', 'sort_order' => 0],
        ['category' => 'itemCategory', 'label' => 'Pharmaceutical', 'value' => 'Pharmaceutical', 'sort_order' => 1],
        ['category' => 'itemCategory', 'label' => 'Dental Materials', 'value' => 'Dental Materials', 'sort_order' => 2],
        ['category' => 'itemCategory', 'label' => 'Dental Prosthetics', 'value' => 'Dental Prosthetics', 'sort_order' => 3],
        ['category' => 'itemCategory', 'label' => 'Equipment', 'value' => 'Equipment', 'sort_order' => 4],
        ['category' => 'itemCategory', 'label' => 'Materials', 'value' => 'Materials', 'sort_order' => 5],
        ['category' => 'itemCategory', 'label' => 'Others', 'value' => 'Others', 'sort_order' => 6],
        ['category' => 'itemCategory', 'label' => 'Service', 'value' => 'Service', 'sort_order' => 7],
        // ─── recordStatus ── (2)
        ['category' => 'recordStatus', 'label' => 'Active', 'value' => 'Active', 'sort_order' => 0],
        ['category' => 'recordStatus', 'label' => 'Inactive', 'value' => 'Inactive', 'sort_order' => 1],
        // ─── communicationChannel ── (3)
        ['category' => 'communicationChannel', 'label' => 'Phone', 'value' => 'Phone', 'sort_order' => 0],
        ['category' => 'communicationChannel', 'label' => 'Chat', 'value' => 'Chat', 'sort_order' => 1],
        ['category' => 'communicationChannel', 'label' => 'Email', 'value' => 'Email', 'sort_order' => 2],
        // ─── communicationDirection ── (2)
        ['category' => 'communicationDirection', 'label' => 'Incoming', 'value' => 'Incoming', 'sort_order' => 0],
        ['category' => 'communicationDirection', 'label' => 'Outgoing', 'value' => 'Outgoing', 'sort_order' => 1],
        // ─── activityStatus ── (3)
        ['category' => 'activityStatus', 'label' => 'Pending', 'value' => 'Pending', 'sort_order' => 0],
        ['category' => 'activityStatus', 'label' => 'Cancelled', 'value' => 'Cancelled', 'sort_order' => 1],
        ['category' => 'activityStatus', 'label' => 'Completed', 'value' => 'Completed', 'sort_order' => 2],
        // ─── ideaStatus ── (3)
        ['category' => 'ideaStatus', 'label' => 'Pending', 'value' => 'Pending', 'sort_order' => 0],
        ['category' => 'ideaStatus', 'label' => 'Cancelled', 'value' => 'Cancelled', 'sort_order' => 1],
        ['category' => 'ideaStatus', 'label' => 'Implemented', 'value' => 'Implemented', 'sort_order' => 2],
        // ─── marketingStrategyStatus ── (3)
        ['category' => 'marketingStrategyStatus', 'label' => 'Open', 'value' => 'Open', 'sort_order' => 0],
        ['category' => 'marketingStrategyStatus', 'label' => 'Cancelled', 'value' => 'Cancelled', 'sort_order' => 1],
        ['category' => 'marketingStrategyStatus', 'label' => 'Closed', 'value' => 'Closed', 'sort_order' => 2],
        // ─── expenseStatus ── (2)
        ['category' => 'expenseStatus', 'label' => 'Pending', 'value' => 'Pending', 'sort_order' => 0],
        ['category' => 'expenseStatus', 'label' => 'Cleared', 'value' => 'Cleared', 'sort_order' => 1],
        // ─── paymentModeType ── (2)
        ['category' => 'paymentModeType', 'label' => 'Cash', 'value' => 'Cash', 'sort_order' => 0],
        ['category' => 'paymentModeType', 'label' => 'Credit', 'value' => 'Credit', 'sort_order' => 1],
        // ─── gender ── (2)
        ['category' => 'gender', 'label' => 'Male', 'value' => 'Male', 'sort_order' => 0],
        ['category' => 'gender', 'label' => 'Female', 'value' => 'Female', 'sort_order' => 1],
        // ─── reportPeriod ── (4)
        ['category' => 'reportPeriod', 'label' => 'Daily', 'value' => 'daily', 'sort_order' => 0],
        ['category' => 'reportPeriod', 'label' => 'Weekly', 'value' => 'weekly', 'sort_order' => 1],
        ['category' => 'reportPeriod', 'label' => 'Monthly', 'value' => 'monthly', 'sort_order' => 2],
        ['category' => 'reportPeriod', 'label' => 'Yearly', 'value' => 'yearly', 'sort_order' => 3],
        // ─── returnPeriod ── (3)
        ['category' => 'returnPeriod', 'label' => 'Daily', 'value' => 'Daily', 'sort_order' => 0],
        ['category' => 'returnPeriod', 'label' => 'Weekly', 'value' => 'Weekly', 'sort_order' => 1],
        ['category' => 'returnPeriod', 'label' => 'Monthly', 'value' => 'Monthly', 'sort_order' => 2],
        // ─── filterPeriod ── (3)
        ['category' => 'filterPeriod', 'label' => 'Daily', 'value' => 'daily', 'sort_order' => 0],
        ['category' => 'filterPeriod', 'label' => 'Weekly', 'value' => 'weekly', 'sort_order' => 1],
        ['category' => 'filterPeriod', 'label' => 'Monthly', 'value' => 'monthly', 'sort_order' => 2],
        // ─── yesNo ── (2)
        ['category' => 'yesNo', 'label' => 'Yes', 'value' => 'Yes', 'sort_order' => 0],
        ['category' => 'yesNo', 'label' => 'No', 'value' => 'No', 'sort_order' => 1],
        // ─── userOccupation ── (2)
        ['category' => 'userOccupation', 'label' => 'Doctor', 'value' => 'Doctor', 'sort_order' => 0],
        ['category' => 'userOccupation', 'label' => 'Other', 'value' => 'Other', 'sort_order' => 1],
        // ─── waitingTimeStatus ── (4)
        ['category' => 'waitingTimeStatus', 'label' => 'All Statuses', 'value' => 'all', 'sort_order' => 0],
        ['category' => 'waitingTimeStatus', 'label' => 'Waiting', 'value' => 'waiting', 'sort_order' => 1],
        ['category' => 'waitingTimeStatus', 'label' => 'In Treatment', 'value' => 'in_treatment', 'sort_order' => 2],
        ['category' => 'waitingTimeStatus', 'label' => 'Completed', 'value' => 'completed', 'sort_order' => 3],
        // ─── prescriptionRoute ── (9)
        ['category' => 'prescriptionRoute', 'label' => 'Oral', 'value' => 'Oral', 'sort_order' => 0],
        ['category' => 'prescriptionRoute', 'label' => 'Topical', 'value' => 'Topical', 'sort_order' => 1],
        ['category' => 'prescriptionRoute', 'label' => 'IV', 'value' => 'IV', 'sort_order' => 2],
        ['category' => 'prescriptionRoute', 'label' => 'IM', 'value' => 'IM', 'sort_order' => 3],
        ['category' => 'prescriptionRoute', 'label' => 'Sublingual', 'value' => 'Sublingual', 'sort_order' => 4],
        ['category' => 'prescriptionRoute', 'label' => 'Inhalation', 'value' => 'Inhalation', 'sort_order' => 5],
        ['category' => 'prescriptionRoute', 'label' => 'Subcutaneous', 'value' => 'Subcutaneous', 'sort_order' => 6],
        ['category' => 'prescriptionRoute', 'label' => 'Intradermal', 'value' => 'Intradermal', 'sort_order' => 7],
        ['category' => 'prescriptionRoute', 'label' => 'Intrathecal', 'value' => 'Intrathecal', 'sort_order' => 8],
        ];

        foreach ($options as $option) {
            Option::updateOrCreate(
                ['category' => $option['category'], 'value' => $option['value']],
                ['label' => $option['label'], 'sort_order' => $option['sort_order'], 'status' => 'Active']
            );
        }
    }
}
