export const DENTAL_TREATMENT_OPTIONS = {
  toothNumbers: [
    { label: "Tooth 11 - Upper Right Central Incisor", value: "11" },
    { label: "Tooth 12 - Upper Right Lateral Incisor", value: "12" },
    { label: "Tooth 13 - Upper Right Canine", value: "13" },
    { label: "Tooth 14 - Upper Right 1st Premolar", value: "14" },
    { label: "Tooth 15 - Upper Right 2nd Premolar", value: "15" },
    { label: "Tooth 16 - Upper Right 1st Molar", value: "16" },
    { label: "Tooth 17 - Upper Right 2nd Molar", value: "17" },
    { label: "Tooth 18 - Upper Right 3rd Molar", value: "18" },
    { label: "Tooth 21 - Upper Left Central Incisor", value: "21" },
    { label: "Tooth 22 - Upper Left Lateral Incisor", value: "22" },
    { label: "Tooth 23 - Upper Left Canine", value: "23" },
    { label: "Tooth 24 - Upper Left 1st Premolar", value: "24" },
    { label: "Tooth 25 - Upper Left 2nd Premolar", value: "25" },
    { label: "Tooth 26 - Upper Left 1st Molar", value: "26" },
    { label: "Tooth 27 - Upper Left 2nd Molar", value: "27" },
    { label: "Tooth 28 - Upper Left 3rd Molar", value: "28" },
    { label: "Tooth 31 - Lower Left Central Incisor", value: "31" },
    { label: "Tooth 32 - Lower Left Lateral Incisor", value: "32" },
    { label: "Tooth 33 - Lower Left Canine", value: "33" },
    { label: "Tooth 34 - Lower Left 1st Premolar", value: "34" },
    { label: "Tooth 35 - Lower Left 2nd Premolar", value: "35" },
    { label: "Tooth 36 - Lower Left 1st Molar", value: "36" },
    { label: "Tooth 37 - Lower Left 2nd Molar", value: "37" },
    { label: "Tooth 38 - Lower Left 3rd Molar", value: "38" },
    { label: "Tooth 41 - Lower Right Central Incisor", value: "41" },
    { label: "Tooth 42 - Lower Right Lateral Incisor", value: "42" },
    { label: "Tooth 43 - Lower Right Canine", value: "43" },
    { label: "Tooth 44 - Lower Right 1st Premolar", value: "44" },
    { label: "Tooth 45 - Lower Right 2nd Premolar", value: "45" },
    { label: "Tooth 46 - Lower Right 1st Molar", value: "46" },
    { label: "Tooth 47 - Lower Right 2nd Molar", value: "47" },
    { label: "Tooth 48 - Lower Right 3rd Molar", value: "48" },
  ],
  toothSurfaces: [
    { label: "Occlusal (O)", value: "O" },
    { label: "Mesial (M)", value: "M" },
    { label: "Distal (D)", value: "D" },
    { label: "Buccal (B)", value: "B" },
    { label: "Lingual (L)", value: "L" },
    { label: "Incisal (I)", value: "I" },
    { label: "MOD (Mesial-Occlusal-Distal)", value: "MOD" },
    { label: "MO (Mesial-Occlusal)", value: "MO" },
    { label: "OD (Occlusal-Distal)", value: "OD" },
    { label: "BL (Buccal-Lingual)", value: "BL" },
  ],
  treatmentTypes: [
    { label: "Restoration / Filling", value: "Restoration" },
    { label: "Extraction", value: "Extraction" },
    { label: "Root Canal Treatment", value: "RCT" },
    { label: "Scaling & Polishing", value: "Scaling" },
    { label: "Crown", value: "Crown" },
    { label: "Bridge", value: "Bridge" },
    { label: "Denture", value: "Denture" },
    { label: "Dental Implant", value: "Implant" },
    { label: "Orthodontic Treatment", value: "Orthodontic" },
    { label: "Periodontal Treatment", value: "Periodontal" },
    { label: "Fluoride Application", value: "Fluoride" },
    { label: "Fissure Sealant", value: "Sealant" },
    { label: "Bleaching / Whitening", value: "Bleaching" },
    { label: "Veneer", value: "Veneer" },
    { label: "Gum Surgery", value: "GumSurgery" },
    { label: "Biopsy", value: "Biopsy" },
  ],
  oralExaminationFindings: [
    { label: "Normal oral mucosa", value: "Normal" },
    { label: "Gingivitis", value: "Gingivitis" },
    { label: "Periodontitis", value: "Periodontitis" },
    { label: "Dental caries", value: "Caries" },
    { label: "Pulpitis", value: "Pulpitis" },
    { label: "Periapical abscess", value: "Abscess" },
    { label: "Oral ulcer", value: "Ulcer" },
    { label: "Leukoplakia", value: "Leukoplakia" },
    { label: "Erythroplakia", value: "Erythroplakia" },
    { label: "Oral candidiasis", value: "Candidiasis" },
    { label: "Oral lichen planus", value: "LichenPlanus" },
    { label: "TMJ disorder", value: "TMJ" },
    { label: "Malocclusion", value: "Malocclusion" },
    { label: "Impacted tooth", value: "Impacted" },
    { label: "Missing tooth", value: "Missing" },
    { label: "Fractured tooth", value: "Fractured" },
    { label: "Worn dentition / Attrition", value: "Attrition" },
  ],
  periodontalCharting: [
    { label: "Probing Depth 1-3mm (Healthy)", value: "1-3" },
    { label: "Probing Depth 4-5mm (Mild)", value: "4-5" },
    { label: "Probing Depth 6-7mm (Moderate)", value: "6-7" },
    { label: "Probing Depth 8mm+ (Severe)", value: "8+" },
    { label: "Bleeding on Probing (BOP)", value: "BOP" },
    { label: "Gingival Recession", value: "Recession" },
    { label: "Furcation Involvement", value: "Furcation" },
    { label: "Mobility Grade I", value: "Mobility1" },
    { label: "Mobility Grade II", value: "Mobility2" },
    { label: "Mobility Grade III", value: "Mobility3" },
  ],
  treatmentPhases: [
    { label: "Phase 1 - Initial / Urgent Care", value: "Phase 1" },
    { label: "Phase 2 - Restorative / Rehabilitative", value: "Phase 2" },
    { label: "Phase 3 - Cosmetic / Final Restoration", value: "Phase 3" },
  ],
  anaesthesiaTypes: [
    { label: "Local Anaesthesia", value: "Local" },
    { label: "Regional Block", value: "Regional" },
    { label: "General Anaesthesia", value: "General" },
    { label: "Sedation (IV)", value: "SedationIV" },
    { label: "Inhalation Sedation", value: "Inhalation" },
  ],
  radiographTypes: [
    { label: "Intraoral Periapical (IOPA)", value: "IOPA" },
    { label: "Bitewing", value: "Bitewing" },
    { label: "Occlusal", value: "Occlusal" },
    { label: "Panoramic (OPG)", value: "OPG" },
    { label: "Cephalometric", value: "Cephalometric" },
    { label: "CBCT", value: "CBCT" },
  ],
  labOrderTypes: [
    { label: "Crown (PFM)", value: "CrownPFM" },
    { label: "Crown (Full Cast)", value: "CrownFullCast" },
    { label: "Crown (Zirconia)", value: "CrownZirconia" },
    { label: "Crown (E-max)", value: "CrownEmax" },
    { label: "Bridge", value: "Bridge" },
    { label: "Partial Denture (Acrylic)", value: "PartialAcrylic" },
    { label: "Partial Denture (Cast Partial)", value: "PartialCast" },
    { label: "Complete Denture", value: "CompleteDenture" },
    { label: "Veneer", value: "Veneer" },
    { label: "Inlay / Onlay", value: "InlayOnlay" },
    { label: "Orthodontic Appliance", value: "OrthoAppliance" },
    { label: "Night Guard", value: "NightGuard" },
    { label: "Surgical Guide", value: "SurgicalGuide" },
  ],
  labMaterials: [
    { label: "PFM (Porcelain Fused to Metal)", value: "PFM" },
    { label: "Zirconia", value: "Zirconia" },
    { label: "E-max (Lithium Disilicate)", value: "E-max" },
    { label: "Composite Resin", value: "Composite" },
    { label: "Acrylic Resin", value: "Acrylic" },
    { label: "Metal Alloy (Cobalt Chrome)", value: "CobaltChrome" },
    { label: "Metal Alloy (Nickel Chrome)", value: "NickelChrome" },
    { label: "Titanium", value: "Titanium" },
    { label: "Wax", value: "Wax" },
    { label: "Gypsum / Stone", value: "Gypsum" },
    { label: "Silicone Impression", value: "Silicone" },
    { label: "Other", value: "Other" },
  ],
  labShadeGuide: [
    { label: "A1", value: "A1" },
    { label: "A2", value: "A2" },
    { label: "A3", value: "A3" },
    { label: "A3.5", value: "A3.5" },
    { label: "A4", value: "A4" },
    { label: "B1", value: "B1" },
    { label: "B2", value: "B2" },
    { label: "B3", value: "B3" },
    { label: "B4", value: "B4" },
    { label: "C1", value: "C1" },
    { label: "C2", value: "C2" },
    { label: "C3", value: "C3" },
    { label: "C4", value: "C4" },
    { label: "D2", value: "D2" },
    { label: "D3", value: "D3" },
    { label: "D4", value: "D4" },
  ],
  labOrderStatuses: [
    { label: "Ordered", value: "Ordered" },
    { label: "In Progress", value: "In Progress" },
    { label: "Ready", value: "Ready" },
    { label: "Delivered", value: "Delivered" },
  ],
};

export const ORAL_EXAMINATION_FINDINGS = {
  lips: [
    { label: "Normal", value: "Normal" },
    { label: "Dry / Chapped", value: "Dry" },
    { label: "Ulceration", value: "Ulceration" },
    { label: "Angular Cheilitis", value: "AngularCheilitis" },
    { label: "Herpes Labialis", value: "Herpes" },
    { label: "Cleft Lip", value: "CleftLip" },
    { label: "Swelling", value: "Swelling" },
    { label: "Pigmentation", value: "Pigmentation" },
  ],
  buccalMucosa: [
    { label: "Normal", value: "Normal" },
    { label: "Hyperkeratosis", value: "Hyperkeratosis" },
    { label: "Leukoplakia", value: "Leukoplakia" },
    { label: "Erythroplakia", value: "Erythroplakia" },
    { label: "Lichen Planus", value: "LichenPlanus" },
    { label: "Ulceration", value: "Ulceration" },
    { label: "Fibroma", value: "Fibroma" },
    { label: "Linea Alba", value: "LineaAlba" },
  ],
  tongue: [
    { label: "Normal", value: "Normal" },
    { label: "Coated / Furred", value: "Coated" },
    { label: "Geographic Tongue", value: "Geographic" },
    { label: "Fissured Tongue", value: "Fissured" },
    { label: "Atrophic / Smooth", value: "Atrophic" },
    { label: "Ulceration", value: "Ulceration" },
    { label: "Leukoplakia", value: "Leukoplakia" },
    { label: "Macroglossia", value: "Macroglossia" },
  ],
  floorOfMouth: [
    { label: "Normal", value: "Normal" },
    { label: "Swelling", value: "Swelling" },
    { label: "Ranula", value: "Ranula" },
    { label: "Leukoplakia", value: "Leukoplakia" },
    { label: "Calculus", value: "Calculus" },
  ],
  palate: [
    { label: "Normal", value: "Normal" },
    { label: "High Arched", value: "HighArched" },
    { label: "Cleft Palate", value: "CleftPalate" },
    { label: "Erythema", value: "Erythema" },
    { label: "Petechiae", value: "Petechiae" },
    { label: "Toras Palatinus", value: "TorasPalatinus" },
  ],
  oropharynx: [
    { label: "Normal", value: "Normal" },
    { label: "Erythema", value: "Erythema" },
    { label: "Tonsillar Enlargement", value: "TonsillarEnlargement" },
    { label: "Exudate", value: "Exudate" },
    { label: "Ulceration", value: "Ulceration" },
  ],
  gingiva: [
    { label: "Normal / Healthy", value: "Normal" },
    { label: "Gingivitis", value: "Gingivitis" },
    { label: "Periodontitis", value: "Periodontitis" },
    { label: "Hyperplasia", value: "Hyperplasia" },
    { label: "Recession", value: "Recession" },
    { label: "Swelling", value: "Swelling" },
    { label: "Bleeding on Probing", value: "BOP" },
    { label: "Fistula / Sinus Tract", value: "Fistula" },
  ],
  salivaryGlands: [
    { label: "Normal", value: "Normal" },
    { label: "Enlarged", value: "Enlarged" },
    { label: "Tender", value: "Tender" },
    { label: "Reduced Saliva Flow", value: "ReducedFlow" },
    { label: "Sialolith (Calculus)", value: "Sialolith" },
  ],
};

export const DENTAL_CHART_OPTIONS = {
  toothStatus: [
    { label: "Present", value: "Present" },
    { label: "Missing", value: "Missing" },
    { label: "Impacted", value: "Impacted" },
    { label: "Fractured", value: "Fractured" },
    { label: "Root Stump", value: "RootStump" },
    { label: "Partially Erupted", value: "PartiallyErupted" },
  ],
  cariesStatus: [
    { label: "Sound (Healthy)", value: "Sound" },
    { label: "Decayed / Carious", value: "Decayed" },
    { label: "Filled (Restored)", value: "Filled" },
    { label: "Filled with Decay", value: "FilledDecay" },
    { label: "Missing due to Caries", value: "MissingCaries" },
    { label: "Fissure Sealant", value: "Sealant" },
  ],
  mobility: [
    { label: "None (Grade 0)", value: "0" },
    { label: "Grade I (1mm)", value: "1" },
    { label: "Grade II (2mm)", value: "2" },
    { label: "Grade III (3mm+)", value: "3" },
  ],
  furcationInvolvement: [
    { label: "None", value: "None" },
    { label: "Grade I (Early)", value: "I" },
    { label: "Grade II (Definite)", value: "II" },
    { label: "Grade III (Through & Through)", value: "III" },
  ],
};

export const NHIF_CLAIM_STATUSES = [
  { label: "Draft", value: "draft" },
  { label: "Submitted", value: "submitted" },
  { label: "Approved", value: "approved" },
  { label: "Rejected", value: "rejected" },
  { label: "Paid", value: "paid" },
];

export const HMIS_CANCER_TYPES = [
  { label: "Oral Cavity Cancer", value: "OralCavity" },
  { label: "Lip Cancer", value: "Lip" },
  { label: "Tongue Cancer", value: "Tongue" },
  { label: "Salivary Gland Cancer", value: "SalivaryGland" },
  { label: "Oropharyngeal Cancer", value: "Oropharynx" },
  { label: "Nasopharyngeal Cancer", value: "Nasopharynx" },
  { label: "Laryngeal Cancer", value: "Larynx" },
  { label: "Thyroid Cancer", value: "Thyroid" },
  { label: "Skin Cancer (Head & Neck)", value: "SkinHeadNeck" },
  { label: "Other (Specify)", value: "Other" },
];

export const DENTAL_SURGERY_RECORD_OPTIONS = {
  surgeryTypes: [
    { label: "Tooth Extraction", value: "Extraction" },
    { label: "Surgical Extraction", value: "SurgicalExtraction" },
    { label: "Root Canal Treatment", value: "RCT" },
    { label: "Apicectomy", value: "Apicectomy" },
    { label: "Dental Implant Placement", value: "ImplantPlacement" },
    { label: "Bone Grafting", value: "BoneGrafting" },
    { label: "Sinus Lift", value: "SinusLift" },
    { label: "Gingivectomy", value: "Gingivectomy" },
    { label: "Flap Surgery", value: "FlapSurgery" },
    { label: "Cyst Enucleation", value: "CystEnucleation" },
    { label: "Biopsy", value: "Biopsy" },
    { label: "Orthognathic Surgery", value: "Orthognathic" },
  ],
  anaesthesiaTypes: [
    { label: "Local Anaesthesia", value: "Local" },
    { label: "Regional Block (Inferior Alveolar)", value: "IANBlock" },
    { label: "Greater Palatine Block", value: "PalatineBlock" },
    { label: "General Anaesthesia", value: "General" },
    { label: "IV Sedation", value: "IVSedation" },
  ],
  toothOptions: [
    { label: "Upper Right (18-11)", value: "UpperRight" },
    { label: "Upper Left (21-28)", value: "UpperLeft" },
    { label: "Lower Left (31-38)", value: "LowerLeft" },
    { label: "Lower Right (41-48)", value: "LowerRight" },
    { label: "All Quadrants", value: "All" },
  ],
};

// Alias for backward compatibility (historical PDF generation)
export const CATARACT_SURGERY_RECORD_OPTIONS = DENTAL_SURGERY_RECORD_OPTIONS;
