import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAddressCard,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBars,
  faBell,
  faCalendarAlt,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faClock,
  faCopy,
  faCreditCard,
  faDownload,
  faEdit,
  faEllipsisVertical,
  faEnvelope,
  faEye,
  faFileInvoiceDollar,
  faFileLines,
  faFilter,
  faGear,
  faHeart,
  faHouse,
  faLock,
  faMagnifyingGlass,
  faMoneyBill,
  faPaperclip,
  faPenToSquare,
  faPhone,
  faPlus,
  faPrint,
  faQrcode,
  faRightFromBracket,
  faRotateLeft,
  faSave,
  faStethoscope,
  faTableList,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserDoctor,
  faUsers,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAddressCard,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faBars,
  faBell,
  faCalendarAlt,
  faChartBar,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faClock,
  faCopy,
  faCreditCard,
  faDownload,
  faEdit,
  faEllipsisVertical,
  faEnvelope,
  faEye,
  faFileInvoiceDollar,
  faFileLines,
  faFilter,
  faGear,
  faHeart,
  faHouse,
  faLock,
  faMagnifyingGlass,
  faMoneyBill,
  faPaperclip,
  faPenToSquare,
  faPhone,
  faPlus,
  faPrint,
  faQrcode,
  faRightFromBracket,
  faRotateLeft,
  faSave,
  faStethoscope,
  faTableList,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserDoctor,
  faUsers,
  faXmark
);

/**
 * Thin wrapper over Font Awesome so screens can request an icon by name and
 * inherit sizing from the surrounding utility classes.
 */
const Icon = ({ name = "circle-info", className = "w-4 h-4", ...rest }) => (
  <FontAwesomeIcon icon={name} className={className} {...rest} />
);

export default Icon;
