export const CATARACT_SURGERY_RECORD_OPTIONS = {
  lensExamination: [
    { label: "Clear lens", value: "1" },
    { label: "Opacity, not ready for operation", value: "2" },
    { label: "Operable cataract", value: "3" },
    { label: "Inoperable cataract", value: "4" },
    { label: "Aphakia", value: "5" },
    { label: "Pseudophakia", value: "6" },
    { label: "Cannot examine", value: "7" },
  ],
  otherOcularPathology: [
    { label: "Corneal scar", value: "1" },
    { label: "Old iritis", value: "2" },
    { label: "Retinal disease (Diabetes, AMD, etc.)", value: "3" },
    { label: "Glaucoma", value: "4" },
    { label: "Other & specify", value: "5" },
  ],
  vaCategories: [
    { label: "6/6", value: "6/6" },
    { label: "6/9", value: "6/9" },
    { label: "6/12", value: "6/12" },
    { label: "6/18", value: "6/18" },
    { label: "6/24", value: "6/24" },
    { label: "6/36", value: "6/36" },
    { label: "6/60", value: "6/60" },
    { label: "3/60", value: "3/60" },
    { label: "1/60", value: "1/60" },
    { label: "PL+", value: "PL+" },
    { label: "NPL", value: "NPL" },
    {
      label: "Cannot examine, believed < 6/60",
      value: "Cannot examine, belived < 6/60",
    },
    {
      label: "Cannot examine, believed > 6/60",
      value: "Cannot examine, belived > 6/60",
    },
  ],
  placeOfOperation: [
    { label: "Base hospital", value: "Base hospital" },
    { label: "Other hospital", value: "Other hospital" },
    { label: "Out of hospital", value: "Out of hospital" },
  ],
  typeOfSurgery: [
    { label: "ICCE", value: "ICCE" },
    { label: "ECCE", value: "ECCE" },
    { label: "SICS", value: "SICS" },
    { label: "Phaco", value: "Phaco" },
  ],
  iol: [
    { label: "PC-IOL", value: "PC-IOL" },
    { label: "AC-IOL", value: "AC-IOL" },
    { label: "No IOL", value: "No IOL" },
  ],
  training: [
    { label: "Ophthalmologist", value: "Ophthalmologist" },
    { label: "Resident / Trainee", value: "Resident / Trainee" },
    { label: "Cataract Surgeon", value: "Cataract Surgeon" },
  ],
  operativeComplications: [
    { label: "None", value: "None" },
    {
      label: "Capsule rupture without vitreous loss",
      value: "Capsule rupture without vitreous loss",
    },
    { label: "Vitreous loss", value: "Vitreous loss" },
    { label: "Zonular dehiscence", value: "Zonular dehiscence" },
    { label: "Retained lens matter", value: "Retained lens matter" },
    { label: "Wound leak", value: "Wound leak" },
    { label: "Striate keratopathy", value: "Striate keratopathy" },
    { label: "Endophthalmitis", value: "Endophthalmitis" },
    { label: "Others", value: "Others" },
  ],
  section: [
    { label: "Corneal", value: "Corneal" },
    { label: "Limbal", value: "Limbal" },
    { label: "Tunnel", value: "Tunnel" },
  ],
  capsulotomy: [
    { label: "Linear", value: "Linear" },
    { label: "CCC", value: "CCC" },
    { label: "Can opener", value: "Can opener" },
    { label: "Other", value: "Other" },
  ],
  suture: [
    { label: "No suture", value: "No suture" },
    { label: "Continuous", value: "Continuous" },
    { label: "Interrupted", value: "Interrupted" },
  ],
};
