import React from "react";
import Grid from "@mui/material/Grid";
import Skeleton from "@mui/material/Skeleton";

const LoadingSkeleton = () => {
  return (
    <Grid
      container
      spacing={{ xs: 2, sm: 2, md: 3 }}
    >
      <Grid
        item
        md={6}
        sm={12}
        xs={12}
      >
        <Grid
          container
          spacing={{ xs: 2, sm: 2, md: 3 }}
        >
          <Grid
            item
            md={6}
            sm={12}
            xs={12}
          >
            <Skeleton
              variant="rounded"
              height={96}
            />
          </Grid>
          <Grid
            item
            md={6}
            sm={12}
            xs={12}
          >
            <Skeleton
              variant="rounded"
              height={96}
            />
          </Grid>
          <Grid
            item
            md={6}
            sm={12}
            xs={12}
          >
            <Skeleton
              variant="rounded"
              height={96}
            />
          </Grid>
          <Grid
            item
            md={6}
            sm={12}
            xs={12}
          >
            <Skeleton
              variant="rounded"
              height={96}
            />
          </Grid>
          <Grid
            item
            md={6}
            sm={12}
            xs={12}
          >
            <Skeleton
              variant="rounded"
              height={96}
            />
          </Grid>
          <Grid
            item
            md={6}
            sm={12}
            xs={12}
          >
            <Skeleton
              variant="rounded"
              height={96}
            />
          </Grid>
        </Grid>
      </Grid>
      <Grid
        item
        md={3}
        sm={12}
        xs={12}
      >
        <Skeleton
          variant="rounded"
          height={336}
        />
      </Grid>
      <Grid
        item
        md={3}
        sm={12}
        xs={12}
      >
        <Skeleton
          variant="rounded"
          height={336}
        />
      </Grid>
      <Grid
        item
        md={6}
        sm={12}
        xs={12}
      >
        <Skeleton
          variant="rounded"
          height={256}
        />
      </Grid>
      <Grid
        item
        md={6}
        sm={12}
        xs={12}
      >
        <Skeleton
          variant="rounded"
          height={256}
        />
      </Grid>
    </Grid>
  );
};

export default LoadingSkeleton;
