<?php

namespace Database\Seeders;

use App\Models\ContentPost;
use App\Models\DrugMovement;
use App\Models\Expense;
use App\Models\RevenueRecord;
use App\Models\SupportTicket;
use App\Models\TicketReply;
use Illuminate\Database\Seeder;

class AdminModuleSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedContentPosts();
        $this->seedSupportTickets();
        $this->seedTicketReplies();
        $this->seedRevenueRecords();
        $this->seedExpenses();
        $this->seedDrugMovements();
    }

    private function seedContentPosts(): void
    {
        $posts = [
            [
                'title' => 'Welcome to Helix Platform',
                'type' => 'banner',
                'content' => 'Welcome to Helix - your all-in-one pharmacy management platform. Streamline your operations, manage inventory, and grow your pharmacy business with our comprehensive tools and analytics.',
                'image_url' => '/images/banners/welcome-banner.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(30),
                'ends_at' => now()->addMonths(6),
                'metadata' => ['position' => 'homepage_hero', 'priority' => 1],
                'created_by' => 1,
            ],
            [
                'title' => 'New Feature: Online Ordering Now Available',
                'type' => 'announcement',
                'content' => 'We are excited to announce that online ordering is now live! Customers can now browse your catalog, place orders, and schedule deliveries directly through the Helix platform. Enable this feature in your pharmacy settings to start accepting online orders today.',
                'image_url' => '/images/announcements/online-ordering.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(7),
                'ends_at' => now()->addMonths(3),
                'metadata' => ['feature_slug' => 'online-ordering', 'priority' => 2],
                'created_by' => 1,
            ],
            [
                'title' => 'Monthly Pharmacy Webinar - July 2026',
                'type' => 'promotion',
                'content' => 'Join our monthly pharmacy management webinar on July 30, 2026 at 2:00 PM EAT. This session covers best practices for inventory management, compliance updates, and tips for increasing pharmacy profitability. Register now - spots are limited!',
                'image_url' => '/images/promotions/webinar-july.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(3),
                'ends_at' => now()->addDays(10),
                'metadata' => ['event_date' => '2026-07-30', 'event_time' => '14:00', 'registration_url' => 'https://pharmex.com/webinars/july-2026'],
                'created_by' => 1,
            ],
            [
                'title' => 'Holiday Operating Hours Update',
                'type' => 'announcement',
                'content' => 'Please note that Helix support services will operate on reduced hours during the upcoming holiday period. Emergency support will remain available 24/7. For non-urgent inquiries, please submit a ticket and we will respond within 24 hours.',
                'image_url' => null,
                'status' => 'draft',
                'starts_at' => now()->addDays(14),
                'ends_at' => now()->addDays(21),
                'metadata' => ['holiday' => 'Nane Nane', 'support_hours' => '10:00 - 16:00'],
                'created_by' => 1,
            ],
            [
                'title' => 'Helix Partner Pharmacy Program',
                'type' => 'promotion',
                'content' => 'Introducing the Helix Partner Pharmacy Program! Earn exclusive benefits including priority support, discounted subscription rates, and co-marketing opportunities. Apply now through your admin dashboard to become a certified Helix partner.',
                'image_url' => '/images/promotions/partner-program.jpg',
                'status' => 'draft',
                'starts_at' => null,
                'ends_at' => null,
                'metadata' => ['discount_percentage' => 15, 'min_requirements' => '6 months active subscription'],
                'created_by' => 1,
            ],
            [
                'title' => 'System Maintenance Notice - August 2026',
                'type' => 'announcement',
                'content' => 'Scheduled system maintenance will take place on August 5, 2026 from 2:00 AM to 6:00 AM EAT. During this time, the platform may be temporarily unavailable. Please plan your operations accordingly.',
                'image_url' => null,
                'status' => 'active',
                'starts_at' => now()->subDays(2),
                'ends_at' => now()->addDays(10),
                'metadata' => ['maintenance_date' => '2026-08-05', 'duration_hours' => 4],
                'created_by' => 1,
            ],
            [
                'title' => 'New Supplier Partnership: Pharma Distributors Ltd',
                'type' => 'announcement',
                'content' => 'We are pleased to announce a new partnership with Pharma Distributors Ltd, one of Tanzanias leading pharmaceutical wholesalers. Helix users now get exclusive 8% discount on all orders.',
                'image_url' => '/images/announcements/pharma-distributors.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(10),
                'ends_at' => now()->addMonths(2),
                'metadata' => ['partner' => 'Pharma Distributors Ltd', 'discount' => 8],
                'created_by' => 1,
            ],
            [
                'title' => 'Customer Appreciation Week - Special Offers',
                'type' => 'promotion',
                'content' => 'Celebrate Customer Appreciation Week with Helix! Enjoy 20% off on subscription upgrades, free SMS credits, and bonus loyalty points. Valid August 1-7, 2026.',
                'image_url' => '/images/promotions/appreciation-week.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(5),
                'ends_at' => now()->addDays(15),
                'metadata' => ['promo_code' => 'APPRECIATE20', 'valid_until' => '2026-08-07'],
                'created_by' => 1,
            ],
            [
                'title' => 'Updated Inventory Management Guide',
                'type' => 'banner',
                'content' => 'Learn how to optimize your pharmacy inventory with our updated management guide. Covers batch tracking, expiry alerts, automatic reorder points, and TMDA compliance.',
                'image_url' => '/images/banners/inventory-guide.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(15),
                'ends_at' => now()->addMonths(3),
                'metadata' => ['guide_url' => 'https://pharmex.com/guides/inventory-management', 'priority' => 3],
                'created_by' => 1,
            ],
            [
                'title' => 'Helix Mobile App v2.0 Release',
                'type' => 'announcement',
                'content' => 'Helix Mobile App version 2.0 is now available! New features include offline mode, push notifications for low stock alerts, barcode scanning, and improved performance.',
                'image_url' => '/images/announcements/mobile-v2.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(8),
                'ends_at' => now()->addMonths(4),
                'metadata' => ['version' => '2.0', 'platforms' => ['android', 'ios']],
                'created_by' => 1,
            ],
            [
                'title' => 'Free Training Workshop: Digital Pharmacy',
                'type' => 'promotion',
                'content' => 'Join our free hands-on training workshop on running a digital pharmacy. Topics include POS systems, electronic prescriptions, and digital marketing. Limited to 30 participants.',
                'image_url' => '/images/promotions/training-workshop.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(4),
                'ends_at' => now()->addDays(20),
                'metadata' => ['location' => 'Dar es Salaam', 'capacity' => 30, 'date' => '2026-08-15'],
                'created_by' => 1,
            ],
            [
                'title' => 'Compliance Update: TMDA New Reporting Requirements',
                'type' => 'announcement',
                'content' => 'TMDA has introduced new monthly reporting requirements effective September 2026. Helix has updated its reporting module to comply. Please review the updated templates.',
                'image_url' => null,
                'status' => 'active',
                'starts_at' => now()->subDays(12),
                'ends_at' => now()->addMonths(2),
                'metadata' => ['regulatory_body' => 'TMDA', 'effective_date' => '2026-09-01'],
                'created_by' => 1,
            ],
            [
                'title' => 'End of Year Tax Filing Reminder',
                'type' => 'banner',
                'content' => 'The deadline for annual tax filing with TRA is approaching. Use Helix accounting module to generate your annual reports, VAT summaries, and PAYE statements.',
                'image_url' => '/images/banners/tax-reminder.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(1),
                'ends_at' => now()->addDays(30),
                'metadata' => ['tax_authority' => 'TRA', 'filing_deadline' => '2026-09-30'],
                'created_by' => 1,
            ],
            [
                'title' => 'Helix Annual Conference 2026',
                'type' => 'promotion',
                'content' => 'Save the date! Helix Annual Conference 2026 on October 15-16 at JNICC. Network with pharmacy owners, attend expert panels, and preview upcoming features.',
                'image_url' => '/images/promotions/annual-conference.jpg',
                'status' => 'draft',
                'starts_at' => now()->addDays(5),
                'ends_at' => now()->addDays(75),
                'metadata' => ['venue' => 'JNICC Dar es Salaam', 'dates' => '2026-10-15 to 2026-10-16'],
                'created_by' => 1,
            ],
            [
                'title' => 'Cold Chain Monitoring Feature Launch',
                'type' => 'announcement',
                'content' => 'Introducing our new cold chain monitoring feature! Track vaccine and temperature-sensitive medication storage in real-time. Get instant alerts for temperature deviations.',
                'image_url' => '/images/announcements/cold-chain.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(6),
                'ends_at' => now()->addMonths(5),
                'metadata' => ['feature_slug' => 'cold-chain-monitoring', 'sensors_supported' => 4],
                'created_by' => 1,
            ],
            [
                'title' => 'Flash Sale: Malaria Season Medications',
                'type' => 'promotion',
                'content' => 'Malaria season is here! Get 15% off on all antimalarial medications including ACTs, rapid diagnostic tests, and mosquito repellents.',
                'image_url' => '/images/promotions/malaria-season.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(3),
                'ends_at' => now()->addDays(25),
                'metadata' => ['promo_code' => 'MALARIA15', 'category' => 'antimalarials'],
                'created_by' => 1,
            ],
            [
                'title' => 'Insurance Integration: NHIF Claims Portal',
                'type' => 'announcement',
                'content' => 'Helix now supports direct NHIF claims submission! Process patient insurance claims directly from the POS and track claim status in real-time.',
                'image_url' => '/images/announcements/nhif-integration.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(9),
                'ends_at' => now()->addMonths(6),
                'metadata' => ['insurer' => 'NHIF', 'plan_required' => 'pro'],
                'created_by' => 1,
            ],
            [
                'title' => 'Customer Feedback Survey - Win Prizes',
                'type' => 'promotion',
                'content' => 'Help us improve! Complete our 5-minute customer feedback survey and stand a chance to win a free 3-month Pro plan upgrade.',
                'image_url' => '/images/promotions/feedback-survey.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(7),
                'ends_at' => now()->addDays(21),
                'metadata' => ['survey_url' => 'https://pharmex.com/survey/2026', 'prize' => '3 months Pro plan'],
                'created_by' => 1,
            ],
            [
                'title' => 'WhatsApp Business Integration Now Live',
                'type' => 'announcement',
                'content' => 'Connect your Helix account to WhatsApp Business! Send order confirmations, delivery updates, and promotional messages directly to customers.',
                'image_url' => '/images/announcements/whatsapp-integration.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(4),
                'ends_at' => now()->addMonths(3),
                'metadata' => ['feature_slug' => 'whatsapp-business', 'messaging_limit' => '1000/day'],
                'created_by' => 1,
            ],
            [
                'title' => 'Back to School Health Products Campaign',
                'type' => 'promotion',
                'content' => 'Get ready for the new school term! Stock up on childrens vitamins, first aid kits, hand sanitizers, and school health essentials. Bulk discounts available.',
                'image_url' => '/images/promotions/back-to-school.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(2),
                'ends_at' => now()->addDays(30),
                'metadata' => ['target' => 'schools', 'min_order' => 500000],
                'created_by' => 1,
            ],
            [
                'title' => 'Data Backup Best Practices for Pharmacies',
                'type' => 'banner',
                'content' => 'Protect your pharmacy data with our comprehensive backup guide. Learn about automatic cloud backups, local backup procedures, and data recovery steps.',
                'image_url' => '/images/banners/data-backup.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(14),
                'ends_at' => now()->addMonths(2),
                'metadata' => ['guide_url' => 'https://pharmex.com/guides/data-backup', 'priority' => 4],
                'created_by' => 1,
            ],
            [
                'title' => 'Helix API for Developers',
                'type' => 'announcement',
                'content' => 'The Helix REST API is now available for integration with third-party systems. Build custom integrations, connect with hospital management systems, or create specialized tools.',
                'image_url' => '/images/announcements/api-launch.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(11),
                'ends_at' => now()->addMonths(6),
                'metadata' => ['api_version' => 'v1', 'docs_url' => 'https://docs.pharmex.com/api'],
                'created_by' => 1,
            ],
            [
                'title' => 'Free Delivery Promotion - Dar es Salaam',
                'type' => 'promotion',
                'content' => 'Enjoy free delivery on all orders above TZS 25,000 within Dar es Salaam! Medications reach you within 2 hours. Valid through August 2026.',
                'image_url' => '/images/promotions/free-delivery.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(6),
                'ends_at' => now()->addDays(35),
                'metadata' => ['min_order' => 25000, 'delivery_zone' => 'Dar es Salaam'],
                'created_by' => 1,
            ],
            [
                'title' => 'Staff Training: Handling Controlled Substances',
                'type' => 'announcement',
                'content' => 'Mandatory training module on handling controlled substances is now available. All pharmacy staff must complete this training by August 31, 2026 for TMDA compliance.',
                'image_url' => null,
                'status' => 'active',
                'starts_at' => now()->subDays(8),
                'ends_at' => now()->addDays(35),
                'metadata' => ['deadline' => '2026-08-31', 'mandatory' => true],
                'created_by' => 1,
            ],
            [
                'title' => 'Helix Loyalty Program Update',
                'type' => 'promotion',
                'content' => 'Exciting updates to the Loyalty Program! Earn 2x points on all orders this month, redeem for free deliveries, and unlock exclusive member-only deals.',
                'image_url' => '/images/promotions/loyalty-update.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(3),
                'ends_at' => now()->addDays(28),
                'metadata' => ['multiplier' => 2, 'redemption_min' => 500],
                'created_by' => 1,
            ],
            [
                'title' => 'E-Prescription Feature Now Available',
                'type' => 'announcement',
                'content' => 'Doctors can now send prescriptions directly to your pharmacy! E-prescriptions reduce errors, speed up dispensing, and improve patient safety.',
                'image_url' => '/images/announcements/e-prescription.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(5),
                'ends_at' => now()->addMonths(4),
                'metadata' => ['feature_slug' => 'e-prescription', 'integrations' => ['hospital_hmis']],
                'created_by' => 1,
            ],
            [
                'title' => 'Helix Impact Report: Q2 2026',
                'type' => 'banner',
                'content' => 'Read our Q2 2026 Impact Report! Helix pharmacies served over 150,000 patients, processed 50,000+ prescriptions, and maintained 99.5% inventory accuracy.',
                'image_url' => '/images/banners/impact-report.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(1),
                'ends_at' => now()->addMonths(1),
                'metadata' => ['report_url' => 'https://pharmex.com/impact/q2-2026', 'quarter' => 'Q2-2026'],
                'created_by' => 1,
            ],
            [
                'title' => 'Rainy Season Health Tips Campaign',
                'type' => 'promotion',
                'content' => 'Stay healthy this rainy season! Stock up on antimalarials, ORS packets, and immune boosters. Use promo code RAINY20 for 20% off health essentials.',
                'image_url' => '/images/promotions/rainy-season.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(7),
                'ends_at' => now()->addDays(45),
                'metadata' => ['promo_code' => 'RAINY20', 'discount' => 20],
                'created_by' => 1,
            ],
            [
                'title' => 'Helix Partner Pharmacies Map',
                'type' => 'banner',
                'content' => 'Find your nearest Helix partner pharmacy on our updated interactive map! With 200+ locations across Tanzania, quality medications are always within reach.',
                'image_url' => '/images/banners/pharmacy-map.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(13),
                'ends_at' => now()->addMonths(6),
                'metadata' => ['map_url' => 'https://pharmex.com/map', 'total_pharmacies' => 200],
                'created_by' => 1,
            ],
            [
                'title' => 'Webinar Recap: Optimizing Pharmacy Margins',
                'type' => 'banner',
                'content' => 'Missed our latest webinar? Watch the recording to learn strategies for optimizing pharmacy profit margins including pricing, wastage reduction, and analytics.',
                'image_url' => '/images/banners/webinar-recap.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(10),
                'ends_at' => now()->addMonths(2),
                'metadata' => ['recording_url' => 'https://pharmex.com/webinars/margins-recap'],
                'created_by' => 1,
            ],
            [
                'title' => 'End of Year Clearance Sale',
                'type' => 'promotion',
                'content' => 'Clearance sale on selected medications approaching expiry! Get up to 50% off on products expiring within 6 months. Offer affordable medications while reducing wastage.',
                'image_url' => '/images/promotions/clearance-sale.jpg',
                'status' => 'draft',
                'starts_at' => now()->addDays(10),
                'ends_at' => now()->addDays(40),
                'metadata' => ['max_discount' => 50, 'condition' => 'expiring_within_6_months'],
                'created_by' => 1,
            ],
            [
                'title' => 'Helix Community Health Initiative',
                'type' => 'promotion',
                'content' => 'Join the Helix Community Health Initiative! Partner with us to provide free health screenings. We provide the equipment, you provide the space.',
                'image_url' => '/images/promotions/community-health.jpg',
                'status' => 'active',
                'starts_at' => now()->subDays(4),
                'ends_at' => now()->addDays(60),
                'metadata' => ['program' => 'community_health', 'resources_provided' => ['screening_kits', 'marketing_materials']],
                'created_by' => 1,
            ],
        ];

        foreach ($posts as $post) {
            ContentPost::create($post);
        }
    }

    private function seedSupportTickets(): void
    {
        $tickets = [
            [
                'pharmacy_id' => 1,
                'user_id' => 2,
                'subject' => 'Unable to generate monthly sales report',
                'description' => 'When I try to generate the monthly sales report for June 2026, the system shows an error message "Failed to generate report". I have tried multiple times and also tried different date ranges but the issue persists. This is affecting our ability to file monthly tax returns.',
                'priority' => 'high',
                'status' => 'in_progress',
                'category' => 'reporting',
                'assigned_to' => 1,
                'created_at' => now()->subDays(5),
            ],
            [
                'pharmacy_id' => 1,
                'user_id' => 3,
                'subject' => 'Drug inventory count not updating after sale',
                'description' => 'After processing a sale for Amoxicillin 500mg, the inventory count is not automatically reducing. I have to manually update the stock count each time. This started happening after the last system update. Please investigate this bug.',
                'priority' => 'urgent',
                'status' => 'open',
                'category' => 'inventory',
                'assigned_to' => 1,
                'created_at' => now()->subDays(2),
            ],
            [
                'pharmacy_id' => 1,
                'user_id' => 2,
                'subject' => 'Request for wholesale pricing feature',
                'description' => 'We would like to request a feature that allows us to set different pricing tiers for retail and wholesale customers. Currently we can only set one selling price per drug. Having tiered pricing would help us serve our bulk customers better while maintaining retail margins.',
                'priority' => 'low',
                'status' => 'resolved',
                'category' => 'feature_request',
                'assigned_to' => 1,
                'resolved_at' => now()->subDays(1),
                'created_at' => now()->subDays(10),
            ],
            [
                'pharmacy_id' => 1,
                'user_id' => 2,
                'subject' => 'Mobile app crashing on Android devices',
                'description' => 'Several of our staff members are experiencing crashes on the Helix mobile app when trying to access the prescription module. The issue occurs on Android 14 devices. iOS seems to work fine. This is disrupting our daily operations.',
                'priority' => 'high',
                'status' => 'open',
                'category' => 'technical',
                'assigned_to' => 1,
                'created_at' => now()->subDays(1),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Barcode scanner not connecting to POS', 'description' => 'The USB barcode scanner is not being recognized by the Helix POS system. It works on other software. We tried reinstalling drivers.', 'priority' => 'high', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(3),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'How to set up automatic reorder alerts', 'description' => 'We need help setting up automatic reorder alerts for fast-moving drugs like Amoxicillin and Paracetamol. Is there a way to configure minimum stock levels?', 'priority' => 'medium', 'status' => 'resolved', 'category' => 'general_inquiry', 'assigned_to' => 1, 'resolved_at' => now()->subDays(2), 'created_at' => now()->subDays(8),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 4, 'subject' => 'Cannot process NHIF insurance claims', 'description' => 'When trying to submit an NHIF claim, I receive error "Claim submission failed - invalid member number format". The member number is correct.', 'priority' => 'urgent', 'status' => 'in_progress', 'category' => 'insurance', 'assigned_to' => 1, 'created_at' => now()->subDays(4),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Request for multi-branch inventory view', 'description' => 'We are planning to open a second branch in Arusha. It would help to have a multi-branch inventory dashboard showing stock levels across all branches.', 'priority' => 'low', 'status' => 'open', 'category' => 'feature_request', 'assigned_to' => 1, 'created_at' => now()->subDays(7),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Incorrect VAT calculation on sales receipts', 'description' => 'VAT calculation on some receipts is showing TZS 16,667 instead of TZS 15,000 for a TZS 100,000 sale. This appears to be a tax rate configuration issue.', 'priority' => 'high', 'status' => 'in_progress', 'category' => 'accounting', 'assigned_to' => 1, 'created_at' => now()->subDays(6),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Slow loading times for drug catalog', 'description' => 'The drug catalog page takes over 10 seconds to load. We have over 500 drugs. Slow performance affects customer service during peak hours.', 'priority' => 'medium', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(5),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Need training on expiry date management module', 'description' => 'Our staff needs training on expiry date tracking. We want automatic alerts for products approaching expiry and monthly reports for TMDA compliance.', 'priority' => 'medium', 'status' => 'resolved', 'category' => 'general_inquiry', 'assigned_to' => 1, 'resolved_at' => now()->subDays(3), 'created_at' => now()->subDays(9),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 4, 'subject' => 'Customer receipt printer not working', 'description' => 'The thermal receipt printer stopped printing after the latest update. Model is Epson TM-T82. It worked before the July 20 update.', 'priority' => 'high', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(2),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Request for customer SMS notification feature', 'description' => 'It would be great if Helix could automatically send SMS notifications when prescriptions are ready for pickup or orders are out for delivery.', 'priority' => 'low', 'status' => 'open', 'category' => 'feature_request', 'assigned_to' => 1, 'created_at' => now()->subDays(11),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Export data to Excel not working', 'description' => 'The export to Excel function on the sales report page returns a blank file. CSV export works fine but Excel export fails for all date ranges.', 'priority' => 'medium', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(4),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'How to add new drug suppliers to the system', 'description' => 'We onboarded Mega Pharma Ltd and HealthFirst Distributors. We need to add them to our supplier database to track purchases and payments.', 'priority' => 'low', 'status' => 'resolved', 'category' => 'general_inquiry', 'assigned_to' => 1, 'resolved_at' => now()->subDays(5), 'created_at' => now()->subDays(12),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 4, 'subject' => 'Dashboard widget showing wrong revenue figures', 'description' => 'Revenue dashboard shows TZS 8,500,000 for July but actual records total TZS 7,200,000. The discrepancy seems to include pending transactions.', 'priority' => 'high', 'status' => 'in_progress', 'category' => 'reporting', 'assigned_to' => 1, 'created_at' => now()->subDays(3),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'User permissions not working correctly', 'description' => 'Junior assistant (user_id 5) should only access POS but can see accounting and inventory sections. Role-based permissions stopped working after update.', 'priority' => 'urgent', 'status' => 'open', 'category' => 'security', 'assigned_to' => 1, 'created_at' => now()->subDays(1),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Drug interaction checker not flagging interactions', 'description' => 'The drug interaction checker failed to flag a known interaction between Warfarin and Ibuprofen. This is a patient safety concern.', 'priority' => 'urgent', 'status' => 'in_progress', 'category' => 'clinical', 'assigned_to' => 1, 'created_at' => now()->subDays(2),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Monthly subscription payment failed', 'description' => 'Automatic subscription payment for July failed with "insufficient funds" error. Our bank has sufficient balance. Please investigate.', 'priority' => 'high', 'status' => 'resolved', 'category' => 'billing', 'assigned_to' => 1, 'resolved_at' => now()->subDays(4), 'created_at' => now()->subDays(7),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 4, 'subject' => 'Request for custom drug labels printing', 'description' => 'We need Helix to support custom label printing for dispensed medications with patient name, dosage, prescriber, and pharmacy branding. Required by TMDA.', 'priority' => 'medium', 'status' => 'open', 'category' => 'feature_request', 'assigned_to' => 1, 'created_at' => now()->subDays(8),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Duplicate entries in transaction history', 'description' => 'Several duplicate entries in transaction history for last week. Each sale appears twice, affecting financial reports and reconciliation.', 'priority' => 'high', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(3),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'How to generate TMDA controlled substance report', 'description' => 'We need to generate a monthly controlled substance report for TMDA. Can you guide us on using the Helix reporting module for this?', 'priority' => 'medium', 'status' => 'resolved', 'category' => 'general_inquiry', 'assigned_to' => 1, 'resolved_at' => now()->subDays(6), 'created_at' => now()->subDays(10),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'POS touchscreen calibration issue', 'description' => 'Touchscreen is registering touches offset from where I touch. Causes errors selecting items. Calibration was fine before moving to new counter.', 'priority' => 'medium', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(5),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Negative stock levels appearing in inventory', 'description' => 'Some products show negative stock levels. Metformin 500mg shows -15 units. Sales seem processed without proper stock validation.', 'priority' => 'urgent', 'status' => 'in_progress', 'category' => 'inventory', 'assigned_to' => 1, 'created_at' => now()->subDays(2),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 4, 'subject' => 'Customer loyalty points not calculating correctly', 'description' => 'Customer who spent TZS 50,000 received 50 points instead of 500. Points multiplier seems off by factor of 10.', 'priority' => 'high', 'status' => 'open', 'category' => 'loyalty', 'assigned_to' => 1, 'created_at' => now()->subDays(4),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Request for dark mode on mobile app', 'description' => 'Many pharmacists work late shifts and would appreciate dark mode. Bright screen causes eye strain during night shifts.', 'priority' => 'low', 'status' => 'open', 'category' => 'feature_request', 'assigned_to' => 1, 'created_at' => now()->subDays(14),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Incorrect supplier payment amounts', 'description' => 'Supplier payment module shows TZS 2,800,000 outstanding for Generic Pharma Ltd but our records show TZS 1,500,000. Discrepancy in payment application.', 'priority' => 'high', 'status' => 'in_progress', 'category' => 'accounting', 'assigned_to' => 1, 'created_at' => now()->subDays(6),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 4, 'subject' => 'Need help setting up delivery zones', 'description' => 'We want to offer delivery services. Can you help set up delivery zones with pricing? Free within 3km and TZS 2,000 beyond 3km.', 'priority' => 'medium', 'status' => 'open', 'category' => 'general_inquiry', 'assigned_to' => 1, 'created_at' => now()->subDays(9),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'System crashing during bulk stock entry', 'description' => 'When entering stock for 50+ items at once using bulk entry, the system crashes and I lose all data. Have to enter items one by one.', 'priority' => 'high', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(3),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Request for pharmacy performance analytics', 'description' => 'We need detailed analytics: top-selling drugs by profit margin, customer retention rates, peak selling hours, and seasonal demand patterns.', 'priority' => 'medium', 'status' => 'open', 'category' => 'feature_request', 'assigned_to' => 1, 'created_at' => now()->subDays(11),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Controlled substance log not saving entries', 'description' => 'Controlled substance dispensing records disappear after page refresh. This is a compliance issue as TMDA requires accurate records.', 'priority' => 'urgent', 'status' => 'open', 'category' => 'compliance', 'assigned_to' => 1, 'created_at' => now()->subDays(1),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 4, 'subject' => 'How to set up automatic daily sales summary emails', 'description' => 'I want Helix to send daily sales summary emails every evening. How do I configure the recipient and report format?', 'priority' => 'low', 'status' => 'resolved', 'category' => 'general_inquiry', 'assigned_to' => 1, 'resolved_at' => now()->subDays(7), 'created_at' => now()->subDays(13),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Tax report missing SDL records', 'description' => 'Skills Development Levy records are missing from our quarterly tax report. We need these for TRA filing. PAYE and VAT show correctly.', 'priority' => 'high', 'status' => 'in_progress', 'category' => 'accounting', 'assigned_to' => 1, 'created_at' => now()->subDays(5),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Medicine image uploads failing', 'description' => 'Product image uploads fail with "File size exceeds maximum". Even small JPEGs under 1MB fail. This worked fine before.', 'priority' => 'medium', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(7),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Monthly sales summary not matching POS totals', 'description' => 'The monthly sales summary in reporting shows TZS 500,000 less than our POS terminal totals. There seems to be a sync issue between POS and reporting.', 'priority' => 'high', 'status' => 'open', 'category' => 'reporting', 'assigned_to' => 1, 'created_at' => now()->subDays(2),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 4, 'subject' => 'Request for customer prescription history view', 'description' => 'As a clinic, we would like to view patient prescription history when they visit our pharmacy. This would help avoid drug interactions and improve care.', 'priority' => 'medium', 'status' => 'open', 'category' => 'feature_request', 'assigned_to' => 1, 'created_at' => now()->subDays(6),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 3, 'subject' => 'Barcode labels not printing correctly', 'description' => 'The barcode labels printed from Helix are too small for our shelf tags. We need an option to print larger labels with drug name, price, and barcode.', 'priority' => 'low', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(8),
            ],
            [
                'pharmacy_id' => 1, 'user_id' => 2, 'subject' => 'Unable to void a completed transaction', 'description' => 'A customer returned a product but we cannot void the original transaction. The void button is greyed out for transactions older than 24 hours. We need a manager override option.', 'priority' => 'high', 'status' => 'open', 'category' => 'technical', 'assigned_to' => 1, 'created_at' => now()->subDays(1),
            ],
        ];

        foreach ($tickets as $ticket) {
            SupportTicket::create($ticket);
        }
    }

    private function seedTicketReplies(): void
    {
        $replies = [
            [
                'ticket_id' => 1,
                'user_id' => 1,
                'message' => 'Thank you for reporting this issue. We have identified the root cause - a database timeout when querying large datasets. Our engineering team is working on a fix and it should be deployed within the next 24 hours. In the meantime, you can try generating a report for a shorter date range.',
                'created_at' => now()->subDays(4),
            ],
            [
                'ticket_id' => 1,
                'user_id' => 2,
                'message' => 'Thank you for the quick response. I tried generating the report for a single week and it worked. Looking forward to the permanent fix.',
                'created_at' => now()->subDays(3),
            ],
            [
                'ticket_id' => 3,
                'user_id' => 1,
                'message' => 'Great suggestion! We have added the tiered pricing feature to our product roadmap. It is currently planned for the Q3 2026 release. We will notify you once it is available. In the meantime, you can use the wholesale_price field in the drug form as a reference.',
                'created_at' => now()->subDays(9),
            ],
            ['ticket_id' => 2, 'user_id' => 1, 'message' => 'We are investigating the inventory update issue. It appears to be a race condition in the stock deduction logic. Our team is deploying a hotfix now.', 'created_at' => now()->subDays(1)],
            ['ticket_id' => 2, 'user_id' => 3, 'message' => 'I noticed the issue happened mainly during peak hours when multiple staff were processing sales simultaneously. Could it be a concurrency issue?', 'created_at' => now()->subDays(1)->subHours(2)],
            ['ticket_id' => 2, 'user_id' => 1, 'message' => 'Excellent observation! Yes, it is indeed a concurrency issue. We have deployed a fix using database-level locking for stock deductions. Please verify on your end.', 'created_at' => now()->subHours(18)],
            ['ticket_id' => 4, 'user_id' => 1, 'message' => 'We are aware of the Android crash issue. It affects Samsung devices running Android 14 with the latest security patch. We are releasing an emergency update tonight.', 'created_at' => now()->subHours(20)],
            ['ticket_id' => 4, 'user_id' => 2, 'message' => 'Our staff are mainly using Samsung Galaxy A14 and A24 devices. Will the fix address these specific models?', 'created_at' => now()->subHours(16)],
            ['ticket_id' => 4, 'user_id' => 1, 'message' => 'Yes, the fix specifically addresses the memory management issue on Samsung Galaxy A-series devices with Android 14. Please update to version 2.3.1 once available.', 'created_at' => now()->subHours(12)],
            ['ticket_id' => 5, 'user_id' => 1, 'message' => 'The barcode scanner issue is likely a USB driver compatibility problem. Please unplug the scanner, go to Settings > Hardware > Scanners, and click Add New Scanner.', 'created_at' => now()->subDays(2)],
            ['ticket_id' => 5, 'user_id' => 3, 'message' => 'I followed your steps and the scanner is now recognized! However, it scans the barcode value twice. Is there a setting to adjust the scan delay?', 'created_at' => now()->subDays(1)->subHours(6)],
            ['ticket_id' => 5, 'user_id' => 1, 'message' => 'Glad it is working! Set the scan delay to 300ms in Settings > Hardware > Scanners > Edit > Scan Delay. This prevents duplicate scans.', 'created_at' => now()->subDays(1)->subHours(3)],
            ['ticket_id' => 6, 'user_id' => 1, 'message' => 'To set up automatic reorder alerts, go to Inventory > Settings > Reorder Management. Set minimum stock level and reorder point for each drug.', 'created_at' => now()->subDays(7)],
            ['ticket_id' => 6, 'user_id' => 2, 'message' => 'I have set up reorder alerts for our top 50 fast-moving drugs. Is there a way to set different reorder points based on supplier lead times?', 'created_at' => now()->subDays(6)],
            ['ticket_id' => 6, 'user_id' => 1, 'message' => 'Yes! In supplier settings, you can set expected lead time. The system calculates optimal reorder point based on average daily sales and lead time.', 'created_at' => now()->subDays(5)],
            ['ticket_id' => 7, 'user_id' => 1, 'message' => 'We have identified the NHIF claim issue. The new API requires member numbers in format NHIF-XXXXXXXXXX. We are updating the validation regex.', 'created_at' => now()->subDays(3)],
            ['ticket_id' => 7, 'user_id' => 4, 'message' => 'That makes sense. Our NHIF member numbers are in format NHIF-1234567890. When will the fix be deployed?', 'created_at' => now()->subDays(2)->subHours(6)],
            ['ticket_id' => 7, 'user_id' => 1, 'message' => 'The fix has been deployed in version 2.3.1. You can now submit NHIF claims with the standard format. Please update and try again.', 'created_at' => now()->subDays(2)],
            ['ticket_id' => 9, 'user_id' => 1, 'message' => 'We found the VAT calculation error. The system was using inclusive VAT rate instead of exclusive. Correct formula: VAT = Sale Amount * 0.15 / 1.15. Deploying fix today.', 'created_at' => now()->subDays(5)],
            ['ticket_id' => 9, 'user_id' => 4, 'message' => 'Will the fix retroactively correct existing receipts generated with wrong VAT amounts?', 'created_at' => now()->subDays(4)->subHours(8)],
            ['ticket_id' => 9, 'user_id' => 1, 'message' => 'The fix corrects going forward. For historical receipts, regenerate from Sales History by selecting receipts and clicking Regenerate.', 'created_at' => now()->subDays(4)],
            ['ticket_id' => 10, 'user_id' => 1, 'message' => 'The slow loading is due to drug catalog loading all images at once. We are implementing lazy loading and image compression to reduce load time from 10s to under 2s.', 'created_at' => now()->subDays(4)],
            ['ticket_id' => 11, 'user_id' => 1, 'message' => 'Training scheduled! 30-minute video call on Thursday at 10am to walk through the expiry date management module. Calendar invite sent.', 'created_at' => now()->subDays(8)],
            ['ticket_id' => 11, 'user_id' => 3, 'message' => 'Thank you! I have accepted the invite. I will bring our other pharmacy assistant so she can learn as well.', 'created_at' => now()->subDays(7)->subHours(4)],
            ['ticket_id' => 12, 'user_id' => 1, 'message' => 'The receipt printer issue is caused by the latest update changing ESC/POS command set. Patch tonight restores compatibility with Epson TM-T82 and TM-T88.', 'created_at' => now()->subHours(18)],
            ['ticket_id' => 14, 'user_id' => 1, 'message' => 'Excel export issue is caused by a library update breaking .xlsx generation. CSV uses a different code path. Fix coming in next patch.', 'created_at' => now()->subDays(3)],
            ['ticket_id' => 14, 'user_id' => 4, 'message' => 'Estimated time for the fix? We need to submit Excel reports to our accountant by end of this week.', 'created_at' => now()->subDays(2)->subHours(8)],
            ['ticket_id' => 14, 'user_id' => 1, 'message' => 'Fix deploys within 24 hours. Temporary workaround: export as CSV and open in Excel. Alternatively, we can generate and email the report.', 'created_at' => now()->subDays(2)],
            ['ticket_id' => 16, 'user_id' => 1, 'message' => 'Please provide supplier details including company name, contact person, phone number, and payment terms. I will set them up today.', 'created_at' => now()->subDays(11)],
            ['ticket_id' => 16, 'user_id' => 3, 'message' => 'Mega Pharma Ltd - Contact: John Mwamba, +255 712 345 678, Terms: Net 30. HealthFirst Distributors - Contact: Amina Hassan, +255 754 321 987, Terms: Net 15.', 'created_at' => now()->subDays(10)->subHours(6)],
            ['ticket_id' => 16, 'user_id' => 1, 'message' => 'Both suppliers added with correct payment terms and contact details. You can now create purchase orders from the Procurement module.', 'created_at' => now()->subDays(10)],
            ['ticket_id' => 17, 'user_id' => 1, 'message' => 'Revenue dashboard discrepancy is because it includes pending transactions. We are updating to show breakdown: confirmed, pending, and total.', 'created_at' => now()->subDays(2)],
            ['ticket_id' => 18, 'user_id' => 1, 'message' => 'This is a critical security issue. Please change password for user_id 5 and review their recent activity logs while we investigate.', 'created_at' => now()->subHours(22)],
            ['ticket_id' => 18, 'user_id' => 2, 'message' => 'Password changed. Please prioritize this fix. The junior assistant should not have access to financial data.', 'created_at' => now()->subHours(20)],
            ['ticket_id' => 18, 'user_id' => 1, 'message' => 'Emergency patch deployed. User role 5 is now limited to POS and basic inventory viewing only. Full security audit of permission system is underway.', 'created_at' => now()->subHours(16)],
            ['ticket_id' => 19, 'user_id' => 1, 'message' => 'Serious patient safety concern. We are updating drug interaction database immediately. Warfarin-Ibuprofen interaction added to high-severity alerts.', 'created_at' => now()->subHours(20)],
            ['ticket_id' => 19, 'user_id' => 3, 'message' => 'Can you also check for other missing interactions? We want to ensure patient safety across all prescriptions.', 'created_at' => now()->subHours(18)],
            ['ticket_id' => 19, 'user_id' => 1, 'message' => 'Comprehensive review completed against WHO interaction list. Found and fixed 23 missing interactions. Quarterly review process being implemented.', 'created_at' => now()->subHours(14)],
            ['ticket_id' => 20, 'user_id' => 1, 'message' => 'Payment gateway issue identified. Your bank changed API endpoints without notice. Updated system. Subscription manually renewed. Next payment should process automatically.', 'created_at' => now()->subDays(5)],
            ['ticket_id' => 20, 'user_id' => 2, 'message' => 'Subscription is active again. Will we be charged a late fee for the failed payment?', 'created_at' => now()->subDays(4)->subHours(8)],
            ['ticket_id' => 20, 'user_id' => 1, 'message' => 'No late fee applied since failure was bank-side. Billing cycle restored to normal. Apologies for the inconvenience.', 'created_at' => now()->subDays(4)],
            ['ticket_id' => 22, 'user_id' => 1, 'message' => 'Investigating duplicate transaction entries. Appears related to network timeout during sales sync. Implementing transaction deduplication logic.', 'created_at' => now()->subDays(2)],
            ['ticket_id' => 24, 'user_id' => 1, 'message' => 'Go to Reports > Regulatory > Controlled Substances. Select reporting period and drug category. System generates TMDA-format PDF. Step-by-step guide sent to email.', 'created_at' => now()->subDays(9)],
            ['ticket_id' => 24, 'user_id' => 2, 'message' => 'Report generated successfully! Format matches TMDA requirements perfectly. This saves us a lot of time.', 'created_at' => now()->subDays(8)],
            ['ticket_id' => 25, 'user_id' => 1, 'message' => 'Touchscreen calibration issue likely from new counter surface. Go to Settings > Hardware > Touchscreen > Calibrate and follow the 4-point process.', 'created_at' => now()->subDays(4)],
            ['ticket_id' => 26, 'user_id' => 1, 'message' => 'Negative stock issue caused by offline mode sync not checking stock availability. Fix deployed and stock reconciliation script running.', 'created_at' => now()->subHours(20)],
            ['ticket_id' => 26, 'user_id' => 3, 'message' => 'How do I run the reconciliation script? We have about 15 products showing negative stock.', 'created_at' => now()->subHours(16)],
            ['ticket_id' => 26, 'user_id' => 1, 'message' => 'Go to Inventory > Tools > Stock Reconciliation. Select Auto-fix negative stock. Then do physical count and update correct quantities.', 'created_at' => now()->subHours(12)],
            ['ticket_id' => 27, 'user_id' => 1, 'message' => 'Loyalty points bug is in the multiplier calculation - dividing by 100 instead of 10. Fix deployed. Affected customers points corrected retroactively.', 'created_at' => now()->subDays(3)],
            ['ticket_id' => 29, 'user_id' => 1, 'message' => 'Investigating supplier payment discrepancy. Appears some early payment discounts were not properly recorded. Corrected statement within 24 hours.', 'created_at' => now()->subDays(5)],
            ['ticket_id' => 31, 'user_id' => 1, 'message' => 'Bulk stock entry crash occurs with 50+ items. Increasing batch limit and implementing auto-save so you never lose entered data.', 'created_at' => now()->subDays(2)],
            ['ticket_id' => 33, 'user_id' => 1, 'message' => 'Controlled substance log issue is a data persistence bug - entries saved to temp cache instead of database. Urgent fix deployed. Re-enter missing entries.', 'created_at' => now()->subHours(20)],
            ['ticket_id' => 35, 'user_id' => 1, 'message' => 'Go to Settings > Notifications > Daily Reports. Enter recipient emails, select format, and choose delivery time. First email sends tonight.', 'created_at' => now()->subDays(12)],
            ['ticket_id' => 35, 'user_id' => 4, 'message' => 'Daily sales summary configured and working perfectly! The 6pm email gives a clear overview. Thank you for this feature.', 'created_at' => now()->subDays(11)],
            ['ticket_id' => 36, 'user_id' => 1, 'message' => 'SDL records were in a separate table not included in the tax report query. Report being updated to include SDL. Fix live by tomorrow.', 'created_at' => now()->subDays(4)],
            ['ticket_id' => 37, 'user_id' => 1, 'message' => 'Image upload issue caused by incorrect server-side file size limit. Increased to 5MB for product images. Uploads should work now.', 'created_at' => now()->subDays(6)],
            ['ticket_id' => 37, 'user_id' => 3, 'message' => 'Image uploads working! Product catalog looks much better with photos. Thank you for the quick fix.', 'created_at' => now()->subDays(5)],
        ];

        foreach ($replies as $reply) {
            TicketReply::create($reply);
        }
    }

    private function seedRevenueRecords(): void
    {
        $records = [
            [
                'pharmacy_id' => 1,
                'type' => 'subscription',
                'amount' => 500000.00,
                'description' => 'Helix Pro Plan - Annual Subscription',
                'invoice_number' => 'INV-2026-SUB-001',
                'status' => 'paid',
                'due_date' => '2026-01-15',
                'paid_at' => '2026-01-14',
                'payment_method' => 'bank_transfer',
                'notes' => 'Annual subscription payment for Mwalimu Pharmacy',
            ],
            [
                'pharmacy_id' => 1,
                'type' => 'commission',
                'amount' => 87500.00,
                'description' => 'Platform commission on July 2026 orders (5%)',
                'invoice_number' => 'INV-2026-COM-007',
                'status' => 'pending',
                'due_date' => '2026-08-05',
                'paid_at' => null,
                'payment_method' => null,
                'notes' => 'Commission calculated on total sales of TZS 1,750,000',
            ],
            [
                'pharmacy_id' => 1,
                'type' => 'service',
                'amount' => 150000.00,
                'description' => 'Premium listing and featured placement - July 2026',
                'invoice_number' => 'INV-2026-SRV-003',
                'status' => 'paid',
                'due_date' => '2026-07-01',
                'paid_at' => '2026-06-28',
                'payment_method' => 'mobile_money',
                'notes' => 'Featured placement on Helix customer app homepage',
            ],
            [
                'pharmacy_id' => 1,
                'type' => 'subscription',
                'amount' => 50000.00,
                'description' => 'Helix Pro Plan - Monthly Renewal',
                'invoice_number' => 'INV-2026-SUB-008',
                'status' => 'paid',
                'due_date' => '2026-08-01',
                'paid_at' => '2026-07-30',
                'payment_method' => 'mobile_money',
                'notes' => 'Monthly subscription renewal',
            ],
            [
                'pharmacy_id' => 1,
                'type' => 'commission',
                'amount' => 62000.00,
                'description' => 'Platform commission on June 2026 orders (5%)',
                'invoice_number' => 'INV-2026-COM-006',
                'status' => 'paid',
                'due_date' => '2026-07-05',
                'paid_at' => '2026-07-03',
                'payment_method' => 'bank_transfer',
                'notes' => 'Commission on June sales of TZS 1,240,000',
            ],
            [
                'pharmacy_id' => 1,
                'type' => 'service',
                'amount' => 75000.00,
                'description' => 'SMS notification package - 5000 credits',
                'invoice_number' => 'INV-2026-SRV-004',
                'status' => 'overdue',
                'due_date' => '2026-07-20',
                'paid_at' => null,
                'payment_method' => null,
                'notes' => 'SMS credits for customer order notifications and reminders',
            ],
            ['pharmacy_id' => 1, 'type' => 'subscription', 'amount' => 50000.00, 'description' => 'Helix Pro Plan - Monthly Renewal January', 'invoice_number' => 'INV-2026-SUB-002', 'status' => 'paid', 'due_date' => '2026-02-01', 'paid_at' => '2026-01-30', 'payment_method' => 'mobile_money', 'notes' => 'January 2026 monthly subscription'],
            ['pharmacy_id' => 1, 'type' => 'subscription', 'amount' => 50000.00, 'description' => 'Helix Pro Plan - Monthly Renewal February', 'invoice_number' => 'INV-2026-SUB-003', 'status' => 'paid', 'due_date' => '2026-03-01', 'paid_at' => '2026-02-28', 'payment_method' => 'mobile_money', 'notes' => 'February 2026 monthly subscription'],
            ['pharmacy_id' => 1, 'type' => 'subscription', 'amount' => 50000.00, 'description' => 'Helix Pro Plan - Monthly Renewal March', 'invoice_number' => 'INV-2026-SUB-004', 'status' => 'paid', 'due_date' => '2026-04-01', 'paid_at' => '2026-03-30', 'payment_method' => 'bank_transfer', 'notes' => 'March 2026 monthly subscription'],
            ['pharmacy_id' => 1, 'type' => 'subscription', 'amount' => 50000.00, 'description' => 'Helix Pro Plan - Monthly Renewal April', 'invoice_number' => 'INV-2026-SUB-005', 'status' => 'paid', 'due_date' => '2026-05-01', 'paid_at' => '2026-04-29', 'payment_method' => 'mobile_money', 'notes' => 'April 2026 monthly subscription'],
            ['pharmacy_id' => 1, 'type' => 'subscription', 'amount' => 50000.00, 'description' => 'Helix Pro Plan - Monthly Renewal May', 'invoice_number' => 'INV-2026-SUB-006', 'status' => 'paid', 'due_date' => '2026-06-01', 'paid_at' => '2026-05-31', 'payment_method' => 'mobile_money', 'notes' => 'May 2026 monthly subscription'],
            ['pharmacy_id' => 1, 'type' => 'subscription', 'amount' => 50000.00, 'description' => 'Helix Pro Plan - Monthly Renewal June', 'invoice_number' => 'INV-2026-SUB-007', 'status' => 'paid', 'due_date' => '2026-07-01', 'paid_at' => '2026-06-30', 'payment_method' => 'bank_transfer', 'notes' => 'June 2026 monthly subscription'],
            ['pharmacy_id' => 1, 'type' => 'commission', 'amount' => 55000.00, 'description' => 'Platform commission on January 2026 orders (5%)', 'invoice_number' => 'INV-2026-COM-001', 'status' => 'paid', 'due_date' => '2026-02-05', 'paid_at' => '2026-02-03', 'payment_method' => 'bank_transfer', 'notes' => 'Commission on January sales of TZS 1,100,000'],
            ['pharmacy_id' => 1, 'type' => 'commission', 'amount' => 48000.00, 'description' => 'Platform commission on February 2026 orders (5%)', 'invoice_number' => 'INV-2026-COM-002', 'status' => 'paid', 'due_date' => '2026-03-05', 'paid_at' => '2026-03-04', 'payment_method' => 'mobile_money', 'notes' => 'Commission on February sales of TZS 960,000'],
            ['pharmacy_id' => 1, 'type' => 'commission', 'amount' => 72000.00, 'description' => 'Platform commission on March 2026 orders (5%)', 'invoice_number' => 'INV-2026-COM-003', 'status' => 'paid', 'due_date' => '2026-04-05', 'paid_at' => '2026-04-03', 'payment_method' => 'bank_transfer', 'notes' => 'Commission on March sales of TZS 1,440,000'],
            ['pharmacy_id' => 1, 'type' => 'commission', 'amount' => 68000.00, 'description' => 'Platform commission on April 2026 orders (5%)', 'invoice_number' => 'INV-2026-COM-004', 'status' => 'paid', 'due_date' => '2026-05-05', 'paid_at' => '2026-05-04', 'payment_method' => 'mobile_money', 'notes' => 'Commission on April sales of TZS 1,360,000'],
            ['pharmacy_id' => 1, 'type' => 'commission', 'amount' => 75000.00, 'description' => 'Platform commission on May 2026 orders (5%)', 'invoice_number' => 'INV-2026-COM-005', 'status' => 'paid', 'due_date' => '2026-06-05', 'paid_at' => '2026-06-03', 'payment_method' => 'bank_transfer', 'notes' => 'Commission on May sales of TZS 1,500,000'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 150000.00, 'description' => 'Premium listing - June 2026', 'invoice_number' => 'INV-2026-SRV-001', 'status' => 'paid', 'due_date' => '2026-06-01', 'paid_at' => '2026-05-29', 'payment_method' => 'bank_transfer', 'notes' => 'Featured placement June'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 75000.00, 'description' => 'SMS credits Q2 2026', 'invoice_number' => 'INV-2026-SRV-002', 'status' => 'paid', 'due_date' => '2026-04-15', 'paid_at' => '2026-04-14', 'payment_method' => 'mobile_money', 'notes' => 'SMS credits for Q2 2026'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 200000.00, 'description' => 'Custom API integration setup fee', 'invoice_number' => 'INV-2026-SRV-005', 'status' => 'paid', 'due_date' => '2026-03-15', 'paid_at' => '2026-03-14', 'payment_method' => 'bank_transfer', 'notes' => 'One-time API setup for hospital system'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 50000.00, 'description' => 'Staff training session', 'invoice_number' => 'INV-2026-SRV-006', 'status' => 'paid', 'due_date' => '2026-02-20', 'paid_at' => '2026-02-19', 'payment_method' => 'mobile_money', 'notes' => 'On-site training for 6 staff'],
            ['pharmacy_id' => 1, 'type' => 'subscription', 'amount' => 50000.00, 'description' => 'Helix Pro Plan - Monthly Renewal August', 'invoice_number' => 'INV-2026-SUB-009', 'status' => 'pending', 'due_date' => '2026-09-01', 'paid_at' => null, 'payment_method' => null, 'notes' => 'Upcoming August subscription'],
            ['pharmacy_id' => 1, 'type' => 'commission', 'amount' => 92000.00, 'description' => 'Platform commission on August 2026 orders (5%)', 'invoice_number' => 'INV-2026-COM-008', 'status' => 'pending', 'due_date' => '2026-09-05', 'paid_at' => null, 'payment_method' => null, 'notes' => 'Projected commission on estimated August sales'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 150000.00, 'description' => 'Premium listing - August 2026', 'invoice_number' => 'INV-2026-SRV-007', 'status' => 'pending', 'due_date' => '2026-08-01', 'paid_at' => null, 'payment_method' => null, 'notes' => 'Featured placement August'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 75000.00, 'description' => 'SMS credits Q3 2026', 'invoice_number' => 'INV-2026-SRV-008', 'status' => 'paid', 'due_date' => '2026-08-01', 'paid_at' => '2026-07-30', 'payment_method' => 'mobile_money', 'notes' => 'SMS credits for Q3'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 100000.00, 'description' => 'Cold chain monitoring device setup', 'invoice_number' => 'INV-2026-SRV-009', 'status' => 'paid', 'due_date' => '2026-06-15', 'paid_at' => '2026-06-14', 'payment_method' => 'bank_transfer', 'notes' => 'Temperature sensor installation'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 25000.00, 'description' => 'Extra 10GB cloud backup storage', 'invoice_number' => 'INV-2026-SRV-010', 'status' => 'paid', 'due_date' => '2026-05-01', 'paid_at' => '2026-04-30', 'payment_method' => 'mobile_money', 'notes' => 'Additional cloud storage'],
            ['pharmacy_id' => 1, 'type' => 'subscription', 'amount' => 50000.00, 'description' => 'Helix Pro Plan - Monthly Renewal September', 'invoice_number' => 'INV-2026-SUB-010', 'status' => 'pending', 'due_date' => '2026-10-01', 'paid_at' => null, 'payment_method' => null, 'notes' => 'Upcoming September subscription'],
            ['pharmacy_id' => 1, 'type' => 'commission', 'amount' => 95000.00, 'description' => 'Platform commission on September 2026 orders (5%)', 'invoice_number' => 'INV-2026-COM-009', 'status' => 'overdue', 'due_date' => '2026-07-05', 'paid_at' => null, 'payment_method' => null, 'notes' => 'Overdue commission - follow up needed'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 300000.00, 'description' => 'Annual conference sponsorship package', 'invoice_number' => 'INV-2026-SRV-011', 'status' => 'pending', 'due_date' => '2026-09-15', 'paid_at' => null, 'payment_method' => null, 'notes' => 'Gold sponsor for Annual Conference 2026'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 50000.00, 'description' => 'Branded receipt paper and pharmacy materials', 'invoice_number' => 'INV-2026-SRV-012', 'status' => 'paid', 'due_date' => '2026-04-10', 'paid_at' => '2026-04-09', 'payment_method' => 'mobile_money', 'notes' => 'Custom branded receipt rolls'],
            ['pharmacy_id' => 1, 'type' => 'service', 'amount' => 125000.00, 'description' => 'WhatsApp Business API setup', 'invoice_number' => 'INV-2026-SRV-013', 'status' => 'paid', 'due_date' => '2026-07-15', 'paid_at' => '2026-07-14', 'payment_method' => 'bank_transfer', 'notes' => 'WhatsApp Business integration setup'],
            ['pharmacy_id' => 1, 'type' => 'commission', 'amount' => 45000.00, 'description' => 'Platform commission on October 2026 orders (5%)', 'invoice_number' => 'INV-2026-COM-010', 'status' => 'pending', 'due_date' => '2026-11-05', 'paid_at' => null, 'payment_method' => null, 'notes' => 'Projected commission on October sales'],
        ];

        foreach ($records as $record) {
            RevenueRecord::create($record);
        }
    }

    private function seedExpenses(): void
    {
        $expenses = [
            [
                'category' => 'Rent',
                'description' => 'Monthly pharmacy premises rent - July 2026',
                'amount' => 850000.00,
                'date' => '2026-07-01',
                'receipt_number' => 'RCT-RENT-0726',
                'recorded_by' => 2,
                'created_at' => now()->subDays(25),
            ],
            [
                'category' => 'Utilities',
                'description' => 'Electricity bill - TANESCO July 2026',
                'amount' => 185000.00,
                'date' => '2026-07-05',
                'receipt_number' => 'RCT-ELEC-0726',
                'recorded_by' => 2,
                'created_at' => now()->subDays(21),
            ],
            [
                'category' => 'Salaries',
                'description' => 'Staff salaries - July 2026 (pharmacist + 2 assistants)',
                'amount' => 2800000.00,
                'date' => '2026-07-28',
                'receipt_number' => null,
                'recorded_by' => 2,
                'created_at' => now()->subDays(2),
            ],
            [
                'category' => 'Marketing',
                'description' => 'Social media advertising - Facebook & Instagram July 2026',
                'amount' => 350000.00,
                'date' => '2026-07-10',
                'receipt_number' => 'RCT-MKT-0726',
                'recorded_by' => 2,
                'created_at' => now()->subDays(16),
            ],
            [
                'category' => 'Supplies',
                'description' => 'Pharmacy supplies - labels, packaging, dispensing materials',
                'amount' => 95000.00,
                'date' => '2026-07-12',
                'receipt_number' => 'RCT-SUP-0726',
                'recorded_by' => 2,
                'created_at' => now()->subDays(14),
            ],
            [
                'category' => 'Insurance',
                'description' => 'Pharmacy liability insurance - Q3 2026 premium',
                'amount' => 450000.00,
                'date' => '2026-07-01',
                'receipt_number' => 'RCT-INS-0726',
                'recorded_by' => 2,
                'created_at' => now()->subDays(25),
            ],
            ['category' => 'Marketing', 'description' => 'Billboard advertising - Morogoro Road location', 'amount' => 450000.00, 'date' => '2026-06-15', 'receipt_number' => 'RCT-MKT-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(30)],
            ['category' => 'Utilities', 'description' => 'Internet service - Tigo Business fiber', 'amount' => 85000.00, 'date' => '2026-06-01', 'receipt_number' => 'RCT-INT-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(28)],
            ['category' => 'Supplies', 'description' => 'Receipt paper rolls - 10 boxes', 'amount' => 45000.00, 'date' => '2026-06-20', 'receipt_number' => 'RCT-SUP-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(25)],
            ['category' => 'Maintenance', 'description' => 'Air conditioner servicing - summer maintenance', 'amount' => 65000.00, 'date' => '2026-06-25', 'receipt_number' => 'RCT-MNT-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(20)],
            ['category' => 'Rent', 'description' => 'Monthly pharmacy premises rent - June 2026', 'amount' => 850000.00, 'date' => '2026-06-01', 'receipt_number' => 'RCT-RENT-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(28)],
            ['category' => 'Utilities', 'description' => 'Water bill - DAWASCO June 2026', 'amount' => 45000.00, 'date' => '2026-06-05', 'receipt_number' => 'RCT-WAT-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(27)],
            ['category' => 'Marketing', 'description' => 'Social media advertising - June 2026', 'amount' => 280000.00, 'date' => '2026-06-10', 'receipt_number' => 'RCT-MKT2-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(26)],
            ['category' => 'Supplies', 'description' => 'Pharmacy labels and packaging materials', 'amount' => 72000.00, 'date' => '2026-06-15', 'receipt_number' => 'RCT-SUP2-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(24)],
            ['category' => 'Transport', 'description' => 'Fuel for delivery van - June', 'amount' => 120000.00, 'date' => '2026-06-28', 'receipt_number' => 'RCT-TRN-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(19)],
            ['category' => 'Insurance', 'description' => 'Van insurance - monthly installment', 'amount' => 85000.00, 'date' => '2026-06-01', 'receipt_number' => 'RCT-INS2-0626', 'recorded_by' => 2, 'created_at' => now()->subDays(28)],
            ['category' => 'Rent', 'description' => 'Monthly pharmacy premises rent - May 2026', 'amount' => 850000.00, 'date' => '2026-05-01', 'receipt_number' => 'RCT-RENT-0526', 'recorded_by' => 2, 'created_at' => now()->subDays(58)],
            ['category' => 'Utilities', 'description' => 'Electricity bill - TANESCO May 2026', 'amount' => 210000.00, 'date' => '2026-05-05', 'receipt_number' => 'RCT-ELEC-0526', 'recorded_by' => 2, 'created_at' => now()->subDays(57)],
            ['category' => 'Supplies', 'description' => 'Hand sanitizer and cleaning supplies', 'amount' => 55000.00, 'date' => '2026-05-10', 'receipt_number' => 'RCT-SUP-0526', 'recorded_by' => 2, 'created_at' => now()->subDays(52)],
            ['category' => 'Marketing', 'description' => 'Radio ad on Times FM - one week slot', 'amount' => 500000.00, 'date' => '2026-05-15', 'receipt_number' => 'RCT-MKT-0526', 'recorded_by' => 2, 'created_at' => now()->subDays(47)],
            ['category' => 'Maintenance', 'description' => 'Pharmaceutical refrigerator service', 'amount' => 150000.00, 'date' => '2026-05-20', 'receipt_number' => 'RCT-MNT-0526', 'recorded_by' => 2, 'created_at' => now()->subDays(42)],
            ['category' => 'Supplies', 'description' => 'Printer ink cartridges - 3 units', 'amount' => 45000.00, 'date' => '2026-05-22', 'receipt_number' => 'RCT-SUP3-0526', 'recorded_by' => 2, 'created_at' => now()->subDays(40)],
            ['category' => 'Salaries', 'description' => 'Staff salaries - June 2026', 'amount' => 2800000.00, 'date' => '2026-06-28', 'receipt_number' => null, 'recorded_by' => 2, 'created_at' => now()->subDays(19)],
            ['category' => 'Transport', 'description' => 'Delivery van fuel - May 2026', 'amount' => 95000.00, 'date' => '2026-05-28', 'receipt_number' => 'RCT-TRN-0526', 'recorded_by' => 2, 'created_at' => now()->subDays(35)],
            ['category' => 'Utilities', 'description' => 'Internet service - May 2026', 'amount' => 85000.00, 'date' => '2026-05-01', 'receipt_number' => 'RCT-INT-0526', 'recorded_by' => 2, 'created_at' => now()->subDays(58)],
            ['category' => 'Training', 'description' => 'Staff continuing education - TMDA compliance workshop', 'amount' => 250000.00, 'date' => '2026-04-15', 'receipt_number' => 'RCT-TRN2-0426', 'recorded_by' => 2, 'created_at' => now()->subDays(75)],
            ['category' => 'Rent', 'description' => 'Monthly pharmacy premises rent - April 2026', 'amount' => 850000.00, 'date' => '2026-04-01', 'receipt_number' => 'RCT-RENT-0426', 'recorded_by' => 2, 'created_at' => now()->subDays(88)],
            ['category' => 'Utilities', 'description' => 'Electricity bill - TANESCO April 2026', 'amount' => 195000.00, 'date' => '2026-04-05', 'receipt_number' => 'RCT-ELEC-0426', 'recorded_by' => 2, 'created_at' => now()->subDays(87)],
            ['category' => 'Supplies', 'description' => 'Pharmacy dispensing supplies', 'amount' => 88000.00, 'date' => '2026-04-12', 'receipt_number' => 'RCT-SUP-0426', 'recorded_by' => 2, 'created_at' => now()->subDays(80)],
            ['category' => 'Marketing', 'description' => 'WhatsApp Business advertising campaign', 'amount' => 150000.00, 'date' => '2026-04-20', 'receipt_number' => 'RCT-MKT-0426', 'recorded_by' => 2, 'created_at' => now()->subDays(72)],
            ['category' => 'Salaries', 'description' => 'Staff salaries - May 2026', 'amount' => 2750000.00, 'date' => '2026-05-28', 'receipt_number' => null, 'recorded_by' => 2, 'created_at' => now()->subDays(35)],
            ['category' => 'Transport', 'description' => 'Delivery van fuel - April 2026', 'amount' => 85000.00, 'date' => '2026-04-28', 'receipt_number' => 'RCT-TRN-0426', 'recorded_by' => 2, 'created_at' => now()->subDays(65)],
            ['category' => 'Utilities', 'description' => 'Water bill - DAWASCO April 2026', 'amount' => 40000.00, 'date' => '2026-04-05', 'receipt_number' => 'RCT-WAT-0426', 'recorded_by' => 2, 'created_at' => now()->subDays(87)],
            ['category' => 'Salaries', 'description' => 'Staff salaries - April 2026', 'amount' => 2700000.00, 'date' => '2026-04-28', 'receipt_number' => null, 'recorded_by' => 2, 'created_at' => now()->subDays(65)],
            ['category' => 'Supplies', 'description' => 'Cleaning materials and waste disposal bags', 'amount' => 35000.00, 'date' => '2026-07-18', 'receipt_number' => 'RCT-CLN-0726', 'recorded_by' => 2, 'created_at' => now()->subDays(8)],
        ];

        foreach ($expenses as $expense) {
            Expense::create([
                'pharmacy_id' => 1,
                ...$expense,
            ]);
        }
    }

    private function seedDrugMovements(): void
    {
        $movements = [
            [
                'drug_id' => 1,
                'movement_type' => 'purchase',
                'quantity' => 200,
                'unit_cost' => 5.00,
                'reference_number' => 'PO-2026-001',
                'notes' => 'Restock Amoxicillin 500mg from Generic Pharma Ltd',
                'performed_by' => 3,
                'created_at' => now()->subDays(20),
            ],
            [
                'drug_id' => 1,
                'movement_type' => 'sale',
                'quantity' => -50,
                'unit_cost' => 8.50,
                'reference_number' => 'ORD-20260001',
                'notes' => 'Dispensed to Grace Hospital bulk order',
                'performed_by' => 3,
                'created_at' => now()->subDays(14),
            ],
            [
                'drug_id' => 2,
                'movement_type' => 'purchase',
                'quantity' => 500,
                'unit_cost' => 1.50,
                'reference_number' => 'PO-2026-002',
                'notes' => 'Bulk order of Paracetamol 500mg from HealthCare',
                'performed_by' => 3,
                'created_at' => now()->subDays(18),
            ],
            [
                'drug_id' => 3,
                'movement_type' => 'adjustment',
                'quantity' => -5,
                'unit_cost' => 4.00,
                'reference_number' => null,
                'notes' => 'Damaged stock write-off - 5 tablets found broken during stock count',
                'performed_by' => 3,
                'created_at' => now()->subDays(7),
            ],
            [
                'drug_id' => 7,
                'movement_type' => 'purchase',
                'quantity' => 15,
                'unit_cost' => 12.00,
                'reference_number' => 'PO-2026-004',
                'notes' => 'Emergency restock - Salbutamol inhalers running low',
                'performed_by' => 3,
                'created_at' => now()->subDays(10),
            ],
            [
                'drug_id' => 20,
                'movement_type' => 'expiry',
                'quantity' => -8,
                'unit_cost' => 4.50,
                'reference_number' => 'EXP-2026-001',
                'notes' => 'Expired Benzoyl Peroxide 5% batch removed - expiry date 2026-06-30',
                'performed_by' => 3,
                'created_at' => now()->subDays(26),
            ],
            ['drug_id' => 2, 'movement_type' => 'sale', 'quantity' => -120, 'unit_cost' => 2.50, 'reference_number' => 'ORD-20260005', 'notes' => 'Dispensed Paracetamol 500mg - hospital ward orders', 'performed_by' => 3, 'created_at' => now()->subDays(16)],
            ['drug_id' => 2, 'movement_type' => 'purchase', 'quantity' => 300, 'unit_cost' => 1.40, 'reference_number' => 'PO-2026-008', 'notes' => 'Restock Paracetamol - seasonal demand increase', 'performed_by' => 3, 'created_at' => now()->subDays(12)],
            ['drug_id' => 4, 'movement_type' => 'sale', 'quantity' => -30, 'unit_cost' => 3.00, 'reference_number' => 'ORD-20260006', 'notes' => 'Dispensed Metformin 500mg - chronic disease patients', 'performed_by' => 3, 'created_at' => now()->subDays(15)],
            ['drug_id' => 5, 'movement_type' => 'purchase', 'quantity' => 25, 'unit_cost' => 18.00, 'reference_number' => 'PO-2026-009', 'notes' => 'Ciprofloxacin 500mg restock from Generic Pharma', 'performed_by' => 3, 'created_at' => now()->subDays(13)],
            ['drug_id' => 5, 'movement_type' => 'sale', 'quantity' => -12, 'unit_cost' => 28.00, 'reference_number' => 'ORD-20260007', 'notes' => 'Dispensed Ciprofloxacin - urinary tract infection prescriptions', 'performed_by' => 3, 'created_at' => now()->subDays(9)],
            ['drug_id' => 6, 'movement_type' => 'purchase', 'quantity' => 100, 'unit_cost' => 1.20, 'reference_number' => 'PO-2026-010', 'notes' => 'Omeprazole 20mg restock', 'performed_by' => 3, 'created_at' => now()->subDays(11)],
            ['drug_id' => 6, 'movement_type' => 'sale', 'quantity' => -40, 'unit_cost' => 2.00, 'reference_number' => 'ORD-20260008', 'notes' => 'Dispensed Omeprazole - acid reflux prescriptions', 'performed_by' => 3, 'created_at' => now()->subDays(8)],
            ['drug_id' => 8, 'movement_type' => 'adjustment', 'quantity' => 3, 'unit_cost' => 2.50, 'reference_number' => null, 'notes' => 'Stock count correction - 3 boxes found in back shelf', 'performed_by' => 3, 'created_at' => now()->subDays(6)],
            ['drug_id' => 9, 'movement_type' => 'purchase', 'quantity' => 300, 'unit_cost' => 1.00, 'reference_number' => 'PO-2026-011', 'notes' => 'ORS salts restock - high demand due to cholera outbreak', 'performed_by' => 3, 'created_at' => now()->subDays(5)],
            ['drug_id' => 9, 'movement_type' => 'sale', 'quantity' => -80, 'unit_cost' => 1.50, 'reference_number' => 'ORD-20260009', 'notes' => 'Dispensed ORS sachets - community health program', 'performed_by' => 3, 'created_at' => now()->subDays(4)],
            ['drug_id' => 10, 'movement_type' => 'expiry', 'quantity' => -5, 'unit_cost' => 3.50, 'reference_number' => 'EXP-2026-002', 'notes' => 'Expired Amoxicillin syrup batch - expiry 2026-06-30', 'performed_by' => 3, 'created_at' => now()->subDays(28)],
            ['drug_id' => 11, 'movement_type' => 'purchase', 'quantity' => 50, 'unit_cost' => 4.00, 'reference_number' => 'PO-2026-012', 'notes' => 'Artemether/Lumefantrine restock for malaria season', 'performed_by' => 3, 'created_at' => now()->subDays(14)],
            ['drug_id' => 11, 'movement_type' => 'sale', 'quantity' => -25, 'unit_cost' => 6.50, 'reference_number' => 'ORD-20260010', 'notes' => 'Dispensed AL tablet packs - malaria prescriptions', 'performed_by' => 3, 'created_at' => now()->subDays(10)],
            ['drug_id' => 12, 'movement_type' => 'adjustment', 'quantity' => -2, 'unit_cost' => 15.00, 'reference_number' => null, 'notes' => 'Damaged Ibuprofen 400mg boxes during warehouse move', 'performed_by' => 3, 'created_at' => now()->subDays(3)],
            ['drug_id' => 13, 'movement_type' => 'purchase', 'quantity' => 40, 'unit_cost' => 5.50, 'reference_number' => 'PO-2026-013', 'notes' => 'Loratadine restock - allergy season demand', 'performed_by' => 3, 'created_at' => now()->subDays(7)],
            ['drug_id' => 13, 'movement_type' => 'sale', 'quantity' => -18, 'unit_cost' => 8.00, 'reference_number' => 'ORD-20260011', 'notes' => 'Dispensed Loratadine - seasonal allergy prescriptions', 'performed_by' => 3, 'created_at' => now()->subDays(5)],
            ['drug_id' => 14, 'movement_type' => 'purchase', 'quantity' => 100, 'unit_cost' => 0.80, 'reference_number' => 'PO-2026-014', 'notes' => 'Mebendazole 500mg restock - school deworming program', 'performed_by' => 3, 'created_at' => now()->subDays(9)],
            ['drug_id' => 14, 'movement_type' => 'sale', 'quantity' => -60, 'unit_cost' => 1.20, 'reference_number' => 'ORD-20260012', 'notes' => 'Dispensed Mebendazole - community health outreach', 'performed_by' => 3, 'created_at' => now()->subDays(6)],
            ['drug_id' => 15, 'movement_type' => 'purchase', 'quantity' => 30, 'unit_cost' => 8.00, 'reference_number' => 'PO-2026-015', 'notes' => 'Fluconazole 200mg restock', 'performed_by' => 3, 'created_at' => now()->subDays(10)],
            ['drug_id' => 15, 'movement_type' => 'sale', 'quantity' => -10, 'unit_cost' => 12.00, 'reference_number' => 'ORD-20260013', 'notes' => 'Dispensed Fluconazole - fungal infection prescriptions', 'performed_by' => 3, 'created_at' => now()->subDays(8)],
            ['drug_id' => 16, 'movement_type' => 'adjustment', 'quantity' => -1, 'unit_cost' => 25.00, 'reference_number' => null, 'notes' => 'Broken thermometer removed from stock', 'performed_by' => 3, 'created_at' => now()->subDays(2)],
            ['drug_id' => 17, 'movement_type' => 'purchase', 'quantity' => 50, 'unit_cost' => 3.00, 'reference_number' => 'PO-2026-016', 'notes' => 'Nystatin cream restock', 'performed_by' => 3, 'created_at' => now()->subDays(4)],
            ['drug_id' => 17, 'movement_type' => 'sale', 'quantity' => -20, 'unit_cost' => 5.00, 'reference_number' => 'ORD-20260014', 'notes' => 'Dispensed Nystatin cream - skin infection treatments', 'performed_by' => 3, 'created_at' => now()->subDays(3)],
            ['drug_id' => 18, 'movement_type' => 'purchase', 'quantity' => 20, 'unit_cost' => 7.00, 'reference_number' => 'PO-2026-017', 'notes' => 'Zinc sulphate tablets restock', 'performed_by' => 3, 'created_at' => now()->subDays(6)],
            ['drug_id' => 18, 'movement_type' => 'sale', 'quantity' => -8, 'unit_cost' => 10.00, 'reference_number' => 'ORD-20260015', 'notes' => 'Dispensed Zinc - pediatric diarrhea treatment', 'performed_by' => 3, 'created_at' => now()->subDays(5)],
            ['drug_id' => 19, 'movement_type' => 'expiry', 'quantity' => -3, 'unit_cost' => 6.00, 'reference_number' => 'EXP-2026-003', 'notes' => 'Expired Clotrimazole cream batch - expiry 2026-07-15', 'performed_by' => 3, 'created_at' => now()->subDays(12)],
            ['drug_id' => 3, 'movement_type' => 'purchase', 'quantity' => 200, 'unit_cost' => 1.80, 'reference_number' => 'PO-2026-018', 'notes' => 'Metronidazole 400mg restock', 'performed_by' => 3, 'created_at' => now()->subDays(8)],
            ['drug_id' => 3, 'movement_type' => 'sale', 'quantity' => -75, 'unit_cost' => 3.00, 'reference_number' => 'ORD-20260016', 'notes' => 'Dispensed Metronidazole - dental infection prescriptions', 'performed_by' => 3, 'created_at' => now()->subDays(4)],
        ];

        foreach ($movements as $movement) {
            DrugMovement::create([
                'pharmacy_id' => 1,
                ...$movement,
            ]);
        }
    }
}
