<?php

namespace Database\Seeders;

use App\Models\AuditLog;
use App\Models\User;
use Illuminate\Database\Seeder;

class AuditLogsSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();
        $owner = User::where('role', 'owner')->first();
        $pharmacist = User::where('role', 'pharmacist')->first();

        $logs = [
            [
                'user_id' => $admin?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Pharmacy',
                'model_id' => 1,
                'new_values' => ['pharmacy_name' => 'Mwalimu Pharmacy', 'status' => 'active'],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Drug',
                'model_id' => 1,
                'old_values' => ['quantity' => 200],
                'new_values' => ['quantity' => 150],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Order',
                'model_id' => 1,
                'new_values' => ['order_code' => 'ORD-20260001', 'total' => 1475.00],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'dispensed',
                'model_type' => 'App\\Models\\Prescription',
                'model_id' => 1,
                'new_values' => ['status' => 'dispensed'],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Pharmacy',
                'model_id' => 1,
                'old_values' => ['monthly_revenue' => 10000],
                'new_values' => ['monthly_revenue' => 12500],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $admin?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Subscription',
                'model_id' => 1,
                'old_values' => ['status' => 'pending'],
                'new_values' => ['status' => 'active'],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\DrugMovement',
                'model_id' => 1,
                'new_values' => ['movement_type' => 'purchase', 'quantity' => 200],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Expense',
                'model_id' => 1,
                'new_values' => ['category' => 'Rent', 'amount' => 850],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'dispensed',
                'model_type' => 'App\\Models\\Prescription',
                'model_id' => 2,
                'new_values' => ['status' => 'dispensed'],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Order',
                'model_id' => 2,
                'new_values' => ['order_code' => 'ORD-20260002', 'total' => 53.69],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Drug',
                'model_id' => 3,
                'old_values' => ['quantity' => 15],
                'new_values' => ['quantity' => 8],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Prescription',
                'model_id' => 3,
                'new_values' => ['prescription_code' => 'RX-20260003', 'status' => 'dispensed'],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $admin?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\User',
                'model_id' => 4,
                'new_values' => ['name' => 'Test Customer', 'role' => 'customer'],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'deleted',
                'model_type' => 'App\\Models\\Drug',
                'model_id' => 20,
                'old_values' => ['name' => 'Benzoyl Peroxide 5%', 'quantity' => 50],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Order',
                'model_id' => 3,
                'old_values' => ['order_status' => 'pending'],
                'new_values' => ['order_status' => 'dispensed'],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $admin?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Pharmacy',
                'model_id' => 1,
                'old_values' => ['is_published' => false],
                'new_values' => ['is_published' => true],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Order',
                'model_id' => 4,
                'new_values' => ['order_code' => 'ORD-20260004', 'total' => 472.00],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Drug',
                'model_id' => 7,
                'old_values' => ['quantity' => 8],
                'new_values' => ['quantity' => 3],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'dispensed',
                'model_type' => 'App\\Models\\Prescription',
                'model_id' => 4,
                'new_values' => ['status' => 'pending'],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Expense',
                'model_id' => 2,
                'new_values' => ['category' => 'Utilities', 'amount' => 120.00],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $admin?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Subscription',
                'model_id' => 1,
                'old_values' => ['plan' => 'basic'],
                'new_values' => ['plan' => 'pro'],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\DrugMovement',
                'model_id' => 2,
                'new_values' => ['movement_type' => 'sale', 'quantity' => -50],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Drug',
                'model_id' => 11,
                'old_values' => ['quantity' => 15],
                'new_values' => ['quantity' => 5],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Order',
                'model_id' => 5,
                'new_values' => ['order_code' => 'ORD-20260005', 'total' => 38.35],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $admin?->id,
                'action' => 'deleted',
                'model_type' => 'App\\Models\\DrugMovement',
                'model_id' => 1,
                'old_values' => ['movement_type' => 'adjustment'],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'dispensed',
                'model_type' => 'App\\Models\\Prescription',
                'model_id' => 5,
                'new_values' => ['status' => 'pending'],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Expense',
                'model_id' => 3,
                'new_values' => ['category' => 'Supplies', 'amount' => 45.00],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Order',
                'model_id' => 6,
                'new_values' => ['order_code' => 'ORD-20260006', 'total' => 79.06],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $admin?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\User',
                'model_id' => 3,
                'old_values' => ['is_active' => false],
                'new_values' => ['is_active' => true],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Drug',
                'model_id' => 13,
                'old_values' => ['quantity' => 100],
                'new_values' => ['quantity' => 90],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\DrugMovement',
                'model_id' => 3,
                'new_values' => ['movement_type' => 'purchase', 'quantity' => 500],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $admin?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Subscription',
                'model_id' => 2,
                'new_values' => ['plan' => 'basic', 'amount' => 49000],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\Order',
                'model_id' => 7,
                'new_values' => ['order_code' => 'ORD-20260007', 'total' => 64.90],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Expense',
                'model_id' => 4,
                'old_values' => ['amount' => 60.00],
                'new_values' => ['amount' => 65.00],
                'ip_address' => '192.168.1.101',
            ],
            [
                'user_id' => $pharmacist?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\DrugMovement',
                'model_id' => 4,
                'new_values' => ['movement_type' => 'expiry', 'quantity' => -10],
                'ip_address' => '192.168.1.102',
            ],
            [
                'user_id' => $admin?->id,
                'action' => 'updated',
                'model_type' => 'App\\Models\\Pharmacy',
                'model_id' => 1,
                'old_values' => ['monthly_revenue' => 12500],
                'new_values' => ['monthly_revenue' => 15000],
                'ip_address' => '192.168.1.100',
            ],
            [
                'user_id' => $owner?->id,
                'action' => 'created',
                'model_type' => 'App\\Models\\DrugMovement',
                'model_id' => 5,
                'new_values' => ['movement_type' => 'adjustment', 'quantity' => -5],
                'ip_address' => '192.168.1.101',
            ],
        ];

        foreach ($logs as $log) {
            AuditLog::create([
                'pharmacy_id' => 1,
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'created_at' => now()->subDays(rand(0, 14)),
                ...$log,
            ]);
        }
    }
}
