<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChatSeeder extends Seeder
{
    public function run(): void
    {
        $messages = [
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'Hello! I need to check if you have Amoxicillin 500mg and Paracetamol 500mg in stock. Can you help?',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subHours(5),
                'updated_at' => now()->subHours(5),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'Hi! Yes, we have both in stock. Amoxicillin 500mg is TZS 8.50 per capsule and Paracetamol 500mg is TZS 3.00 per tablet. How many do you need?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subHours(4),
                'updated_at' => now()->subHours(4),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'Great! I need 20 capsules of Amoxicillin and 10 tablets of Paracetamol. Do you offer delivery?',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subHours(3),
                'updated_at' => now()->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'Absolutely! We offer free delivery within Dar es Salaam. Delivery usually takes 2-4 hours. We also have same-day delivery for orders placed before 6pm.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'Perfect! I would like to place an order: 20x Amoxicillin 500mg and 10x Paracetamol 500mg. Please deliver to my address.',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subHour(),
                'updated_at' => now()->subHour(),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'Order confirmed! Your total is TZS 200.00 (Amoxicillin: 20x8.50 = 170.00, Paracetamol: 10x3.00 = 30.00). We will deliver within 3 hours. Thank you for your order!',
                'message_type' => 'text',
                'is_read' => false,
                'created_at' => now()->subMinutes(30),
                'updated_at' => now()->subMinutes(30),
            ],
            // ── Additional messages ─────────────────────────────────────────
            [
                'pharmacy_id' => 1,
                'sender_id' => 5,
                'receiver_id' => 3,
                'message' => 'Jambo, una Metformin 500mg? Naitaji vidongi 60 kwa mgonjwa wangu.',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(1)->subHours(6),
                'updated_at' => now()->subDays(1)->subHours(6),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 5,
                'message' => 'Habari! Ndiyo, tuna Metformin 500mg. Bei ni TZS 5.50 kwa kila kipande. Je, unahitaji dawa nyingine pia?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(1)->subHours(5),
                'updated_at' => now()->subDays(1)->subHours(5),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 5,
                'receiver_id' => 3,
                'message' => 'Ndiyo, nina pia Amlodipine 5mg na Omeprazole 20mg. Nipe vitu vyote pamoja.',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(1)->subHours(4),
                'updated_at' => now()->subDays(1)->subHours(4),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 5,
                'message' => 'Sawa! Metformin 60x5.50 = TZS 330, Amlodipine 30x4.00 = TZS 120, Omeprazole 28x6.00 = TZS 168. Jumla = TZS 618. Je, utalipa kwa njia gani?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(1)->subHours(3),
                'updated_at' => now()->subDays(1)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 5,
                'receiver_id' => 3,
                'message' => 'Nitapitia M-Pesa. Namba yangu ni 0754321987. Tafadhali nitumie order number kwa urahisi.',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(1)->subHours(2),
                'updated_at' => now()->subDays(1)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 5,
                'message' => 'Imekamilika! Order #ORD-20260012 imeundwa. Lipa kupitia M-Pesa na namba ya malipo. Tutatuma dawa ndani ya masaa 2.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(1)->subHour(),
                'updated_at' => now()->subDays(1)->subHour(),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 2,
                'receiver_id' => 3,
                'message' => 'How is the stock count going? We need to finalize the monthly inventory report by end of day.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(2)->subHours(3),
                'updated_at' => now()->subDays(2)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 2,
                'message' => 'Almost done! I have counted the fast-moving drugs. Still working on the controlled substances section. Should be ready by 3pm.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(2)->subHours(2),
                'updated_at' => now()->subDays(2)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 2,
                'receiver_id' => 3,
                'message' => 'Good. Also check the expiry dates on the Paracetamol batch EXP-202607. We need to flag any items expiring within 3 months.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(2)->subHours(1),
                'updated_at' => now()->subDays(2)->subHours(1),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 2,
                'message' => 'Noted! I found 12 boxes of Paracetamol expiring August 2026. I will move them to the clearance shelf and update the system.',
                'message_type' => 'text',
                'is_read' => false,
                'created_at' => now()->subDays(2)->subMinutes(30),
                'updated_at' => now()->subDays(2)->subMinutes(30),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'Hi again! My mother also needs Artemether-Lumefantrine for malaria. Do you have it in the 20/120mg dosage?',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(3)->subHours(4),
                'updated_at' => now()->subDays(3)->subHours(4),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'Yes, we have Coartem (Artemether-Lumefantrine) 20/120mg. A course of 24 tablets costs TZS 3,500. We also have the 80/480mg strength if needed.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(3)->subHours(3),
                'updated_at' => now()->subDays(3)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'The 20/120mg is fine. She weighs about 45kg. Please add it to my previous order and deliver together.',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(3)->subHours(2),
                'updated_at' => now()->subDays(3)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'Updated! New total including Coartem is TZS 3,700. Delivery confirmed for this afternoon. Our rider will call you on arrival.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(3)->subHours(1),
                'updated_at' => now()->subDays(3)->subHours(1),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 5,
                'receiver_id' => 3,
                'message' => 'Dawa zimenifika, asante sana! Quality ni nzuri. Nitakuwa naika order nyingine wiki ijayo.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(4)->subHours(2),
                'updated_at' => now()->subDays(4)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 5,
                'message' => 'Karibu tena! Furaha ya kukuhudumia. Ukihitaji dawa yoyote, tafadhali tujulishe mapema ili tuwekelee order kwa wakati.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(4)->subHour(),
                'updated_at' => now()->subDays(4)->subHour(),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 2,
                'receiver_id' => 4,
                'message' => 'Hello! This is the pharmacy manager. Thank you for your recent orders. As a valued customer, you are eligible for our loyalty discount program.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(5)->subHours(5),
                'updated_at' => now()->subDays(5)->subHours(5),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 2,
                'message' => 'That sounds great! What are the benefits of the loyalty program?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(5)->subHours(4),
                'updated_at' => now()->subDays(5)->subHours(4),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 2,
                'receiver_id' => 4,
                'message' => 'You get 5% off on orders above TZS 10,000, free delivery on all orders, and priority access to new products. Would you like to join?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(5)->subHours(3),
                'updated_at' => now()->subDays(5)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 2,
                'message' => 'Yes please! Sign me up. I order regularly so this will save me a lot.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(5)->subHours(2),
                'updated_at' => now()->subDays(5)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 2,
                'receiver_id' => 4,
                'message' => 'You are now enrolled! Your loyalty ID is LOYAL-0047. You can use this code when placing future orders. Welcome aboard!',
                'message_type' => 'text',
                'is_read' => false,
                'created_at' => now()->subDays(5)->subHour(),
                'updated_at' => now()->subDays(5)->subHour(),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 5,
                'message' => 'Habari! Mgonjwa wako aliuliza kuhusu dawa za msimu wa mvua. Je, unahitaji Quinine au ORS?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(6)->subHours(3),
                'updated_at' => now()->subDays(6)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 5,
                'receiver_id' => 3,
                'message' => 'Ndiyo, tafadhali niletee ORS sacheti 10 na Zinc tablets 30. Hii ni kwa ajili ya kuzuia upungufu wa maji mwilini.',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(6)->subHours(2),
                'updated_at' => now()->subDays(6)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 5,
                'message' => 'Sawa. ORS 10xTZS 500 = TZS 5,000, Zinc 30xTZS 200 = TZS 6,000. Jumla = TZS 11,000. Nitatuma leo jioni.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(6)->subHour(),
                'updated_at' => now()->subDays(6)->subHour(),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'Can you check if I have any pending prescriptions? My doctor sent one last week for Cetirizine.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(7)->subHours(2),
                'updated_at' => now()->subDays(7)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'Let me check... Yes, Dr. Mwakio sent a prescription for Cetirizine 10mg, 30 tablets. It is ready for pickup or delivery. Shall I send it?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(7)->subHour(),
                'updated_at' => now()->subDays(7)->subHour(),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'Yes, please add it to my next delivery. Also, is Cetirizine covered by NHIF?',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(8)->subHours(4),
                'updated_at' => now()->subDays(8)->subHours(4),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'Cetirizine is not covered by NHIF unfortunately, but it is very affordable at TZS 2,500 for 30 tablets. I have added it to your pending order.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(8)->subHours(3),
                'updated_at' => now()->subDays(8)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 2,
                'receiver_id' => 3,
                'message' => 'Reminder: The new batch of vaccines arrives tomorrow morning. Please clear space in the cold storage unit and prepare the temperature log.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(9)->subHours(6),
                'updated_at' => now()->subDays(9)->subHours(6),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 2,
                'message' => 'Understood! I will prepare the cold chain documentation and verify the thermometer calibration tonight. How many doses are we expecting?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(9)->subHours(5),
                'updated_at' => now()->subDays(9)->subHours(5),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 2,
                'receiver_id' => 3,
                'message' => '200 doses of Pentavalent vaccine and 150 doses of Oral Polio Vaccine. Handle with extreme care - these are WHO-supplied.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(9)->subHours(4),
                'updated_at' => now()->subDays(9)->subHours(4),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 2,
                'message' => 'Noted. I will ensure proper documentation per WHO cold chain guidelines. The temperature has been stable at 2-8 degrees Celsius.',
                'message_type' => 'text',
                'is_read' => false,
                'created_at' => now()->subDays(9)->subHours(3),
                'updated_at' => now()->subDays(9)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 5,
                'receiver_id' => 3,
                'message' => 'Je, mna dawa za mtoto wa miezi 6? Ninahitaji vitamin drops na cough syrup.',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(10)->subHours(5),
                'updated_at' => now()->subDays(10)->subHours(5),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 5,
                'message' => 'Ndiyo! Vitafya Vitamin D drops ni TZS 8,000 na Benylin Cough Syrup (for infants) ni TZS 4,500. Je, unahitaji pia Thermometer ya mtoto?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(10)->subHours(4),
                'updated_at' => now()->subDays(10)->subHours(4),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 5,
                'receiver_id' => 3,
                'message' => 'Vitamin drops pekee kwa sasa. Nitachukua pia Panadol Baby. Ni gharamu gani yote?',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(10)->subHours(3),
                'updated_at' => now()->subDays(10)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 5,
                'message' => 'Vitamin drops TZS 8,000 + Benylin Infant TZS 4,500 + Panadol Baby TZS 3,500 = Total TZS 16,000. Free delivery! Order imethibitishwa.',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(10)->subHours(2),
                'updated_at' => now()->subDays(10)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'Hi, I want to know about your wholesale prices for Amoxicillin. I run a small clinic and need about 200 capsules per month.',
                'message_type' => 'order_inquiry',
                'is_read' => true,
                'created_at' => now()->subDays(11)->subHours(3),
                'updated_at' => now()->subDays(11)->subHours(3),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'For wholesale orders of 200+ capsules, we offer a 10% discount. That brings the price from TZS 8.50 to TZS 7.65 per capsule. Total: TZS 1,530. Shall I prepare a standing monthly order?',
                'message_type' => 'text',
                'is_read' => true,
                'created_at' => now()->subDays(11)->subHours(2),
                'updated_at' => now()->subDays(11)->subHours(2),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 4,
                'receiver_id' => 3,
                'message' => 'That is a great deal! Yes, please set up a monthly standing order for 200 capsules. Can you also include Paracetamol 500mg wholesale?',
                'message_type' => 'order_inquiry',
                'is_read' => false,
                'created_at' => now()->subDays(11)->subHour(),
                'updated_at' => now()->subDays(11)->subHour(),
            ],
            [
                'pharmacy_id' => 1,
                'sender_id' => 3,
                'receiver_id' => 4,
                'message' => 'Absolutely! Paracetamol 500mg wholesale: 300 tablets at TZS 2.70 each = TZS 810. Combined monthly order: TZS 2,340. I will send you the standing order contract.',
                'message_type' => 'text',
                'is_read' => false,
                'created_at' => now()->subDays(12)->subHours(6),
                'updated_at' => now()->subDays(12)->subHours(6),
            ],
        ];

        DB::table('messages')->insert($messages);
    }
}
