<?php

namespace Database\Seeders;

use App\Models\Notification;
use App\Models\User;
use Illuminate\Database\Seeder;

class NotificationsSeeder extends Seeder
{
    public function run(): void
    {
        $owner = User::where('role', 'owner')->first();
        $pharmacist = User::where('role', 'pharmacist')->first();

        $notifications = [
            [
                'user_id' => $owner?->id,
                'title' => 'New Order Received',
                'message' => 'Order ORD-20260001 from Grace Hospital has been placed.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/orders',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Low Stock Alert',
                'message' => 'Metformin 850mg is below reorder level. Only 8 units remaining.',
                'type' => 'warning',
                'is_read' => false,
                'link' => '/drugs',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Subscription Renewed',
                'message' => 'Your subscription has been renewed for 12 months.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/settings',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Prescription Pending',
                'message' => 'RX-20260004 needs to be reviewed and dispensed.',
                'type' => 'info',
                'is_read' => false,
                'link' => '/prescriptions',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Delivery Assigned',
                'message' => 'You have been assigned delivery DLV-0004.',
                'type' => 'info',
                'is_read' => false,
                'link' => '/deliveries',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Expiry Warning',
                'message' => 'Omeprazole 20mg (BATCH-OMP-005) expires on 2026-07-30.',
                'type' => 'danger',
                'is_read' => false,
                'link' => '/expiring-soon',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Monthly Revenue Report',
                'message' => 'July revenue report is ready. Total revenue: TZS 12,500.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/reports',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'New Customer Added',
                'message' => 'Carol Banda has been registered as a new customer.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/customers',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'New Order Received',
                'message' => 'Order ORD-20260002 from Alice Mwamba has been placed.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/orders',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Low Stock Alert',
                'message' => 'Salbutamol Inhaler is critically low. Only 3 vials remaining.',
                'type' => 'danger',
                'is_read' => false,
                'link' => '/drugs',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Prescription Dispensed',
                'message' => 'RX-20260001 has been successfully dispensed to Bob Phiri.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/prescriptions',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Delivery Completed',
                'message' => 'Delivery DLV-0001 to Grace Hospital has been completed.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/deliveries',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Payment Received',
                'message' => 'Payment of TZS 472.00 received from City Clinic for order ORD-20260004.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/orders',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'New Order Received',
                'message' => 'Order ORD-20260005 from Carol Banda has been placed.',
                'type' => 'info',
                'is_read' => false,
                'link' => '/orders',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Expiry Warning',
                'message' => 'Benzoyl Peroxide 5% (BATCH-BPO-020) expired on 2026-06-30. Please remove from inventory.',
                'type' => 'danger',
                'is_read' => false,
                'link' => '/expiring-soon',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Subscription Expiring',
                'message' => 'Your trial subscription expires in 3 days. Upgrade to continue.',
                'type' => 'warning',
                'is_read' => false,
                'link' => '/settings/subscription',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Delivery Failed',
                'message' => 'Delivery DLV-0009 to Bob Phiri could not be completed. Customer not available.',
                'type' => 'danger',
                'is_read' => false,
                'link' => '/deliveries',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'New Order Received',
                'message' => 'Order ORD-20260006 from Alice Mwamba has been placed.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/orders',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Stock Adjustment',
                'message' => '5 units of Metformin 850mg have been written off due to damage.',
                'type' => 'warning',
                'is_read' => true,
                'link' => '/drugs',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Prescription Pending',
                'message' => 'RX-20260005 needs to be reviewed and dispensed for Alice Mwamba.',
                'type' => 'info',
                'is_read' => false,
                'link' => '/prescriptions',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Monthly Expenses Summary',
                'message' => 'Total expenses for July: TZS 850.00. View detailed breakdown.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/expenses',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Low Stock Alert',
                'message' => 'Azithromycin 250mg is below reorder level. Only 5 units remaining.',
                'type' => 'warning',
                'is_read' => false,
                'link' => '/drugs',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Delivery Completed',
                'message' => 'Delivery DLV-0002 to Alice Mwamba has been completed successfully.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/deliveries',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'New Order Received',
                'message' => 'Order ORD-20260007 from Bob Phiri has been placed.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/orders',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'License Renewal Reminder',
                'message' => 'Your pharmacy license PHA-TZ-2024-00156 is valid until 2027-12-31.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/settings',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'New Order Received',
                'message' => 'Order ORD-20260008 from Grace Hospital has been placed.',
                'type' => 'info',
                'is_read' => false,
                'link' => '/orders',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Revenue Milestone',
                'message' => 'Congratulations! Your pharmacy has reached TZS 1,000,000 in total sales.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/reports',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Drug Price Update',
                'message' => 'Selling price of Amoxicillin 500mg updated from TZS 7.50 to TZS 8.50.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/drugs',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Delivery Assigned',
                'message' => 'You have been assigned delivery DLV-0015 to Baraka Clinic.',
                'type' => 'info',
                'is_read' => false,
                'link' => '/deliveries',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'New Order Received',
                'message' => 'Order ORD-20260009 from City Clinic has been placed.',
                'type' => 'info',
                'is_read' => false,
                'link' => '/orders',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Expiry Warning',
                'message' => 'Multivitamin Syrup (BATCH-MVS-019) expires on 2026-09-15. Consider running a promotion.',
                'type' => 'warning',
                'is_read' => false,
                'link' => '/expiring-soon',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Delivery Completed',
                'message' => 'Delivery DLV-0003 to City Clinic has been completed.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/deliveries',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'System Maintenance Notice',
                'message' => 'Scheduled maintenance on August 1, 2026 from 02:00 to 04:00 EAT.',
                'type' => 'warning',
                'is_read' => true,
                'link' => '/notifications',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'New Order Received',
                'message' => 'Order ORD-20260010 from Carol Banda has been placed.',
                'type' => 'info',
                'is_read' => false,
                'link' => '/orders',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'Payment Received',
                'message' => 'Cash payment of TZS 38.35 received for order ORD-20260005.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/orders',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Inventory Count Reminder',
                'message' => 'Weekly inventory count is due. Please verify stock levels.',
                'type' => 'warning',
                'is_read' => false,
                'link' => '/drugs',
            ],
            [
                'user_id' => $pharmacist?->id,
                'title' => 'New Customer Added',
                'message' => 'Bob Phiri has been registered as a new customer.',
                'type' => 'info',
                'is_read' => true,
                'link' => '/customers',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Delivery Failed',
                'message' => 'Delivery DLV-0019 to Furaha Pharmacy failed. Customer address could not be located.',
                'type' => 'danger',
                'is_read' => false,
                'link' => '/deliveries',
            ],
            [
                'user_id' => $owner?->id,
                'title' => 'Monthly Revenue Report',
                'message' => 'June revenue report is ready. Total revenue: TZS 3,875,000.',
                'type' => 'success',
                'is_read' => true,
                'link' => '/reports',
            ],
        ];

        foreach ($notifications as $notification) {
            Notification::create([
                'pharmacy_id' => 1,
                'created_at' => now()->subDays(rand(0, 14)),
                ...$notification,
            ]);
        }
    }
}
