<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegulatorySeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        $this->seedPharmacyLicenses();
        $this->seedRegulatoryReports();

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }

    private function seedPharmacyLicenses(): void
    {
        $now = now();

        $records = [
            [
                'pharmacy_id' => 1,
                'license_type' => 'pharmacy_license',
                'license_number' => 'PHA-TZ-2024-00156',
                'issue_date' => '2024-01-15',
                'expiry_date' => '2027-12-31',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 90,
                'notes' => 'Primary pharmacy practice license issued under the Tanzania Medicines and Medical Devices Authority Act, Cap 200. Authorizes dispensing of prescription and over-the-counter medications.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'drug_dealer_license',
                'license_number' => 'CDL-TZ-2024-00089',
                'issue_date' => '2024-03-01',
                'expiry_date' => '2027-06-30',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 90,
                'notes' => 'Controlled substances dealer license authorizing storage, handling and dispensing of Category II and III controlled drugs under the Drugs and Cosmetics Act, Cap 92.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'business_license',
                'license_number' => 'BL-ILALA-2025-00342',
                'issue_date' => '2025-01-10',
                'expiry_date' => '2026-12-31',
                'issuing_authority' => 'Ilala Municipal Council',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 60,
                'notes' => 'Annual business operating license issued by the Ilala Municipal Council for pharmaceutical retail operations.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'fire_safety_certificate',
                'license_number' => 'FSC-DSM-2025-00781',
                'issue_date' => '2025-06-15',
                'expiry_date' => '2026-06-14',
                'issuing_authority' => 'Tanzania Fire and Rescue Force',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 30,
                'notes' => 'Fire safety compliance certificate for pharmaceutical storage premises. Must be renewed annually.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'tax_clearance_certificate',
                'license_number' => 'TCC-TRA-2026-00123',
                'issue_date' => '2026-01-01',
                'expiry_date' => '2026-12-31',
                'issuing_authority' => 'Tanzania Revenue Authority (TRA)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 60,
                'notes' => 'Annual tax clearance certificate confirming compliance with VAT and income tax obligations.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'premises_inspection_certificate',
                'license_number' => 'PIC-TMDA-2026-00045',
                'issue_date' => '2026-03-20',
                'expiry_date' => '2027-03-19',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 90,
                'notes' => 'Annual premises inspection certificate confirming compliance with Good Pharmacy Practice (GPP) standards.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'pharmacist_practice_license',
                'license_number' => 'PPL-TNC-2024-0198',
                'issue_date' => '2024-08-01',
                'expiry_date' => '2027-07-31',
                'issuing_authority' => 'Tanzania National Council of Pharmacist',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 90,
                'notes' => 'Individual pharmacist practice license for Dr. Amina Juma (Pharmacist In-Charge).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'controlled_substances_storage_permit',
                'license_number' => 'CSSP-TMDA-2025-00234',
                'issue_date' => '2025-04-10',
                'expiry_date' => '2026-04-09',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 60,
                'notes' => 'Permit for secure storage of controlled substances including Schedule II-V drugs. Requires annual renewal.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'cold_chain_compliance_certificate',
                'license_number' => 'CCC-TMDA-2026-00067',
                'issue_date' => '2026-02-15',
                'expiry_date' => '2027-02-14',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 90,
                'notes' => 'Cold chain compliance certificate for proper storage of temperature-sensitive medications and vaccines.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'waste_disposal_permit',
                'license_number' => 'WDP-NEMC-2025-00189',
                'issue_date' => '2025-09-01',
                'expiry_date' => '2026-08-31',
                'issuing_authority' => 'National Environment Management Council (NEMC)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 60,
                'notes' => 'Permit for proper disposal of pharmaceutical waste and expired medications per Environmental Management Act.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'signage_permit',
                'license_number' => 'SP-ILALA-2026-00112',
                'issue_date' => '2026-01-20',
                'expiry_date' => '2026-12-31',
                'issuing_authority' => 'Ilala Municipal Council',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 30,
                'notes' => 'Permit for pharmacy signage display as per Ilala Municipal Council bylaws.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'insurance_liability_certificate',
                'license_number' => 'ILC-DSL-2026-00456',
                'issue_date' => '2026-07-01',
                'expiry_date' => '2026-09-30',
                'issuing_authority' => 'Diamond Trust Insurance Company',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 30,
                'notes' => 'Professional liability insurance covering pharmaceutical dispensing errors for Q3 2026.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'pharmacy_license',
                'license_number' => 'PHA-TZ-2023-00098',
                'issue_date' => '2023-06-01',
                'expiry_date' => '2025-05-31',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 90,
                'notes' => 'Previous pharmacy practice license superseded by PHA-TZ-2024-00156. Retained for records.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'drug_dealer_license',
                'license_number' => 'CDL-TZ-2023-00056',
                'issue_date' => '2023-04-15',
                'expiry_date' => '2024-03-31',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 90,
                'notes' => 'Previous controlled substances dealer license superseded by CDL-TZ-2024-00089.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'business_license',
                'license_number' => 'BL-ILALA-2024-00287',
                'issue_date' => '2024-01-05',
                'expiry_date' => '2024-12-31',
                'issuing_authority' => 'Ilala Municipal Council',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 60,
                'notes' => 'Previous annual business license. Renewed as BL-ILALA-2025-00342.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'premises_inspection_certificate',
                'license_number' => 'PIC-TMDA-2024-00023',
                'issue_date' => '2024-05-10',
                'expiry_date' => '2025-05-09',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 90,
                'notes' => 'Previous premises inspection certificate. Renewed after satisfactory compliance review.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'pharmacy_license',
                'license_number' => 'PHA-TZ-2025-00201',
                'issue_date' => '2025-01-15',
                'expiry_date' => '2026-01-14',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 90,
                'notes' => 'Interim pharmacy license issued during renewal process. Valid for 12 months.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'controlled_substances_storage_permit',
                'license_number' => 'CSSP-TMDA-2024-00178',
                'issue_date' => '2024-04-01',
                'expiry_date' => '2025-03-31',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 60,
                'notes' => 'Previous controlled substances storage permit. Renewed as CSSP-TMDA-2025-00234.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'cold_chain_compliance_certificate',
                'license_number' => 'CCC-TMDA-2024-00034',
                'issue_date' => '2024-02-01',
                'expiry_date' => '2025-01-31',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 90,
                'notes' => 'Previous cold chain compliance certificate. Renewed after temperature monitoring audit.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'tax_clearance_certificate',
                'license_number' => 'TCC-TRA-2025-00089',
                'issue_date' => '2025-01-01',
                'expiry_date' => '2025-12-31',
                'issuing_authority' => 'Tanzania Revenue Authority (TRA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 60,
                'notes' => 'Previous year tax clearance certificate. Renewed as TCC-TRA-2026-00123.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'waste_disposal_permit',
                'license_number' => 'WDP-NEMC-2024-00134',
                'issue_date' => '2024-09-01',
                'expiry_date' => '2025-08-31',
                'issuing_authority' => 'National Environment Management Council (NEMC)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 60,
                'notes' => 'Previous waste disposal permit. Renewed as WDP-NEMC-2025-00189.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'fire_safety_certificate',
                'license_number' => 'FSC-DSM-2024-00612',
                'issue_date' => '2024-06-01',
                'expiry_date' => '2025-05-31',
                'issuing_authority' => 'Tanzania Fire and Rescue Force',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 30,
                'notes' => 'Previous fire safety certificate. Renewed as FSC-DSM-2025-00781.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'pharmacy_license',
                'license_number' => 'PHA-TZ-2026-00301',
                'issue_date' => '2026-01-15',
                'expiry_date' => '2028-12-31',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 90,
                'notes' => 'Current primary pharmacy practice license. Two-year validity period.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'drug_dealer_license',
                'license_number' => 'CDL-TZ-2025-00156',
                'issue_date' => '2025-07-01',
                'expiry_date' => '2028-06-30',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 90,
                'notes' => 'Current controlled substances dealer license with three-year validity.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'pharmacist_practice_license',
                'license_number' => 'PPL-TNC-2023-0156',
                'issue_date' => '2023-08-01',
                'expiry_date' => '2026-07-31',
                'issuing_authority' => 'Tanzania National Council of Pharmacist',
                'document_path' => null,
                'status' => 'pending_renewal',
                'renewal_reminder_days' => 90,
                'notes' => 'Pharmacist practice license for Dr. Amina Juma expiring soon. Renewal application submitted.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'signage_permit',
                'license_number' => 'SP-ILALA-2025-00098',
                'issue_date' => '2025-01-15',
                'expiry_date' => '2025-12-31',
                'issuing_authority' => 'Ilala Municipal Council',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 30,
                'notes' => 'Previous signage permit. Renewed as SP-ILALA-2026-00112.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'insurance_liability_certificate',
                'license_number' => 'ILC-DSL-2026-00389',
                'issue_date' => '2026-04-01',
                'expiry_date' => '2026-06-30',
                'issuing_authority' => 'Diamond Trust Insurance Company',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 30,
                'notes' => 'Previous quarterly liability insurance certificate. Renewed for Q3 2026.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'controlled_substances_storage_permit',
                'license_number' => 'CSSP-TMDA-2026-00312',
                'issue_date' => '2026-04-10',
                'expiry_date' => '2027-04-09',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 60,
                'notes' => 'Current controlled substances storage permit with updated security requirements.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'premises_inspection_certificate',
                'license_number' => 'PIC-TMDA-2025-00056',
                'issue_date' => '2025-06-01',
                'expiry_date' => '2026-05-31',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 90,
                'notes' => 'Previous premises inspection certificate. Renewed as PIC-TMDA-2026-00045.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'waste_disposal_permit',
                'license_number' => 'WDP-NEMC-2026-00234',
                'issue_date' => '2026-09-01',
                'expiry_date' => '2027-08-31',
                'issuing_authority' => 'National Environment Management Council (NEMC)',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 60,
                'notes' => 'Current waste disposal permit with updated pharmaceutical waste handling procedures.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'cold_chain_compliance_certificate',
                'license_number' => 'CCC-TMDA-2025-00089',
                'issue_date' => '2025-02-15',
                'expiry_date' => '2026-02-14',
                'issuing_authority' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'document_path' => null,
                'status' => 'expired',
                'renewal_reminder_days' => 90,
                'notes' => 'Previous cold chain compliance certificate. Renewed as CCC-TMDA-2026-00067.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'license_type' => 'fire_safety_certificate',
                'license_number' => 'FSC-DSM-2026-00892',
                'issue_date' => '2026-06-15',
                'expiry_date' => '2027-06-14',
                'issuing_authority' => 'Tanzania Fire and Rescue Force',
                'document_path' => null,
                'status' => 'active',
                'renewal_reminder_days' => 30,
                'notes' => 'Current fire safety compliance certificate after annual inspection passed.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('pharmacy_licenses')->insert($records);
    }

    private function seedRegulatoryReports(): void
    {
        $now = now();

        $records = [
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 6,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'total_prescriptions' => 284,
                    'total_otc_sales' => 412,
                    'total_revenue' => 3875000.00,
                    'total_discounts' => 125000.00,
                    'net_revenue' => 3750000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 156, 'revenue' => 892500.00],
                        'antihypertensives' => ['units_sold' => 134, 'revenue' => 675000.00],
                        'analgesics' => ['units_sold' => 198, 'revenue' => 562500.00],
                    ],
                    'expired_returns_count' => 4,
                    'expired_returns_value' => 36000.00,
                    'compliance_notes' => 'All prescriptions verified by licensed pharmacist. Cold chain records maintained.',
                ]),
                'status' => 'submitted',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2026-07-05 09:30:00',
                'approved_by' => null,
                'notes' => 'Monthly pharmacy sales report for June 2026 submitted to TMDA as per Regulatory Guidelines for Pharmaceutical Premises.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'control_substance',
                'report_period_month' => 6,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'reporting_quarter' => 'Q2-2026',
                    'controlled_schedule_ii' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'controlled_schedule_iii' => [
                        'items' => [
                            ['drug_name' => 'Amoxicillin 500mg', 'received' => 200, 'dispensed' => 135, 'balance' => 65],
                            ['drug_name' => 'Azithromycin 250mg', 'received' => 50, 'dispensed' => 38, 'balance' => 12],
                        ],
                        'total_received' => 250,
                        'total_dispensed' => 173,
                        'balance_stock' => 77,
                    ],
                    'controlled_schedule_iv' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'discrepancies' => [],
                    'auditor_name' => 'Rehema Mwangaza',
                    'auditor_designation' => 'Pharmacist In-Charge',
                ]),
                'status' => 'submitted',
                'submitted_to' => 'Tanzania Cooperative Drug Authority (TCDA)',
                'submitted_at' => '2026-07-10 14:00:00',
                'approved_by' => null,
                'notes' => 'Quarterly controlled substances usage and inventory report for Q2 2026 (April-June) submitted to TCDA. No discrepancies found during internal audit.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 7,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'total_prescriptions' => 182,
                    'total_otc_sales' => 267,
                    'total_revenue' => 2450000.00,
                    'total_discounts' => 78000.00,
                    'net_revenue' => 2372000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 98, 'revenue' => 560000.00],
                        'analgesics' => ['units_sold' => 124, 'revenue' => 350000.00],
                        'antimalarials' => ['units_sold' => 87, 'revenue' => 290000.00],
                    ],
                    'expired_returns_count' => 2,
                    'expired_returns_value' => 18000.00,
                    'compliance_notes' => 'Monthly data still in progress. Report will be finalized by end of month.',
                ]),
                'status' => 'draft',
                'submitted_to' => null,
                'submitted_at' => null,
                'approved_by' => null,
                'notes' => 'Draft monthly sales report for July 2026. Data is being compiled from POS records. Expected submission to TMDA by 5th August 2026.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 5,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'total_prescriptions' => 268,
                    'total_otc_sales' => 389,
                    'total_revenue' => 3650000.00,
                    'total_discounts' => 110000.00,
                    'net_revenue' => 3540000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 142, 'revenue' => 820000.00],
                        'analgesics' => ['units_sold' => 187, 'revenue' => 525000.00],
                        'cardiovascular' => ['units_sold' => 112, 'revenue' => 612000.00],
                    ],
                    'expired_returns_count' => 3,
                    'expired_returns_value' => 27000.00,
                    'compliance_notes' => 'All prescriptions verified. Controlled substance log up to date.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2026-06-05 10:15:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for May 2026. Approved by TMDA regional inspector on 2026-06-12.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 4,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'total_prescriptions' => 251,
                    'total_otc_sales' => 372,
                    'total_revenue' => 3420000.00,
                    'total_discounts' => 95000.00,
                    'net_revenue' => 3325000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 138, 'revenue' => 795000.00],
                        'analgesics' => ['units_sold' => 175, 'revenue' => 498000.00],
                        'gastrointestinal' => ['units_sold' => 89, 'revenue' => 345000.00],
                    ],
                    'expired_returns_count' => 5,
                    'expired_returns_value' => 42000.00,
                    'compliance_notes' => 'Increased expired returns due to seasonal stock rotation. All handled per SOP.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2026-05-04 08:45:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for April 2026. Approved with minor observations on expiry management.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 3,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'total_prescriptions' => 235,
                    'total_otc_sales' => 345,
                    'total_revenue' => 3180000.00,
                    'total_discounts' => 88000.00,
                    'net_revenue' => 3092000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 128, 'revenue' => 738000.00],
                        'analgesics' => ['units_sold' => 162, 'revenue' => 462000.00],
                        'vitamins' => ['units_sold' => 145, 'revenue' => 415000.00],
                    ],
                    'expired_returns_count' => 2,
                    'expired_returns_value' => 15000.00,
                    'compliance_notes' => 'Compliant month. Zero discrepancies in controlled substance records.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2026-04-05 09:00:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for March 2026. Clean approval.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'control_substance',
                'report_period_month' => 3,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'reporting_quarter' => 'Q1-2026',
                    'controlled_schedule_ii' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'controlled_schedule_iii' => [
                        'items' => [
                            ['drug_name' => 'Amoxicillin 500mg', 'received' => 180, 'dispensed' => 162, 'balance' => 18],
                            ['drug_name' => 'Azithromycin 250mg', 'received' => 40, 'dispensed' => 35, 'balance' => 5],
                        ],
                        'total_received' => 220,
                        'total_dispensed' => 197,
                        'balance_stock' => 23,
                    ],
                    'controlled_schedule_iv' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'discrepancies' => [],
                    'auditor_name' => 'Rehema Mwangaza',
                    'auditor_designation' => 'Pharmacist In-Charge',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Cooperative Drug Authority (TCDA)',
                'submitted_at' => '2026-04-10 11:30:00',
                'approved_by' => 'Mr. Festo Mcha',
                'notes' => 'Quarterly controlled substances report for Q1 2026. Approved with commendation for accurate record keeping.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 2,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'total_prescriptions' => 218,
                    'total_otc_sales' => 320,
                    'total_revenue' => 2950000.00,
                    'total_discounts' => 75000.00,
                    'net_revenue' => 2875000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 118, 'revenue' => 682000.00],
                        'analgesics' => ['units_sold' => 148, 'revenue' => 422000.00],
                        'cardiovascular' => ['units_sold' => 98, 'revenue' => 535000.00],
                    ],
                    'expired_returns_count' => 1,
                    'expired_returns_value' => 8500.00,
                    'compliance_notes' => 'Low expiry returns. Strong compliance across all categories.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2026-03-05 10:00:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for February 2026.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 1,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'total_prescriptions' => 195,
                    'total_otc_sales' => 298,
                    'total_revenue' => 2720000.00,
                    'total_discounts' => 68000.00,
                    'net_revenue' => 2652000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 105, 'revenue' => 612000.00],
                        'analgesics' => ['units_sold' => 132, 'revenue' => 378000.00],
                        'antimalarials' => ['units_sold' => 92, 'revenue' => 318000.00],
                    ],
                    'expired_returns_count' => 3,
                    'expired_returns_value' => 24000.00,
                    'compliance_notes' => 'New year stock adjustments completed. All records reconciled.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2026-02-04 08:30:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for January 2026.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'control_substance',
                'report_period_month' => 12,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'reporting_quarter' => 'Q4-2025',
                    'controlled_schedule_ii' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'controlled_schedule_iii' => [
                        'items' => [
                            ['drug_name' => 'Amoxicillin 500mg', 'received' => 160, 'dispensed' => 148, 'balance' => 12],
                            ['drug_name' => 'Azithromycin 250mg', 'received' => 35, 'dispensed' => 30, 'balance' => 5],
                        ],
                        'total_received' => 195,
                        'total_dispensed' => 178,
                        'balance_stock' => 17,
                    ],
                    'controlled_schedule_iv' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'discrepancies' => [],
                    'auditor_name' => 'Rehema Mwangaza',
                    'auditor_designation' => 'Pharmacist In-Charge',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Cooperative Drug Authority (TCDA)',
                'submitted_at' => '2026-01-08 14:00:00',
                'approved_by' => 'Mr. Festo Mcha',
                'notes' => 'Quarterly controlled substances report for Q4 2025. Year-end reconciliation completed.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 12,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 205,
                    'total_otc_sales' => 310,
                    'total_revenue' => 2880000.00,
                    'total_discounts' => 82000.00,
                    'net_revenue' => 2798000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 112, 'revenue' => 648000.00],
                        'analgesics' => ['units_sold' => 138, 'revenue' => 395000.00],
                        'vitamins' => ['units_sold' => 155, 'revenue' => 438000.00],
                    ],
                    'expired_returns_count' => 4,
                    'expired_returns_value' => 32000.00,
                    'compliance_notes' => 'Year-end inventory count completed. All controlled substances accounted for.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2026-01-05 09:15:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for December 2025. Year-end compliance review passed.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 11,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 198,
                    'total_otc_sales' => 302,
                    'total_revenue' => 2780000.00,
                    'total_discounts' => 72000.00,
                    'net_revenue' => 2708000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 108, 'revenue' => 625000.00],
                        'analgesics' => ['units_sold' => 135, 'revenue' => 388000.00],
                        'respiratory' => ['units_sold' => 78, 'revenue' => 295000.00],
                    ],
                    'expired_returns_count' => 2,
                    'expired_returns_value' => 16000.00,
                    'compliance_notes' => 'Steady month. Respiratory medications up due to rainy season.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-12-05 10:30:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for November 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 10,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 210,
                    'total_otc_sales' => 325,
                    'total_revenue' => 2980000.00,
                    'total_discounts' => 78000.00,
                    'net_revenue' => 2902000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 115, 'revenue' => 665000.00],
                        'analgesics' => ['units_sold' => 142, 'revenue' => 408000.00],
                        'cardiovascular' => ['units_sold' => 102, 'revenue' => 558000.00],
                    ],
                    'expired_returns_count' => 3,
                    'expired_returns_value' => 22000.00,
                    'compliance_notes' => 'Full compliance maintained. No incidents reported.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-11-04 08:45:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for October 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'annual_compliance',
                'report_period_month' => 12,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'annual_revenue' => 34500000.00,
                    'total_prescriptions' => 2580,
                    'total_otc_sales' => 3850,
                    'total_customers_served' => 1245,
                    'controlled_substance_incidents' => 0,
                    'dispensing_errors' => 0,
                    'cold_chain_breaches' => 0,
                    'expiry_returns_total' => 42,
                    'expiry_returns_value' => 385000.00,
                    'staff_training_hours' => 120,
                    'gpp_compliance_score' => 96.5,
                ]),
                'status' => 'submitted',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2026-01-20 11:00:00',
                'approved_by' => null,
                'notes' => 'Annual compliance report for 2025. Comprehensive review of all pharmacy operations, safety records, and regulatory compliance.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 8,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'total_prescriptions' => 145,
                    'total_otc_sales' => 210,
                    'total_revenue' => 1920000.00,
                    'total_discounts' => 55000.00,
                    'net_revenue' => 1865000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 78, 'revenue' => 448000.00],
                        'analgesics' => ['units_sold' => 98, 'revenue' => 282000.00],
                        'antimalarials' => ['units_sold' => 72, 'revenue' => 245000.00],
                    ],
                    'expired_returns_count' => 1,
                    'expired_returns_value' => 9000.00,
                    'compliance_notes' => 'Month in progress. Data partial as of mid-July.',
                ]),
                'status' => 'draft',
                'submitted_to' => null,
                'submitted_at' => null,
                'approved_by' => null,
                'notes' => 'Draft report for upcoming month. Being compiled from POS data.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'control_substance',
                'report_period_month' => 9,
                'report_period_year' => 2026,
                'report_data' => json_encode([
                    'reporting_quarter' => 'Q3-2026',
                    'controlled_schedule_ii' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'controlled_schedule_iii' => [
                        'items' => [
                            ['drug_name' => 'Amoxicillin 500mg', 'received' => 220, 'dispensed' => 195, 'balance' => 25],
                            ['drug_name' => 'Azithromycin 250mg', 'received' => 45, 'dispensed' => 40, 'balance' => 5],
                        ],
                        'total_received' => 265,
                        'total_dispensed' => 235,
                        'balance_stock' => 30,
                    ],
                    'controlled_schedule_iv' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'discrepancies' => [],
                    'auditor_name' => 'Rehema Mwangaza',
                    'auditor_designation' => 'Pharmacist In-Charge',
                ]),
                'status' => 'draft',
                'submitted_to' => null,
                'submitted_at' => null,
                'approved_by' => null,
                'notes' => 'Draft quarterly controlled substances report for Q3 2026. Data collection in progress.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 7,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 192,
                    'total_otc_sales' => 288,
                    'total_revenue' => 2650000.00,
                    'total_discounts' => 65000.00,
                    'net_revenue' => 2585000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 102, 'revenue' => 592000.00],
                        'analgesics' => ['units_sold' => 128, 'revenue' => 365000.00],
                        'antimalarials' => ['units_sold' => 95, 'revenue' => 328000.00],
                    ],
                    'expired_returns_count' => 3,
                    'expired_returns_value' => 25000.00,
                    'compliance_notes' => 'Malaria season impact visible in antimalarial sales.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-08-05 09:30:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for July 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 6,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 178,
                    'total_otc_sales' => 265,
                    'total_revenue' => 2420000.00,
                    'total_discounts' => 58000.00,
                    'net_revenue' => 2362000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 95, 'revenue' => 548000.00],
                        'analgesics' => ['units_sold' => 118, 'revenue' => 338000.00],
                        'dermatology' => ['units_sold' => 68, 'revenue' => 245000.00],
                    ],
                    'expired_returns_count' => 2,
                    'expired_returns_value' => 18000.00,
                    'compliance_notes' => 'Dermatology sales up due to skin infection season.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-07-05 10:00:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for June 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 5,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 185,
                    'total_otc_sales' => 275,
                    'total_revenue' => 2530000.00,
                    'total_discounts' => 62000.00,
                    'net_revenue' => 2468000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 98, 'revenue' => 565000.00],
                        'analgesics' => ['units_sold' => 122, 'revenue' => 350000.00],
                        'cardiovascular' => ['units_sold' => 88, 'revenue' => 485000.00],
                    ],
                    'expired_returns_count' => 3,
                    'expired_returns_value' => 26000.00,
                    'compliance_notes' => 'Steady month. Cardiovascular category showing growth.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-06-05 08:45:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for May 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'control_substance',
                'report_period_month' => 6,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'reporting_quarter' => 'Q2-2025',
                    'controlled_schedule_ii' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'controlled_schedule_iii' => [
                        'items' => [
                            ['drug_name' => 'Amoxicillin 500mg', 'received' => 190, 'dispensed' => 175, 'balance' => 15],
                            ['drug_name' => 'Azithromycin 250mg', 'received' => 38, 'dispensed' => 32, 'balance' => 6],
                        ],
                        'total_received' => 228,
                        'total_dispensed' => 207,
                        'balance_stock' => 21,
                    ],
                    'controlled_schedule_iv' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'discrepancies' => [],
                    'auditor_name' => 'Rehema Mwangaza',
                    'auditor_designation' => 'Pharmacist In-Charge',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Cooperative Drug Authority (TCDA)',
                'submitted_at' => '2025-07-10 13:30:00',
                'approved_by' => 'Mr. Festo Mcha',
                'notes' => 'Quarterly controlled substances report for Q2 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 4,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 172,
                    'total_otc_sales' => 255,
                    'total_revenue' => 2340000.00,
                    'total_discounts' => 55000.00,
                    'net_revenue' => 2285000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 92, 'revenue' => 532000.00],
                        'analgesics' => ['units_sold' => 112, 'revenue' => 320000.00],
                        'gastrointestinal' => ['units_sold' => 78, 'revenue' => 298000.00],
                    ],
                    'expired_returns_count' => 4,
                    'expired_returns_value' => 35000.00,
                    'compliance_notes' => 'Slightly higher expiry returns due to seasonal stock adjustments.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-05-05 09:00:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for April 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 3,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 165,
                    'total_otc_sales' => 242,
                    'total_revenue' => 2220000.00,
                    'total_discounts' => 48000.00,
                    'net_revenue' => 2172000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 88, 'revenue' => 508000.00],
                        'analgesics' => ['units_sold' => 105, 'revenue' => 302000.00],
                        'vitamins' => ['units_sold' => 125, 'revenue' => 355000.00],
                    ],
                    'expired_returns_count' => 2,
                    'expired_returns_value' => 17000.00,
                    'compliance_notes' => 'Strong vitamin sales due to health awareness campaign.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-04-05 10:15:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for March 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 2,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 155,
                    'total_otc_sales' => 228,
                    'total_revenue' => 2098000.00,
                    'total_discounts' => 42000.00,
                    'net_revenue' => 2056000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 82, 'revenue' => 475000.00],
                        'analgesics' => ['units_sold' => 98, 'revenue' => 282000.00],
                        'cardiovascular' => ['units_sold' => 78, 'revenue' => 428000.00],
                    ],
                    'expired_returns_count' => 1,
                    'expired_returns_value' => 8000.00,
                    'compliance_notes' => 'Excellent month. Lowest expiry returns of the quarter.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-03-05 08:30:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for February 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 1,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions' => 148,
                    'total_otc_sales' => 215,
                    'total_revenue' => 1975000.00,
                    'total_discounts' => 38000.00,
                    'net_revenue' => 1937000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 78, 'revenue' => 452000.00],
                        'analgesics' => ['units_sold' => 92, 'revenue' => 265000.00],
                        'antimalarials' => ['units_sold' => 68, 'revenue' => 232000.00],
                    ],
                    'expired_returns_count' => 3,
                    'expired_returns_value' => 24000.00,
                    'compliance_notes' => 'New year baseline. All systems operational.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-02-05 09:00:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for January 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'control_substance',
                'report_period_month' => 3,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'reporting_quarter' => 'Q1-2025',
                    'controlled_schedule_ii' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'controlled_schedule_iii' => [
                        'items' => [
                            ['drug_name' => 'Amoxicillin 500mg', 'received' => 170, 'dispensed' => 158, 'balance' => 12],
                            ['drug_name' => 'Azithromycin 250mg', 'received' => 32, 'dispensed' => 28, 'balance' => 4],
                        ],
                        'total_received' => 202,
                        'total_dispensed' => 186,
                        'balance_stock' => 16,
                    ],
                    'controlled_schedule_iv' => [
                        'items' => [],
                        'total_received' => 0,
                        'total_dispensed' => 0,
                        'balance_stock' => 0,
                    ],
                    'discrepancies' => [],
                    'auditor_name' => 'Rehema Mwangaza',
                    'auditor_designation' => 'Pharmacist In-Charge',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Cooperative Drug Authority (TCDA)',
                'submitted_at' => '2025-04-10 14:00:00',
                'approved_by' => 'Mr. Festo Mcha',
                'notes' => 'Quarterly controlled substances report for Q1 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'monthly_sales',
                'report_period_month' => 12,
                'report_period_year' => 2024,
                'report_data' => json_encode([
                    'total_prescriptions' => 135,
                    'total_otc_sales' => 198,
                    'total_revenue' => 1820000.00,
                    'total_discounts' => 35000.00,
                    'net_revenue' => 1785000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 72, 'revenue' => 418000.00],
                        'analgesics' => ['units_sold' => 85, 'revenue' => 245000.00],
                        'vitamins' => ['units_sold' => 95, 'revenue' => 272000.00],
                    ],
                    'expired_returns_count' => 2,
                    'expired_returns_value' => 16500.00,
                    'compliance_notes' => 'Year-end operations. All records reconciled for 2024 annual report.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-01-06 09:00:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for December 2024. Final report for 2024 fiscal year.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 2,
                'report_type' => 'monthly_sales',
                'report_period_month' => 1,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions_filled' => 210,
                    'total_otc_sales' => 215,
                    'total_revenue' => 2050000.00,
                    'total_discounts' => 42000.00,
                    'net_revenue' => 2008000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 80, 'revenue' => 460000.00],
                        'analgesics' => ['units_sold' => 92, 'revenue' => 268000.00],
                    ],
                    'expired_returns_count' => 3,
                    'expired_returns_value' => 22000.00,
                    'compliance_notes' => 'January 2025 report. New year inventory adjustments completed.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-02-05 10:30:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for January 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 3,
                'report_type' => 'monthly_sales',
                'report_period_month' => 2,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions_filled' => 195,
                    'total_otc_sales' => 200,
                    'total_revenue' => 1920000.00,
                    'total_discounts' => 38000.00,
                    'net_revenue' => 1882000.00,
                    'top_selling_categories' => [
                        'antibiotics' => ['units_sold' => 75, 'revenue' => 430000.00],
                        'vitamins' => ['units_sold' => 88, 'revenue' => 255000.00],
                    ],
                    'expired_returns_count' => 1,
                    'expired_returns_value' => 12000.00,
                    'compliance_notes' => 'February 2025 report. Valentine health campaign completed.',
                ]),
                'status' => 'approved',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-03-04 09:15:00',
                'approved_by' => 'Dr. Stephen Mwakasege',
                'notes' => 'Monthly pharmacy sales report for February 2025.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 4,
                'report_type' => 'control_substance',
                'report_period_month' => 3,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions_filled' => 88,
                    'total_otc_sales' => 0,
                    'total_revenue' => 450000.00,
                    'total_discounts' => 0.00,
                    'net_revenue' => 450000.00,
                    'controlled_substances_dispensed' => 88,
                    'scheduled_drugs_record' => [
                        'schedule_ii' => 35,
                        'schedule_iii' => 53,
                    ],
                    'compliance_notes' => 'Q1 2025 controlled substance quarterly report. All records verified.',
                ]),
                'status' => 'submitted',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-04-08 11:00:00',
                'approved_by' => null,
                'notes' => 'Q1 2025 controlled substance report for regulatory compliance.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'pharmacy_id' => 1,
                'report_type' => 'annual_compliance',
                'report_period_month' => 6,
                'report_period_year' => 2025,
                'report_data' => json_encode([
                    'total_prescriptions_filled' => 1350,
                    'total_otc_sales' => 1420,
                    'total_revenue' => 12800000.00,
                    'total_discounts' => 285000.00,
                    'net_revenue' => 12515000.00,
                    'compliance_notes' => 'Mid-year 2025 compliance review. All operations within regulatory guidelines.',
                ]),
                'status' => 'submitted',
                'submitted_to' => 'Tanzania Medicines and Medical Devices Authority (TMDA)',
                'submitted_at' => '2025-07-05 08:30:00',
                'approved_by' => null,
                'notes' => 'H1 2025 semi-annual compliance report for TMDA review.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('regulatory_reports')->insert($records);
    }
}
