/**
 * Font Awesome stand-ins for the `@mui/icons-material` imports still present in
 * un-migrated pages. Every MUI icon name is re-exported as a component rendering the
 * closest Font Awesome glyph, so existing `<SomeRounded />` JSX keeps working while the
 * UI moves to the Font Awesome icon set.
 *
 * Generated by tools/gen-icons.py - add entries there when new icons appear.
 */

import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowLeft,
  faArrowTrendDown,
  faArrowTrendUp,
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBell,
  faBook,
  faBox,
  faBoxesStacked,
  faBriefcase,
  faBullhorn,
  faCalendar,
  faCalendarDay,
  faChartColumn,
  faCheckDouble,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChurch,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlay,
  faCircleQuestion,
  faClipboardList,
  faClock,
  faCodeBranch,
  faCommentSms,
  faComputerMouse,
  faCreditCard,
  faDna,
  faDownload,
  faEllipsisVertical,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFilePdf,
  faFilter,
  faFingerprint,
  faFlag,
  faFlask,
  faFloppyDisk,
  faGear,
  faHospital,
  faHourglass,
  faIdCard,
  faLightbulb,
  faListCheck,
  faLocationDot,
  faMagnifyingGlass,
  faMagnifyingGlassLocation,
  faMars,
  faMoneyBill,
  faMoneyBillTransfer,
  faNoteSticky,
  faPalette,
  faPaperPlane,
  faPaperclip,
  faPen,
  faPercent,
  faPhone,
  faPhoneVolume,
  faPills,
  faPlay,
  faPlus,
  faPrint,
  faReceipt,
  faRepeat,
  faRightFromBracket,
  faRightLeft,
  faRightToBracket,
  faSackDollar,
  faStar,
  faStethoscope,
  faStop,
  faStopwatch,
  faTags,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faUser,
  faUserPlus,
  faUsers,
  faVenus,
  faWallet,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

const make = (icon) => {
  const Component = ({ className = "", ...rest }) => (
    <FontAwesomeIcon
      icon={icon}
      className={`w-5 h-5 ${className}`.trim()}
      {...rest}
    />
  );
  Component.displayName = icon.iconName;
  return Component;
};

export const AccessTimeRounded = make(faClock);
export const AccountBalanceWalletRounded = make(faWallet);
export const Add = make(faPlus);
export const AddRounded = make(faPlus);
export const ArrowBack = make(faArrowLeft);
export const ArrowBackRounded = make(faArrowLeft);
export const ArrowDropDownRounded = make(faChevronDown);
export const AssessmentRounded = make(faChartColumn);
export const AssignmentRounded = make(faClipboardList);
export const AttachMoneyRounded = make(faMoneyBill);
export const AttachmentRounded = make(faPaperclip);
export const BadgeRounded = make(faIdCard);
export const BiotechRounded = make(faDna);
export const CalendarMonthRounded = make(faCalendar);
export const CalendarTodayRounded = make(faCalendarDay);
export const CancelRounded = make(faXmark);
export const CategoryRounded = make(faTags);
export const CheckCircleRounded = make(faCircleCheck);
export const ChevronLeftRounded = make(faChevronLeft);
export const ChevronRightRounded = make(faChevronRight);
export const ChurchRounded = make(faChurch);
export const CloseRounded = make(faXmark);
export const CreditCardRounded = make(faCreditCard);
export const Delete = make(faTrash);
export const DeleteRounded = make(faTrash);
export const DoneAllRounded = make(faCheckDouble);
export const DownloadRounded = make(faDownload);
export const Edit = make(faPen);
export const EditRounded = make(faPen);
export const EmailRounded = make(faEnvelope);
export const ErrorOutlineRounded = make(faCircleExclamation);
export const ErrorRounded = make(faCircleExclamation);
export const EventNoteRounded = make(faNoteSticky);
export const ExitToAppRounded = make(faRightFromBracket);
export const FemaleRounded = make(faVenus);
export const FilterAltRounded = make(faFilter);
export const FilterList = make(faFilter);
export const FingerprintRounded = make(faFingerprint);
export const FlagRounded = make(faFlag);
export const GroupRounded = make(faUsers);
export const HourglassEmptyRounded = make(faHourglass);
export const InfoRounded = make(faCircleInfo);
export const Inventory2Rounded = make(faBoxesStacked);
export const InventoryRounded = make(faBox);
export const LibraryBooksRounded = make(faBook);
export const LightbulbRounded = make(faLightbulb);
export const LocalActivityRounded = make(faBullhorn);
export const LocalHospitalRounded = make(faHospital);
export const LocalPharmacyRounded = make(faPills);
export const LocalShippingRounded = make(faTruck);
export const LocationOnRounded = make(faLocationDot);
export const LocationSearchingRounded = make(faMagnifyingGlassLocation);
export const LoginRounded = make(faRightToBracket);
export const MaleRounded = make(faMars);
export const MedicalServicesRounded = make(faStethoscope);
export const MedicationRounded = make(faPills);
export const MonetizationOnRounded = make(faSackDollar);
export const MoneyOffRounded = make(faPercent);
export const MoreVertRounded = make(faEllipsisVertical);
export const MouseRounded = make(faComputerMouse);
export const NorthEastRounded = make(faArrowUpRightFromSquare);
export const NoteAltRounded = make(faNoteSticky);
export const NotificationsRounded = make(faBell);
export const PaletteRounded = make(faPalette);
export const PaymentRounded = make(faCreditCard);
export const PaymentsRounded = make(faMoneyBillTransfer);
export const PeopleRounded = make(faUsers);
export const Person2Rounded = make(faUser);
export const PersonAddRounded = make(faUserPlus);
export const PersonRounded = make(faUser);
export const PhoneInTalkRounded = make(faPhoneVolume);
export const PhoneRounded = make(faPhone);
export const PictureAsPdfRounded = make(faFilePdf);
export const PlayArrowRounded = make(faPlay);
export const PlayCircleRounded = make(faCirclePlay);
export const PrintRounded = make(faPrint);
export const QuestionMarkRounded = make(faCircleQuestion);
export const ReceiptRounded = make(faReceipt);
export const RefreshRounded = make(faArrowsRotate);
export const RepeatRounded = make(faRepeat);
export const SaveRounded = make(faFloppyDisk);
export const ScheduleRounded = make(faClock);
export const ScienceRounded = make(faFlask);
export const Search = make(faMagnifyingGlass);
export const SearchRounded = make(faMagnifyingGlass);
export const SendRounded = make(faPaperPlane);
export const SettingsRounded = make(faGear);
export const SmsRounded = make(faCommentSms);
export const SourceRounded = make(faCodeBranch);
export const StarRounded = make(faStar);
export const StopRounded = make(faStop);
export const TaskRounded = make(faListCheck);
export const TimerRounded = make(faStopwatch);
export const TransferWithinAStationRounded = make(faRightLeft);
export const TrendingDownRounded = make(faArrowTrendDown);
export const TrendingUpRounded = make(faArrowTrendUp);
export const Visibility = make(faEye);
export const VisibilityOff = make(faEyeSlash);
export const VisibilityRounded = make(faEye);
export const WarningRounded = make(faTriangleExclamation);
export const WorkRounded = make(faBriefcase);
